### ISSUE TITLE
Formality

### ISSUE THREAD

**Issue by ghost** [Just-Natsuki-Team/NatsukiModDev#1]
Hi there, I'm interested in contributing to this repository. However I see many things which may take a lot of work to implement so I'll likely do this over multiple pull requests.

Right now, the first thing I want to focus on is cleaning up the code. I see a lot of code dedicated to making references and such, but in the interest of the mod, I'd like to ask your direction here. Do we want to have it take a more serious direction as in Monika After Story style or Just Yuri style?

If you do want to go that route, I'm likely going to take out a bunch of the references (as it becomes easier to manage the code too)

Just wanted to get a feel on the direction you guys were going for.

**Comment by JustNatNat** [comment]
Test comment, pls ignore

**Comment by JustNatNat** [comment]
test
