### ISSUE TITLE
[SUGGESTTION AND QUESTION] Why aren't the game files in RPA form?

### ISSUE THREAD

**Issue by kat-glitch-turtle** [Just-Natsuki-Team/NatsukiModDev#115]
I know this is a stupid question but why aren't the game files in .rpa archives? This isn't more of an issue but rather something of "Do you want every joe schmoe to be able to edit the game files and make something" I don't see any reason why the files can't be RPAs but it's just something I was wondering
Thanks for reading!

**Comment by multimokia** [comment]
We're an open source repository. The idea is to invite anyone and everyone to be able to contribute to the mod, be it new topics for Natsuki to talk about, or even feature additions. So people being able to edit the files is the idea!

Of course, that means while everyone can edit, not all submissions will be *accepted*. If we feel like the content submitted doesn't represent what Natsuki believes in or something that would be appropriate for Natsuki, we would likely reject the pull request adding it if it's not possible to edit.

**Comment by kat-glitch-turtle** [comment]
That makes sense! Thank you for clearing that up
