### ISSUE TITLE
[ FEATURE REQUEST ] - "I Feel..." Update

### ISSUE THREAD

**Issue by SomeRandomGuyOrPerson** [Just-Natsuki-Team/NatsukiModDev#116]
I see in the other mods when people click on the "I feel..." button, it seems to be missing some choices. and doesn't look similar to the other mods.
If you want my idea for adding some features what the people playing this mod wants then its up to you guys. I'm thinking about adding: lonely, anxious, etc.
in the "I Feel..." Option.

**Comment by Blizzardsev** [comment]
Hello! Thank you for your interest.

The admissions ("I feel...") options range does currently include Anxious, although we may look at expanding this in the future to include other emotions.

As it stands, we're currently looking at getting all existing dialogue set up with sprites using our new sprite system, so this (along with any other dialogue suggestion) would be something we'd look at once this is completed.

**Comment by SomeRandomGuyOrPerson** [comment]
I also forgot about this one.

It would be a lot more adorable if you can boop her on the nose, headpat her, pinch her cheek, tickle, etc to Natsuki and will react about those features which people can do to Yuri and Monika. It will be very nice to have that feature. I'm just saying.
click on her nose, head, cheek, etc.

**Comment by Blizzardsev** [comment]
Hi again! Thanks for your input.

As a heads up - each suggestion should be on a new issue, so if in the future you could try and stick to this it would help us out a lot! The idea is that it allows us to discuss/work concepts individually, and it's just generally easier to manage this way.

On your points:

- We're aware that those features may exist for other mods, but if anything, any physical contact with Natsuki would be something we'd want restricted to high levels of affinity. As we see in the base game and side stories, Natsuki isn't really one for physical displays of affection as a general rule, and would want such things to be on her own terms. This isn't to say we're writing off the idea, but it's definitely one we want to approach carefully.
- This is a good call, and it's something I've been thinking about - but as mentioned previously, we do have a **lot** of existing dialogue we need to get working with our new sprites before we take on more (as introducing separate goodbye "Reasons" entails a lot of dialogue work).
