### ISSUE TITLE
[ FEATURE REQUEST ] - Yukata

### ISSUE THREAD

**Issue by EatinBeanz** [Just-Natsuki-Team/NatsukiModDev#123]
I'd be absolutely struck in awe if a yukata outfit was added to Natsuki's wardrobe! I would love to play Hanafuda with Natsuki while she's dressed for the occasion! Please take a look into Hanafuda I feel it would be a very fitting game for Natsuki!

**Comment by Blizzardsev** [comment]
Thanks for your continued interest in our mod!

A yukata is a nice wardrobe idea; I can see that being a nice fit for something like New Year.

As for Hanafuda - could you please clarify more on this point? From a glance, Hanafuda refers to a style of Japanese playing card and not an actual game specifically. Are there any particular games played with Hanafuda that you had in mind?

**Comment by EatinBeanz** [comment]
Sorry about that I actually had no idea there were more games played with Hanafuda other than Koi-Koi. Well, the game I was thinking of was Koi-Koi. An initial dealer called the oya, is decided upon when the game starts. This can be done with any method (rock-paper-scissors, dice roll) the players agree upon. A hanafuda-specific method involves random card draw: each player draws a single card; the player who draws a card from the earliest month is the oya. If both players draw a card from the same month, the player with the higher value card becomes the oya. The other player is called the ko. To deal, the oya deals eight cards to the ko (face down), then to the table (face up), and then to themselves (face down), though this is normally done with two cards at a time. The rest of the cards are set aside as a draw pile, and then the game begins starting with the oya. The object of the game is to form certain card combinations or sets called yaku from cards accumulated in a point pile. Players can gain cards in their point piles by matching cards in their hands, or drawn from the draw pile, with cards on the table. Once a yaku has been made, a player can stop to cash in points, or keep going by declaring Koi Koi, to form additional yaku for more points. The point values assigned to individual cards have no effect on the score, but they are helpful to judge their value in forming yaku. On a player's turn, they may match by suit (that is, by month/flower) any one card in their hand with one on the table and take both into their point pile. If they cannot match a card from their hand, they must discard a card face up to the table. After matching or discarding a card, they then draw one card from the draw pile and place it face up on the playing area. If this card matches any card now on the table, they must match that card and take both for their point pile; otherwise, it becomes part of the table. If the played card matches two cards on the table, the player gets the choice as to which card to match and therefore keep in addition to the played card. In the event that three cards of a same suit are on the table and a player plays the fourth one, they collect all cards of that suit and take them into their point pile. After a player's turn ends, if they made at least one yaku that turn, that player must then make a choice. As for more detail on Koi-koiing the player may end the hand and add the value of their yaku to their point total, or they can choose to continue playing (calling "koi-koi") in an effort to gain more points. In some versions, a player may only call koi-koi once per hand; in others, a player may call koi-koi on multiple yaku-forming turns. Calling koi-koi leaves the player vulnerable, as if their opponent is able to form a yaku before the caller forms another, the opponent gains double their score and the caller earns nothing. If a player has yaku totaling 7 or more points when the hand ends, that player earns twice that value. If a player hits 7 or more points and their opponent had called koi-koi, they get both doubling bonuses for a total of four times their score. The player who won the last hand becomes the new oya, and a new hand is dealt. Should both players ever run out of cards to play without having formed a yaku on the last play, the oya gains one point, and the next hand begins with the same oya (this is called Oya-Ken, meaning "Dealer's Privilege"). Generally, play continues for 12 hands, with each hand representing a month in the year, but the players can decide to play for a different number of rounds before the game starts. Some groups, when gambling, will require the player whose score was multiplied to pay a proportionately larger amount of the winnings (i.e. a player who continued play twice would pay twice as much as the other player, since their score would have been doubled). There is a chart that shows the months, and card combinations I'll try to send them if GitHub allows me to. The game is much less confusing than I explained it's just very difficult trying to explain the game in text without a visual explanation.
![fuda2](https://user-images.githubusercontent.com/96153578/146789082-953696e7-5396-4fa8-9eb0-20cc2dd8315d.png)
That's an image of the suits the "bright" cards are called "light" not "bright"https://www.gamedesign.jp/flash/hanafuda/rule_e.html this shows the suits again and a basic variation of the point system.  https://youtu.be/Y-BkkIOe1uU And, here's a video of 2 people playing Koi-Koi. Koi-koi is a very fun game that is very simple once you learn the suits if you are still confused on anything I texted or sent please just ask I'd be more than happy to explain! Thank you for responding to me, and for your time I really hope you take Koi-Koi into consideration : ) This was really long to type out, so if I misspelt something or I repeated something please forgive me..

**Comment by EatinBeanz** [comment]
Hey sorry I know you're extremely busy creating greatness, but I was really curious about your thoughts on adding Hanafuda (Koi-Koi) if it still doesn't make sense I can try to explain it differently. I would love to play Koi-Koi with Natsuki!

**Comment by EatinBeanz** [comment]
Hey, sorry, I was wondering what were your thoughts on adding koi-koi to Just Natsuki? Did my explanation not make little sense? If you'd like I could try and explain it differently
