### ISSUE TITLE
[ FEATURE REQUEST ] - Hair and Hair Pin Color

### ISSUE THREAD

**Issue by EatinBeanz** [Just-Natsuki-Team/NatsukiModDev#124]
I remember in the original Just Natsuki Mod you were able to change the color of Natty's hair. I don't know if this will still be a feature, but I'd love to dye Natsuki's hair black every once and again, and adjusting her hair pin color would be fun to experiment with too!

**Comment by Blizzardsev** [comment]
Thank you for your interest!

In terms of hair colour/dyeing - this is a possibility, but as it stands we already have a wide range of hairstyles and we'd need to figure out how we want to integrate different hair colours into this - or if we want to keep things true to Natsuki and retain her original hair colour in official distributions.

As for hairclips - yes! Different coloured hairclips are already a feature we plan to introduce.

**Comment by EatinBeanz** [comment]
Awesome, thank you again for your time!
