### ISSUE TITLE
[ FEATURE REQUEST ] - Jacket Thief

### ISSUE THREAD

**Issue by EatinBeanz** [Just-Natsuki-Team/NatsukiModDev#125]
I'd yearn for a glimpse of Nat in your (MC's) black jacket! There could even be unique dialogue for her taking your jacket, and then unlocking it as one of her outfits.

**Comment by Blizzardsev** [comment]
Hello! Thanks again for your interest.

In terms of the context for the mod, we'd very much like to avoid discussion/insertion of MC - this is, after all a place for Natsuki and her player!

However, I do think the idea of Natsuki borrowing a jacket to be very cute and worth consideration.

**Comment by EatinBeanz** [comment]
Yes I agree I just used MC as a description for the jacket being black, but then I went back and typed black. I didn't mean the actual MC's jacket... Sorry for being very convoluted.. （>﹏<）

**Comment by lunulae** [comment]
I do like the idea of this. If nothing else, a random topic about wishing she could steal our jacket/sweater/etc. would be adorable.

If we wanted to take it further, if a custom-outfit gifting system were implemented down the line, a possible conditional for an outfit could be that it's something of yours, changing that earlier random topic.

**Comment by Blizzardsev** [comment]
@lunulae Since Natsuki wouldn't know about the jacket the player owns unless told, perhaps she could dress it up as a question? Then leave briefly, and come back all smug?
