### ISSUE TITLE
Won't Load Up

### ISSUE THREAD

**Issue by ItsSforSamuel** [Just-Natsuki-Team/NatsukiModDev#14]
When I put the file in the game folder, and I follow instructions that I was given, but it won't even boot up, it basically just crashes immediately

**Comment by FukoIbukii** [comment]
Uhh does it say anything or just crash?

**Comment by ItsSforSamuel** [comment]
It doesn't say anything, just crashes

**Comment by FukoIbukii** [comment]
Oh okay you didn’t have any mods installed before this or started the game did you?

**Comment by spaghetsie** [comment]
Hey, could you please send the `log.txt`?

**Comment by spaghetsie** [comment]
Also, please consider joining our discord server for more direct support
