### ISSUE TITLE
[ FEATURE REQUEST ] - Long hair for Natsuki.

### ISSUE THREAD

**Issue by YukoMagic** [Just-Natsuki-Team/NatsukiModDev#142]
# Overview: so i think that it would be amazing if natsuki have longer hair so yeah!
[brief description of what this aims to achieve]

## Must haves: Long hair 
[features that you deem essential for this issue]

## Could haves: N/A
[features that you deem would be good, but not essential, for this issue]

## Is this feature request related to a problem? Please describe.
[prob a feature ]

**Comment by Blizzardsev** [comment]
Will be introduced in #270
