### ISSUE TITLE
[ FEATURE REQUEST ] - More talk about the dokis

### ISSUE THREAD

**Issue by YukoMagic** [Just-Natsuki-Team/NatsukiModDev#143]
# Overview: i think she gonna tallk about the moment that they've been together, complain or compliment about their personality, jokes about them (or their deaths if you guys think natsuki personality fit that) 
[brief description of what this aims to achieve]

## Must haves: Dokis talk
[features that you deem essential for this issue]

## Could haves: N/A
[features that you deem would be good, but not essential, for this issue]

## Is this feature request related to a problem? Please describe.
[prob a feature]

**Comment by Blizzardsev** [comment]
Hiya,

Thanks for raising this as we discussed earlier.

Topics involving the other girls are something we'd like to look at in more detail, for sure. However, we do need to be careful how we approach them: particularly as we have an introductory sequence (coming from Act 3) we need to think about.

Jokes/references to the other girls are fine, but mocking their deaths is absolutely **not** something in-character for Natsuki: we see she cares deeply about Yuri despite everything, for example - I don't think she'd be willing to talk about having just seen her rotting corpse.

We also don't want to cover too much that DDLC/DDLC+ already go over: we want to try and explore new concepts, not retell what our users have already seen in the base game or DDLC+ side stories.

As a starting point, how about a series of topics based on how Natsuki feels about the other girls? I.E:
- How do you feel about Monika?
- How do you feel about Sayori?
- How do you feel about Yuri?

**Comment by YukoMagic** [comment]
Nice!, we can have that topic too, or she can say random things about them in random talks if you guys want!
