### ISSUE TITLE
[ BUG REPORT ] - Error with "alcohol" dialogue

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#163]
## The Bug

I was talking to Natsuki about alcohol and then I an error. Something about the unknown text tag u'w-0.3'
[traceback.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/8055647/traceback.txt)

**Comment by Blizzardsev** [comment]
Thanks for bringing this to our attention! It looks like one of the tags we use to make Natsuki pause in dialogue wasn't correctly written; we'll get this sorted.
