### ISSUE TITLE
Camera reactions happen before starting the game

### ISSUE THREAD

**Issue by TriniTDM** [Just-Natsuki-Team/NatsukiModDev#172]
Natsuki freaked out when I was taking screenshots on the warning page, where she wasn't even present.
![screenshot_15-02-2022_17-29-57](https://user-images.githubusercontent.com/52469676/154535748-3991b373-7747-46ba-9c4e-4cf22ddac81e.png)

**Comment by Blizzardsev** [comment]
Hi @TriniTDM - thanks for raising this to us.

As we're working on redoing the entire introduction sequence to the game (or more accurately, adding one), we'll look to have this resolved as part of that.
