### ISSUE TITLE
[ BUG REPORT ] - Double pet question

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#173]
# The Bug:
When you ask Natsuki about pets not for the first time, she asks the question "What about you?" twice in a row. Here's the example:

![2022-02-18_21-43-57](https://user-images.githubusercontent.com/75726665/154704943-766fc2b1-0004-4446-913b-84530f0a553d.png)

**Comment by Blizzardsev** [comment]
Thanks for bringing this up to us!

We'll take a look shortly.
