### ISSUE TITLE
[ SUPPORT REQUEST ] - Photo request

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#175]
# The Problem:
So, I know that Nat doesn't like surprise pictures, but I can't find the option for her to allow screenshot her. I already (accidentaly, though) took a picture of her, so now I can tell her that I won't make a screenshot without her approval. Do I need to spend more time with her or should I do something else?

**Comment by FastestDan** [comment]
The only option in "Photography" section is "How do you feel about having your picture taken?"
Here's the persistent: [persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/8099174/persistent.zip)

**Comment by Blizzardsev** [comment]
Thanks for the information!

We now have a fix pending review; unfortunately as we do not yet have a mechanism for migrating persistent data from one update to another, you will need to delete your existing persistent file and restart the game once you have downloaded the updated mod files.

Apologies for the inconvenience!
