### ISSUE TITLE
[ FEATURE REQUEST ] - Changing our name

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#185]
# The Idea:
I think that we should have an option for Natsuki to call us by different name. Kinda like in MAS/Just Yuri mods. It can(or should) be locked by level of Relationship and/or Trust.

## Additional Ideas:
If player enters an "easter egg" name, Natsuki can react to it. She can also react if player changes their name to the name of one of the DDLC members(special reation if player's name is "Natsuki"). Maybe she can lose some Trust/Relashionship with the player if they enter inappropriate (for Natsuki) name, like "Senpai" or "Onii-chan".

**Comment by Blizzardsev** [comment]
Hello,

Thanks for your suggestion! As it stands, the player does get the ability to nickname Natsuki at higher affinity levels, so having the inverse seems reasonable to me.

@multimokia @spaghetsie - thoughts?

**Comment by multimokia** [comment]
Yes please

**Comment by lunulae** [comment]
As a reminder to myself, I might add in some joke dialogue for a few nicknames. "Senpai" comes to mind, maybe a few others. ;P

**Comment by Blizzardsev** [comment]
Can't link directly as we've hit the maximum number of issues, but closing this under the assurance that this feature will be in the next update!
