### ISSUE TITLE
My naming issue

### ISSUE THREAD

**Issue by tejasguruji098** [Just-Natsuki-Team/NatsukiModDev#197]
i am actually having a problem in naming my self 'tejas' . as i typed this name natsuki wont allow me to have it.
does my name is some kinda vulgar word in any language. as far as i know its not so please fix this name so that i can use my name in the game.

Anyway thanks for this aweasome/ fantastic mod as far as i have played i dont find any issues or bugs its in good progress.

Tejas

**Comment by Blizzardsev** [comment]
Thanks for bringing this to our attention - we'll take a look.
