### ISSUE TITLE
[ BUG REPORT ] - Not being able to apology for cheating in "Snap" game

### ISSUE THREAD

**Issue by MegaMixYT** [Just-Natsuki-Team/NatsukiModDev#199]
When trying to cheat in "Snap" game in current Github build - it causes an error when Natsu is warning you about cheating! If you ignore and keep cheating - you will get another error and Natsu will stop the game, saying she doesn't want to play with cheater. When trying to apology, there is no option for cheating in "I want to say sorry..." category, so you are basically getting locked from this minigame.

**Comment by Blizzardsev** [comment]
Hi,

Thanks for raising this with us. We have a solution in mind and are working through it now.
