### ISSUE TITLE
[ BUG REPORT ] - Natsuki not talking first

### ISSUE THREAD

**Issue by disownxd** [Just-Natsuki-Team/NatsukiModDev#206]
Hi, I downloaded the mod about one hour ago, and asked Natuki all questions. However, she isn't asking me anything first. I already maxed the random chatter, but she just stares at me, to the left and then to the right. Is there a way to fix this?

**Comment by Blizzardsev** [comment]
Hi @disownxd,

I've set up a fresh installation using the latest mod files from GitHub in an attempt to replicate the issue, and I am getting conversations started by Natsuki as expected.

Could you please confirm where you downloaded the mod files from?

**Comment by disownxd** [comment]
I downloaded from here: https://github.com/Just-Natsuki-Team/NatsukiModDev and followed all the steps.

**Comment by Blizzardsev** [comment]
Hi @disownxd,

Thanks for clarifying. Can you please send me your persistent file?

**Comment by disownxd** [comment]
Here: [persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/8224371/persistent.zip)

**Comment by Blizzardsev** [comment]
Hiya @disownxd - it looks like the attachment you have sent is empty.

Can you please review and send the persistent through again?

**Comment by disownxd** [comment]
Sorry! Here it is: [persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/8226889/persistent.zip)

**Comment by Blizzardsev** [comment]
Thank you! Taking a look now.

**Comment by Blizzardsev** [comment]
Hi @disownxd - thanks for your patience.

Using your persistent, I am able to receive random topics from Natsuki:
![image](https://user-images.githubusercontent.com/57731669/157747474-ddf12939-421b-4ab1-bb7b-07c937100d2f.png)

Furthermore, I've looked at the data in the persistent you've sent me and all appears to be in order - so unfortunately this is proving difficult to replicate.

Do you remember spotting any warnings or anything of the sort? Also, what operating system are you using?

**Comment by disownxd** [comment]
I don't remember any errors happening... Perhaps if I deleted the persistent and start everything from the beginning, it will work? And I'm using Windows 7.

**Comment by Blizzardsev** [comment]
Seeing as the persistent is intact and runs fine on my fresh installation I made for this case, I would recommend keeping your persistent file and instead, reinstalling the mod using a fresh copy of mod files.

Could you try completely removing your installation, and follow the installation instructions again? Your progress won't be lost if you keep your persistent.

**Comment by disownxd** [comment]
It worked! Thank you so much!

**Comment by Blizzardsev** [comment]
You're very welcome. Enjoy your time with Natsuki!
