### ISSUE TITLE
[ FEATURE REQUEST ] - Farewell expansion

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#21]
# Overview:
This feature will add a pool of farewell dialogue to be used when the player bids farewell to Natsuki when quitting the game.

## Must haves:
- Natsuki will have a pool of greetings, that vary based on affinity/trust.
- At high affinity/trust, Natsuki will be disheartened at her player's departure, but warmly wish them the best and express her love and care.
- At medium affinity/trust, Natsuki will be disappointed but understanding. She will hope her player has a good day.
- At low affinity/trust, Natsuki is generally aloof and offers lukewarm farewells at best.
- At very low/zero/negative affinity/trust, Natsuki will either express relief that the player is leaving, and may even decline to comment at all.

## Could haves:
N/A

## Is this feature request related to a problem? Please describe.
This is a new feature.

**Comment by JustNatsFang** [comment]
Closing as implemented with #24
