### ISSUE TITLE
[ FEATURE REQUEST ] - "unseen" option

### ISSUE THREAD

**Issue by NathanL0lz** [Just-Natsuki-Team/NatsukiModDev#215]
When you click "talk", the "unseen" option will appear and there gonna be a new topics/questions that you have not yet talked to Natsuki will appear, but when you talk about all these questions/topics, all those topics/questions from the "unseen" will be in the "Let's talk about.." but when there are not new questions/topics the "unseen" option will be invisible  but when there are new topics/questions to Natsuki the option ''unseen'' will reappear

**Comment by Blizzardsev** [comment]
Yes, this is something we can look at when time permits.

**Comment by Blizzardsev** [comment]
Will be introduced in #270
