### ISSUE TITLE
[ FEATURE REQUEST ] - Magical girl dress for natsuki

### ISSUE THREAD

**Issue by YukoMagic** [Just-Natsuki-Team/NatsukiModDev#218]
# Overview:
So you guys are working on oufit rework now, im so happy that finally you guys touch this one lol. So i have an idea about a new oufit for natsuki, i think "magical girl dress" is hard to imagine so i can send you some examples in dm.

## Must haves:
Magical girl dress for natsuki

## Could haves:
accessories comes with the magical girl dress

## Is this feature request related to a problem? Please describe.
N/A

**Comment by kkrosie123** [comment]
Already made it. Thank you for your suggestion though.

**Comment by YukoMagic** [comment]
already know it,i said it in the #general.

**Comment by Blizzardsev** [comment]
Closed, as this is already a planned addition.
