### ISSUE TITLE
[ FEATURE REQUEST ] - Nagomi Yui (Cure Precious) cosplay

### ISSUE THREAD

**Issue by YukoMagic** [Just-Natsuki-Team/NatsukiModDev#219]
# Overview:
So you guys are working in the oufit rework now so i have a suggestion! i would like to see natsuki in cure precious costume so im come up with this haha, hope you guys will touch this soon.

## Must haves:
Cure Precious dress

## Could haves:
Accessories with cure precious dress, civilian dress of Nagomi Yui.

## Is this feature request related to a problem? Please describe.
N/A

**Comment by Blizzardsev** [comment]
Hi @YukoMagic, thanks for your suggestion.

Personally, I'm not 100% sold on this. As it stands, the outfit rework will introduce at least two outfits that already carry the "Magical Girl" theme, and we'd prefer variety over saturation of specific styles.

@kkrosie123 @Nemu-sus any thoughts?

**Comment by kkrosie123** [comment]
Although I could 100% make this, I agree with Blizz. It's too similar to our current magical girl outfit.

**Comment by Blizzardsev** [comment]
Closing, as @kkrosie123 mentioned - too similar to existing outfits, and this could be added as a user-sourced extra when the outfit rework is finished.
