### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki dialogue for hairstyle

### ISSUE THREAD

**Issue by MasterTengu44** [Just-Natsuki-Team/NatsukiModDev#220]
# Overview:
Natsuki should have different dialogue when the player asks her "why do you style your hair like that?" if she has a hairstyle different from her usual hairstyle.

**Comment by Blizzardsev** [comment]
Sure, this is something we can review under the outfit rework.

**Comment by Blizzardsev** [comment]
Will be introduced in #270
