### ISSUE TITLE
(Question) How to raise affection with Natsuki?

### ISSUE THREAD

**Issue by disownxd** [Just-Natsuki-Team/NatsukiModDev#234]
I'm just confused about how the affection system works... Natsuki already talked about all topics available, and I looked at the script-topics.rpy and saw that there's still topics she didn't talk about, but I guess they're unlocked at higher affection? If so, how to raise affection with her, so I can unlock them too? If someone could clarify this, I would appreciate very much.

**Comment by Blizzardsev** [comment]
Hi @disownxd - as we state in the readme, you build up your relationship by spending time with her and generally treating her well. This includes (but is not limited to):

- Visiting often
- Listening to her conversations
- Responding politely when asked questions
- Complementing Natsuki, when available
- Not entering rude inputs when prompted
- Not quitting without warning

If you aren't sure where you stand with Natsuki, you can get a rough estimate by asking her how she feels about you in the "Let's talk about..." -> "You" menu option.

**Comment by disownxd** [comment]
I see. Thank you for clarifying!

**Comment by Blizzardsev** [comment]
No worries. Enjoy your time with Natsuki!
