### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki talks about bullying

### ISSUE THREAD

**Issue by disownxd** [Just-Natsuki-Team/NatsukiModDev#259]
# Overview:

Natsuki talks about bullying in a general way, and her personal experiences with it aswell, like how people constantly made fun of her because of her interests.

## Must haves:

- Natsuki sharing her personal experiences.

- How bullying affects a person's life.

- How people seem to dismiss bullying (especially in schools) as a form of harassment.

- How people who bully others are possibly being bullied too, and that's the reason why they do it.

- Natsuki tells the player that, despite her teasing sometimes, she would never say something that could potentially hurt the player emotionally or harm the player's mental health.

- And of course, how wrong bullying is.

## Could haves:

- Natsuki asks if the player ever suffered bullying, or bullied someone.

- Depending on the affection/trust level, Natsuki acts angry and protective of the player if they suffered bullying, and/or gets upset at a low affection/trust level if the player ever bullied someone.

- Natsuki gets more emotional if the affection/trust level is high when sharing her personal experiences.

**Comment by Blizzardsev** [comment]
Some good inspiration for a topic here!

It's also pretty fitting for Natsuki to talk about, given her experiences in DDLC+ as you mentioned.

We'll see what we can do!
