### ISSUE TITLE
[ FEATURE REQUEST ] - Lifestyle/staying healthy topic bundle

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#26]
# Overview:
This feature will add a range of topics where Natsuki will discuss her concern for the player, and how they can best stay healthy.

## Must haves:
- All topics must be prompted by Natsuki, due to her concern for her player, rather than being player-driven/asked topics.
- All topics must be gated by a positive affinity level, from HAPPY onwards.
- All topics will vary slightly in dialogue based on affinity.
- New topic "Using a computer properly", where Natsuki will discuss sitting posture, taking breaks from the screen and so on.
- New topic "Staying active", where Natsuki will stress the importance of getting regular exercise.
- New topic "Relieving stress", where Natsuki will advise the player on how they can better handle stressful situations.
- New topic "Careful spending", where Natsuki will advise the player against both excess spending and excess frugality.
- New topic "Eating well", where Natsuki places emphasis on the importance of a good diet, and advises against things like excess junk food, soft drinks and so on.

## Could haves:
N/A

## Is this feature request related to a problem? Please describe.
This is a new feature.

**Comment by spaghetsie** [comment]
Could be unlocked by stuff like player activity for example - opening the game late, Natsuki could discuss the importance of a healthy sleep schedule.

Or possibly if the player stays active from 10:00 to 14:00 Natsuki could ask if they've even eaten yet - if not, scolding the player for not eating properly

**Comment by Blizzardsev** [comment]
> Could be unlocked by stuff like player activity for example - opening the game late, Natsuki could discuss the importance of a healthy sleep schedule.
> 
> Or possibly if the player stays active from 10:00 to 14:00(10am to 2pm) Natsuki could ask if they've even eaten yet - if not, scolding the player for not eating properly

I agree; we can still affinity lock it of course but I also like the idea of having them unlocked contextually in addition to that. It'll also expand the lifespan of the mod by having more topics that are unlocked in specific ways, by giving our users more to discover (even if accidentally)

**Comment by Blizzardsev** [comment]
I'm thinking of the following unlock criteria, as well as affinity:
- Using a computer properly: Game session of at least four hours
- Staying active: At least 10 recorded visits/launches of JN
- Relieving stress: N/A, aff. only
- Careful spending: N/A, aff. only
- Eating well: Game session kept open between 10:00AM : 2:00PM without closure.
