### ISSUE TITLE
[ FEATURE REQUEST ] - "Can I hug you?" Option

### ISSUE THREAD

**Issue by NathanL0lz** [Just-Natsuki-Team/NatsukiModDev#263]
So after spending time with Natsuki there gonna be a ''Can I hug you?" Option. And if you just hug her for a seconds she gonna be a little sad. When you hug her maybe 5 minutes she gonna be happy but, when you hug her 6-30 minutes she gonna thanks you for a long hug.  
And if you hug her more than 30 minutes she gonna fall asleep and if you click her there gonna be 2 options one is: Wake her up and the another option is Let her rest on you.

**Comment by Blizzardsev** [comment]
This is a cute idea!

By the sounds of it, this is somewhat inspired by a similar feature on MAS so we'd want to spin a Natsuki flavour on it to keep things fresh and original.

@multimokia thoughts?

**Comment by Blizzardsev** [comment]
I think given Natsuki's personality and how we use physical displays of affection for sensitive/emotional events (such as the confession, or holidays at higher affinity levels - with Natsuki _herself_ initiating them), having the ability to just ask Natsuki for hugs whenever would feel somewhat out of place - and with the newer headpats feature, a physical means of showing affection to Nat in a way that wouldn't feel overwhelming to her does already exist at this stage.
