### ISSUE TITLE
[ FEATURE REQUEST ] - Pets topic bundle

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#27]
# Overview:
This feature will introduce a range of topics about pets, animals in service, and so on.

## Must haves:
- New topic "Did you ever own any pets?"; where Natsuki discusses how she was never allowed to keep a pet at home due to the strictness of her parents, and express her wish to have owned something. Natsuki will then return the question, and react based on what the player chooses as their pet.
- New topic "Animals at work"; where Natsuki discusses the use of emotional support animals, perhaps making reference to Sayori and how one did/may have helped her.

## Could haves:
- Natsuki may ask the player for the name of their pet, and occasionally ask about them as another topic. Alternatively, this could be followed up in another issue to account for things like pets being unwell, passing away, etc.

## Is this feature request related to a problem? Please describe.
This is a new feature.

**Comment by Blizzardsev** [comment]
In terms of player pet responses, I think the following would suit Natsuki's personality well:

- Loves: Rodents (mice, hamsters, gerbils, rabbits, etc.), Cats
- Likes: Dogs
- Indifferent: Birds, Fish
- Dislikes: Reptiles, Amphibians
- Hates: Insects, Arachnids

It should be noted that:

- Indifferent doesn't mean she doesn't think they're good pets, more that she doesn't personally see the appeal, but can understand why others would.
- Dislikes are generally animals she finds somewhat off-putting, but again wouldn't chastise someone over owning.
- Hates are animals she is personally grossed out by, but wouldn't think less of somebody for owning.

**Comment by Trainerbluetube** [comment]
I could work on this since I'm not doing anything else at the moment.
