### ISSUE TITLE
[ SUPPORT REQUEST ] - Affection/Progress with Natsuki

### ISSUE THREAD

**Issue by FanOfEveryone** [Just-Natsuki-Team/NatsukiModDev#276]
Overview:
Hello, I have been having problems with the current build of the mod. Currently, I have been playing this mod for around a month now and haven't been getting new topics or anything for at least 2 weeks. I am just wondering if there is anything I need to do to unlock things or do I need to wait more longer for stuff to start unlocking?

I also have looked over the other issues:
#242
#234 

Thanks again for using your time to go through this with me. And I am sorry in advanced if I set the layout of this issue wrong or I don't respond that quick.

**Comment by Blizzardsev** [comment]
Hiya @FanOfEveryone, thanks for raising your request with us.

As it stands, content for the mod is fairly spread out - we intend for content to be unlocked over months with the way the affinity system works, but this unfortunately reveals how much we have yet to do in terms of bridging the content gap between affinity levels: there's no easy cure for this besides writing in a ton of stuff (as we're trying to do!).

If it helps, (and if you don't mind **spoilers**), you can find a more detailed list of mod content (and unlock conditions) on our Wiki here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)

**Comment by FanOfEveryone** [comment]
Hello @Blizzardsev,
Thank you for your response.

I've looked through the wiki and the Content of the mod, I have a little understanding on what I would need to do. I just need to give her more time, since everything else is locked until a higher tier of relationship. 
Thank you for your help with this 😊
I hope you have a amazing day.
