### ISSUE TITLE
[ BUG REPORT ] - Error when opening the game

### ISSUE THREAD

**Issue by Yerningcross8** [Just-Natsuki-Team/NatsukiModDev#277]
For the last couple of times I've tried to open the game, I've been hit with a Ren'Py error. I am able to ignore it but I do not know the effects it is having on my game.
Here's the traceback:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 27, in script
    python:
  File "game/script-ch30.rpy", line 53, in <module>
    and jn_events.select_event()
  File "game/script-events.rpy", line 24, in select_event
    affinity=Natsuki._getAffinityState(),
NameError: global name 'Natsuki' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 27, in script
    python:
  File "C:\Users\noahr\Downloads\Natsuki\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\noahr\Downloads\Natsuki\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 53, in <module>
    and jn_events.select_event()
  File "game/script-events.rpy", line 24, in select_event
    affinity=Natsuki._getAffinityState(),
NameError: global name 'Natsuki' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Just Natsuki 4.1.0

**Comment by Blizzardsev** [comment]
Hi @Yerningcross8 - thanks for bringing this up.

Can you please send me your persistent file?

**Comment by Yerningcross8** [comment]
How do you want me to send the file to you? Github doesn't allow the persistent file to be sent in the comments.

**Comment by Blizzardsev** [comment]
Hi @Yerningcross8 - you should be able to drag/drop or paste the file into the comment field from File Explorer. Failing that, you can email a copy of your file here: fubuki@justnatsuki.club

**Comment by Blizzardsev** [comment]
Hi @Yerningcross8 - just as an update. A fix has been built and will be released shortly.
