### ISSUE TITLE
[ BUG REPORT ] - Global Name "Natsuki" is not defined.

### ISSUE THREAD

**Issue by KonekoKoko** [Just-Natsuki-Team/NatsukiModDev#284]
Alright so, myself and other people have experienced this where there is a slight chance the game will come up with an error that refers to loading a certain event, theory is that it's most likely one of those events such as walking in on her reading Manga or something.

I feel like a lot of core features of the mod may be struggling if this is the case.

**Comment by Blizzardsev** [comment]
Hi @KonekoKoko, thanks for bringing this to our attention.

A fix has just been released; if you download a fresh copy of the mod files then you should be able to experience events as planned.

Thanks!
