### ISSUE TITLE
[ SUPPORT REQUEST ] - How can I add my own outfits?

### ISSUE THREAD

**Issue by KonekoKoko** [Just-Natsuki-Team/NatsukiModDev#285]
Heya, I know that you don't have submod support yet, or anything, but I want to ask if there is a certain script or something I can use to manually add outfits for Natsuki to switch into from time to time.

If you could, can I have some pointers or how to do it?

**Comment by Blizzardsev** [comment]
Hi @KonekoKoko, thanks for raising your ticket.

As you've highlighted, we don't currently have a public means of adding outfits in the latest version of the mod.

When the outfit rework has been completed, we'll make sure Wiki instructions are available on how to add outfits.
