### ISSUE TITLE
[ FEATURE REQUEST ] - Skip reaction

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#286]
# The Idea:
JN, like every other game made in RenPy, has the "skip" button. In Original DDLC, as well as in JY, girls have different reactions when that button is pressed to skip their words. I think that Natsuki should also have a reaction to this, since she clearly sees the screenshot flash.

## Essential stuff:
After seeing the "skip" button being pressed, Natsuki should have an apporpriate reaction according to Affinity/Trust values. These values should be decreased after that: the worser relationship there is, the more points deducted. 
## Possible stuff:
On High (or maybe even Normal) Affinity, Natsuki may assume that player did a misclick and give them a warning. On Low Affinity her reaction may be more harsh than on Normal, and because of that, Trust may be decreased, too.

**Comment by Blizzardsev** [comment]
I've just taken a look at this - we don't seem to actually use the skip functionality at all right now! 

Although we feature the _Auto_ function, I would be hesitant to remove this or assign a consequence to it, given the problems in accessibility it could present - and with the removal of the screenshot feature some time ago, we're moving away from more casual gameplay functions having a negative consequence for the player anyway.

Thanks for your suggestion!
