### ISSUE TITLE
Question: Repeat Topics for Progression

### ISSUE THREAD

**Issue by scohn** [Just-Natsuki-Team/NatsukiModDev#289]
I've gone through all the topics currently available to talk about and Natsuki has brought up all the topics available to her.
I have read the description of what to expect saying new topics and features would be unlocked as I grow closer, but is it enough to visit often after the current topics are used or do I need to set her to repat topics to make any progress or is it just time based?
I'm trying to keep focusing on the journey like the description says, I just want to make sure progress is being made.

**Comment by Blizzardsev** [comment]
Hiya @scohn,

I wouldn't worry about not making progress: we aim for content to be unlocked over a longer timescale (weeks/months), so some delays in new content being available is to be expected.

You don't need to worry about having repeat topics on, but it's worth noting that some topics may offer options to respond with that allow you to grow closer beyond simply visiting every day.

You may be interested in the following wiki page, which details all the ways you can grow closer with Natsuki: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#ways-to-gainlose-affinity

**Comment by scohn** [comment]
Thanks for the answer, I figured that was the case but just wanted to be sure. It's pretty clever designing it that way since tsundere's warm up to people slowly, so kudos to you guys.
