### ISSUE TITLE
[ FEATURE REQUEST ] - When I'm gone topic bundle

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#29]
# Overview:
This feature will add topics that cover how Natsuki feels/copes when the player is absent.

## Must haves:
- New topic "Do you feel lonely when I'm gone?"; where Natsuki will talk about how loneliness impacts her based on the current affinity state.
- New topic "What do you do when I'm not around?"; where Natsuki will describe how she keeps - or does not keep - herself occupied when alone, based on the current affinity state.

## Could haves:
- Natsuki may bring mention to particularly long absences, and how they impacted her.

## Is this feature request related to a problem? Please describe.
This is a new feature.

**Comment by Trainerbluetube** [comment]
I can work on this.

**Comment by Trainerbluetube** [comment]
[Natsuki Loneliness topic.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/7501987/Natsuki.Loneliness.topic.txt)
