### ISSUE TITLE
[ SUPPORT REQUEST ] - I don't know what I'm doing wrong, but it doesn't update

### ISSUE THREAD

**Issue by Panko30** [Just-Natsuki-Team/NatsukiModDev#290]
# Overview:
I can't update, i tried everything. I followed the steps correctly about the update, install and uninstall many times. I don't know what to do. 

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Hi @Panko30, thanks for raising a ticket with us.

Would you be able to clarify what you mean by not being able to update? For example, are you seeing any errors, etc?

**Comment by Blizzardsev** [comment]
Hi @Panko30,

Honestly, given we haven't actually released yet, everyone currently playing is in the beta!

The limited options you mention will be down to your relationship with Natsuki; I wouldn't expect many choices to be open that early on, especially as we plan for content to be unlocked over longer timeframes (weeks and months as opposed to days). 

Don't worry, more content will reveal itself as you visit, talk to and generally spend time with Natsuki - if you've played another after-story style mod such as MAS, then progression in Just Natsuki works similarly.

You may also wish to check the wiki here for more information: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki

**Comment by Panko30** [comment]
Ohhhhhh i get it! Sorry to waste your valuable time. Thank you

**Comment by Blizzardsev** [comment]
No worries!
