### ISSUE TITLE
[Question] How many affection points do I need for Natsuki to confess her love to me?

### ISSUE THREAD

**Issue by BrandiBlitz** [Just-Natsuki-Team/NatsukiModDev#293]
I've been asking everywhere for an answer to this.

**Comment by wowm03** [comment]
You can view the features (https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)) if you dont mind spoilers, and it seems like you need to be at least 8 affinity points (enamoured)  to get her to confess love to you.

**Comment by Blizzardsev** [comment]
Hi @BrandiBlitz, thanks for raising an issue with us.

Currently, there is no predetermined special event for Natsuki to confess her love to you: this is something we plan on creating a specific event for when time permits.

When the affinity level is high enough however, the player may express that they love Natsuki herself through the talk menu.

**Comment by BrandiBlitz** [comment]
> Hi @BrandiBlitz, thanks for raising an issue with us.
> 
> 
> 
> Currently, there is no predetermined special event for Natsuki to confess her love to you: this is something we plan on creating a specific event for when time permits.
> 
> 
> 
> When the affinity level is high enough however, the player may express that they love Natsuki herself through the talk menu.

Thank you~
