### ISSUE TITLE
[ FEATURE REQUEST ] - How long have you been wearing ribbons?

### ISSUE THREAD

**Issue by EatinBeanz** [Just-Natsuki-Team/NatsukiModDev#294]
Player asks Natsuki how long she has been wearing ribbons

**Comment by Blizzardsev** [comment]
Hiya @EatinBeanz, thanks for raising a suggestion with us.

Not a bad idea! I think my concern would be the similarity of this topic to an existing topic, where the player may ask Natsuki why she styles her hair how she does: as she goes through various aspects of her usual hairstyle including her twintails, hairband, etc.

I don't think this particular question would be distinct enough for a new topic entirely, but I'd be happy to look into adding this as a section for the existing hairstyle topic as described above.
