### ISSUE TITLE
[ FEATURE REQUEST ] - Can you draw?

### ISSUE THREAD

**Issue by Katrisaph** [Just-Natsuki-Team/NatsukiModDev#295]
Option to ask Natsuki if she can draw/if she's an artist.

**Comment by Blizzardsev** [comment]
Hi @Katrisaph, thanks for raising a suggestion with us.

We do in fact already plan on introducing an artwork topic! Our preferred approach tends to involve Natsuki interjecting her personal experiences into topics she's been asked about, so I'd like to roll this under #79.

Thank you!
