### ISSUE TITLE
Improved/Reworked Affection System

### ISSUE THREAD

**Issue by BrandiBlitz** [Just-Natsuki-Team/NatsukiModDev#296]
As of now, the "daily affection cap" is too "grindy" and needs to be reworked. Unlocking topics takes too long and Natsuki just sits there for 10 minutes. 

How about implementing both Monika & Yuri's affection system into JustNatsuki? That would be for better for a Quality of Life experience with NAS.

**Comment by multimokia** [comment]
For the record, MAS' affection climb is _also_ slow. It's _designed_ to be slow both in JN and MAS as the idea is to effectively simulate a relationship. Additionally speaking, the mod is still heavily in development, as such there's still a lot more we have to add. 

Please do keep in mind you're playing on a developer build of the game where the core focus is implementing the main system backends at the moment. More things to help progress the relationship will come at a later point as more features get implemented and this becomes the larger priority.

**Comment by Blizzardsev** [comment]
Closing as per explanation.
