### ISSUE TITLE
[ BUG REPORT ] - 

### ISSUE THREAD

**Issue by PGMonkeh21** [Just-Natsuki-Team/NatsukiModDev#297]
# Overview: Struggling to install JN mod

## Replication steps:
I follow the steps to install the mod listed on the GitHub site, however, this error comes up whenever I attempt to launch DDLC:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/game/definitions.rpy", line 1155, in script
    init -999 python in jn_utils:
  File "game/game/definitions.rpy", line 1157, in <module>
    import easter
ImportError: No module named easter

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\pharr\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\pharr\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/game/definitions.rpy", line 1155, in script
    init -999 python in jn_utils:
  File "C:\Users\pharr\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\pharr\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/game/definitions.rpy", line 1157, in <module>
    import easter
ImportError: No module named easter

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 
I unfortunately have no experience with downloading mods until now, so I cannot seem to circumvent this issue.

## Additional information:
If you need any extra information, please let me know, thank you!

**Comment by Blizzardsev** [comment]
Hiya @PGMonkeh21, thanks for raising this with us.

It looks like the game is missing a package; these are Python code libraries that the game needs in order to run.

Can you please confirm that you copied the contents of the lib folder from the downloaded mod files into your installation as per the installation instructions?

**Comment by PGMonkeh21** [comment]
Hello, @Blizzardsev thanks for replying!

And yes, I did copy the lib folder from JN into the DDLC lib folder, and have done the process around 6 times with the same results.

If there is any other info that you need, do let me know! Thank you!

**Comment by Blizzardsev** [comment]
Hiya @PGMonkeh21,

Could you please send me a screenshot of your installation, including the contents of the lib folder?

**Comment by PGMonkeh21** [comment]
Of course! (Do let me know if what I sent was incorrect, or if the quality was poor, I am very inexperienced with these sort of issues, thank you!)

**Comment by PGMonkeh21** [comment]
Hello, sorry about the previous comment - I am very new to a laptop, but I managed to take a screenshot directly from my laptop. Do let me know if what I sent is incorrect, thank you
![Screenshot (1)](https://user-images.githubusercontent.com/105133037/167297982-e992824f-06f0-4561-acdc-4828b7c6b5c8.png)
![Screenshot (2)](https://user-images.githubusercontent.com/105133037/167297985-1fdd4d28-e8f4-4b9f-ad66-029ba77df7cc.png)
![Screenshot (3)](https://user-images.githubusercontent.com/105133037/167297989-f9e9e2e1-55f9-491a-99a7-24cf96daa904.png)

![Screenshot (4)](https://user-images.githubusercontent.com/105133037/167297992-99d68d0c-7da1-446a-b1a4-21118621701b.png)
!

**Comment by Blizzardsev** [comment]
Hi @PGMonkeh21, thanks for the screenshots.

It looks like you've copied the lib folder itself into the lib folder of your installation; apologies if the instructions were unclear: what we mean is that the contents of the lib folder from the mod files should be copied into the lib folder of your DDLC installation.

Could you delete the lib folder from your installation as seen on the first screenshot (leaving just the four other folders), then copy the contents of the lib folder from the mod files into the lib folder of your DDLC install?

**Comment by PGMonkeh21** [comment]
I am very sorry, I attempted what I believe you meant and failed - but I think I fail to understand what you are saying. Could you possibly repeat the steps, please? Thank you!

**Comment by multimokia** [comment]
Hi @PGMonkeh21, could you screenshot the contents of the folder called `game` from this image:
![image](https://user-images.githubusercontent.com/22531674/167302214-821887b1-ac5d-4f14-a163-7444bb4b3cee.png)

**Comment by PGMonkeh21** [comment]
Yes, of course:
![Screenshot (5)](https://user-images.githubusercontent.com/105133037/167302616-082a5bc8-0e0c-44d2-abd7-447bfabf4105.png)

**Comment by multimokia** [comment]
There's your issue, you have a `game` folder inside your `game` folder. Take all the contents from the `game` folder you have selected in that last screenshot, and bring it to the one you're looking at

**Comment by PGMonkeh21** [comment]
Sorry, I have completed the step of:
Moving the game folder's contents of my 2nd latest screenshot
Into the game folder of my most recent screenshot

And it does not seem to be working - it comes up with the same error. Did I misunderstand you?

**Comment by multimokia** [comment]
Can you show the contents of the `game` folder now?

**Comment by PGMonkeh21** [comment]
If you mean the game folder copied inside the first one, then of course:
![2022-05-08](https://user-images.githubusercontent.com/105133037/167303010-1f16a71e-0795-4b14-8a07-f0282a95cea6.png)

Apologies that I am causing so much trouble for you due to my misunderstanding.

**Comment by multimokia** [comment]
Looks like you didn't move the files. If you notice the filepath
![image](https://user-images.githubusercontent.com/22531674/167303113-d70eca18-fb23-4e1d-8202-c44b839ea1b8.png)
You're currently in `DDLC-1.1.1-pc/game/game`, we need to only have **one** `game` in the path.

So all of the items here, should be in `DDLC-1.1.1-pc/game`, so you'll want to move all of these items to the above folder.

**Comment by multimokia** [comment]
As a general rule, if you see folders that are with the same name, you want to **merge** their contents (no duplications, just the combinations of their files)

**Comment by PGMonkeh21** [comment]
Okay, very sorry for my poor interpretation of your instructions - I shall attempt now.

**Comment by PGMonkeh21** [comment]
To double check, I  should be attempting to move DDLC-1.1.1-pc/game/ into DDLC-1.1.1-pc/game/game ?

**Comment by multimokia** [comment]
no.

Other way around

**Comment by PGMonkeh21** [comment]
I am attempting do so, but I cannot merge their folders as you described:
![Screenshot (6)](https://user-images.githubusercontent.com/105133037/167304113-3bcf2075-c4d0-47e9-ab36-e4403a31484c.png)

I press skip and supposedly move the files, but the game/game folder is still present?

**Comment by multimokia** [comment]
Okay, do the same steps you're doing, but move to the DDLC-1.1.1-pc folder instead. It'll let you do it

**Comment by PGMonkeh21** [comment]
Thank you so much, it finally worked! I once again apologise for my lack of understanding of your instructions.

**Comment by multimokia** [comment]
No problem

[closing as resolved]
