### ISSUE TITLE
[ FEATURE REQUEST ] - 

### ISSUE THREAD

**Issue by natzrulez** [Just-Natsuki-Team/NatsukiModDev#299]
# Overview:
[Well I saw a new dialogue option has been added, and I totally didn't know about it. So I think it would be good to have some kind of "Unseen" thing like in Monika after story where it shows all the dialogue you haven't chosen.]

## Must haves:
[None really.]

## Could haves:
[I think it would be good if you made it so we could hide it too!]

## Is this feature request related to a problem? Please describe.
[The only problem is I didn't know and I felt a bit bothered that I didn't realize I could ask something new.]

**Comment by Blizzardsev** [comment]
Hi @natzrulez, thanks for raising a suggestion with us.

We're actually already looking at introducing an indication of whether a topic is new or not, and this should be rolled out in the next large-scale update we have planned.
