### ISSUE TITLE
[ FEATURE REQUEST ] - Branded menu sound effects

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#30]
# Overview:
This feature will introduce new sound effects for menuing that better suit the JN experience than the vanilla sound effects.

## Must haves:
- New select/confirm sound for menu items, themed to match Natsuki's theme as heard in DDLC.
- Old select/confirm sound must be removed, as it genuinely sucks.

## Could haves:
N/A

## Is this feature request related to a problem? Please describe.
This is a new feature.

**Comment by lunulae** [comment]
Just a bit of brainstorming, since Natsuki seems to enjoy texting maybe the menu sound effects could sound like retro-cellphone button sounds?

**Comment by Blizzardsev** [comment]
Resolved under #134
