### ISSUE TITLE
 REQUEST- translation in french 

### ISSUE THREAD

**Issue by Klauxjh** [Just-Natsuki-Team/NatsukiModDev#303]
# Overview:
I just want to translate the mod in french if you're ok with it ^^

**Comment by Blizzardsev** [comment]
Hiya @Klauxjh, thanks for raising a suggestion with us.

@multimokia and I have discussed this among the team, and unfortunately we'd prefer if any fan translations were held off for the time being.

As we're in a period of rapid expansion upon the mod, where previous dialogue is still open to change (as well as large amounts of new dialogue coming in), we feel it'd be somewhat self-defeating to attempt a translation at this stage - as well as the risks of translations impacting user save data, as we have sadly seen before on related DDLC mods.

We would also want to build an official means of adding translations using a controlled framework to make adding translations as seamless as possible - no matter the language - and this is unfortunately something I don't see the team working on for a while yet considering the amount of core features still on our list.

However, we'd like to express our thanks for the kind offer, and for approaching us for permission first: we really appreciate it!

**Comment by Klauxjh** [comment]
Thank you for your response, if you change your mind later I would be glad to help you.

 Keep going you're making a awesome mod
