### ISSUE TITLE
Natsuki Not Reacting to Screenshot/Screenshot not Working

### ISSUE THREAD

**Issue by scohn** [Just-Natsuki-Team/NatsukiModDev#305]
I'm trying to take my first screenshot of Natsuki so she can react to it and then unlock the topic to ask for permission but for some reason the screenshot doesn't save in the folder and she has no reaction. I've been hitting Fn+Windows+Print Screen and my screen goes dim for a second but nothing happens. 
Am I doing it right, do I not have high enough affinity, or is there something wrong with the game?

**Comment by Pahaplay** [comment]
> Я пытаюсь сделать свой первый скриншот Нацуки, чтобы она могла на это отреагировать, а затем разблокировать тему, чтобы спросить разрешения, но по какой-то причине скриншот не сохраняется в папке, и она не реагирует. Я нажимаю Fn+Windows+Print Screen, и мой экран тускнеет на секунду, но ничего не происходит. Правильно ли я делаю, у меня недостаточно высокая аффинити или что-то не так с игрой?

you need to press the s button in the game itself and then the reaction will be immediate, make sure that you have caps lock turned off)

**Comment by Pahaplay** [comment]
> I'm trying to take my first screenshot of Natsuki so she can react to it and then unlock the topic to ask for permission but for some reason the screenshot doesn't save in the folder and she has no reaction. I've been hitting Fn+Windows+Print Screen and my screen goes dim for a second but nothing happens. Am I doing it right, do I not have high enough affinity, or is there something wrong with the game?
you need to press the s button in the game itself and then the reaction will be immediate, make sure that you have caps lock turned off)

**Comment by Pahaplay** [comment]
> I'm trying to take my first screenshot of Natsuki so she can react to it and then unlock the topic to ask for permission but for some reason the screenshot doesn't save in the folder and she has no reaction. I've been hitting Fn+Windows+Print Screen and my screen goes dim for a second but nothing happens. Am I doing it right, do I not have high enough affinity, or is there something wrong with the game?

you need to press the s button in the game itself and then the reaction will be immediate, make sure that you have caps lock turned off)

**Comment by scohn** [comment]
I got it to work, I feel like such a dummy for overthinking that. Thanks.

**Comment by Blizzardsev** [comment]
Closing as resolved.
