### ISSUE TITLE
[ FEATURE REQUEST ] - SPOILERS FOR JN, Maybe make Natsuki talk a about her life before JN

### ISSUE THREAD

**Issue by JetstreamNatsuki** [Just-Natsuki-Team/NatsukiModDev#307]
after she confesses to you, even after that treat her nicely and a special type of notif will be heard, she talks bit of bits about her life before JN, yk even tho she confesses to you, you gotta make sure she fully trusts you, and if she asks questions during her talk about her life, you'll have to make the right decisions I am there its up to you devs to do what you like here, then after that or whatever it takes you to the next tier of affection, cause yk theres still another one above where she confesses.

**Comment by Blizzardsev** [comment]
Good news - we do in fact already have dialogue pertaining to Natsuki's life before JN, and her reactions to the events of the game and the other girls. We can look to expand on this in the future of course, but this is something I would like to look at in more detail once we have some of the big ticket items written first.

Thanks for your suggestion!
