### ISSUE TITLE
[FEATURE REQUEST] Rework how Nastuki celebrates holidays & add an "unseen" option.

### ISSUE THREAD

**Issue by BrandiBlitz** [Just-Natsuki-Team/NatsukiModDev#309]
I'd like to celebrate more holidays with Natsuki. Specifically: Valentine's Day, Easter, Fanmade Natsuki's birthday (8/21), Thanksgiving, and Halloween. 

Also, please either add more dialogue for those holidays and/or let the player do something to celebrate holidays with Natsuki (more holiday exclusive minigames or gifts).

How & when are we gonna be able to gift Natsuki some presents?

Please add an "unseen" option for new dialogue that's not already in the starting topic options.

**Comment by Blizzardsev** [comment]
Hiya @BrandiBlitz, thanks for raising a suggestion with us.

We are in fact already working on events! Natsuki's birthday will be included among them, although her birthday has been established among the team as the anniversary date of the mod originally being created.

Regarding the particular holidays you've mentioned: something to bear in mind is that our mod attracts fans from all over the world, and so we strive to be as agnostic as possible towards the national holidays of specific countries: for example, Thanksgiving is only a holiday celebrated in North America, and so wouldn't be familiar to European players, or even Natsuki herself (being Japanese). We would of course plan on adding the more widely globally celebrated holidays such as the new year, Halloween and Christmas.

Gifting is itself something we have planned, but as gifts themselves are a complex system, this would likely be after we have holiday events sorted.

Regarding the unseen option: we already plan to include a visual indication of topics that have been unlocked (and haven't been read yet) in the next update we plan to release in the near future.

Also, going forward: could you please try to keep suggestions to a single suggestion per issue? This better aligns with how we work, and makes keeping tracks of individual suggestions easier.

Thanks!
