### ISSUE TITLE
[ BUG REPORT ] - The "Music Glitch"

### ISSUE THREAD

**Issue by AnimeMizuki-Weeb** [Just-Natsuki-Team/NatsukiModDev#312]
I would like to report a bug on this Mod. It's when you unlock the 'music' option to download and listen to music. But I have downloaded music and I'm 100% certain it's in mp3 format, but for some reason, the music isn't playing. Is this supposed to happen, or what?

**Comment by Blizzardsev** [comment]
Hiya @AnimeMizuki-Weeb, thanks for raising a bug report with us.

Could you confirm where you are placing the music files you have downloaded within your JN installation?

Music files should only be placed in the custom_music folder that Natsuki creates automatically.

**Comment by AnimeMizuki-Weeb** [comment]
Yes, I putted all my music files in the custom_music folder. Natsuki did create it.

**Comment by Blizzardsev** [comment]
Hi @AnimeMizuki-Weeb - are you running the latest version of JN? We did release a fix related to issues some users were experiencing with music files named with certain characters.

Can you please confirm?

**Comment by AnimeMizuki-Weeb** [comment]
Yes, I can confirm that I am running the latest version of JN. But for some reason, the music is still not playing.

**Comment by Blizzardsev** [comment]
Can you please send a screenshot of your custom_music directory, as well as an example file for us to test with?

You can send us a file at fubuki@justnatsuki.club

**Comment by AnimeMizuki-Weeb** [comment]
wait, what do you mean as an "example file?"

**Comment by AnimeMizuki-Weeb** [comment]
<img width="865" alt="Screen Shot 2022-08-13 at 1 15 37 PM" src="https://user-images.githubusercontent.com/105988592/184504163-73e21e1e-d428-4011-aa6f-dacf836195d9.png">
but, like i said, I am using mac, so the custom_music directory might look different.

**Comment by Blizzardsev** [comment]
Example file as in one you've tried to play that has been known not to work, but I own the DDLC+ soundtrack so we're fine on this front. We'll take a look and see what we can figure out.

**Comment by AnimeMizuki-Weeb** [comment]
okay, thank you.

**Comment by Blizzardsev** [comment]
Hi @AnimeMizuki-Weeb - if you update to the newest release, this will be resolved.
