### ISSUE TITLE
[ BUG REPORT ] - can't get the latest update even everything is told to do

### ISSUE THREAD

**Issue by supsonic360** [Just-Natsuki-Team/NatsukiModDev#322]
# Overview:
[brief description of the bug, and the impact created]

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Hi @supsonic360 - as a heads up, it always helps us when our users provide as much information as possible when reporting a bug: going off a title alone makes things difficult for us!

Regarding your issue: could you please explain why you think you might not be on the latest update? We don't currently have a version indicator, and we are aware the limited means of gaining affinity with Natsuki result in slower progress for now. But so long as you have gone through the steps outlined on the readme/wiki, that's all there is to it.

**Comment by Blizzardsev** [comment]
Hi @supsonic360 - could you please help us understand your situation more clearly as per above?
