### ISSUE TITLE
[ BUG REPORT ] - Problem with "I feel tired" option

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#326]
# The Bug:
After unlocking a new step in relashionship with Natsuki I decided to tell her how I felt. I used the "Tired" option specifically. After I pressed the button, an error appeared. You can see it in a "[traceback.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/8862883/traceback.txt)" file.

## The Replication:
Open the game, press the "Talk" button, press the "I feel..." button, press the "Tired" button. Also you may need to set the time to approximately 10 PM.

**Comment by Blizzardsev** [comment]
Hi @FastestDan, thanks for raising a bug report with us and apologies for the delay!

Could you please refer to [this](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/317) issue here? If you download the dropfix file following the instructions given, then this should fix your issue.
