### ISSUE TITLE
[ BUG REPORT ] - Screenshot problem

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#327]
# The Bug:
When I ask for permission to take screenshots, Natsuki says that already have one. However, when I make a picture, she says that I did it without asking. It started happening only after I unlocked the "I feel..." and "I want to tell you something..." options. I'm gonna clip the "[persistent](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/8867282/persistent.zip)" file, just in case.

## The Replication:
Have Natsuki in "Happy" state. Ask her to make screenshots and then take one.

**Comment by AnimeMizuki-Weeb** [comment]
That also happened to me before, I think it's a bug.

**Comment by wowm03** [comment]
> # The Bug:
> When I ask for permission to take screenshots, Natsuki says that already have one. However, when I make a picture, she says that I did it without asking. It started happening only after I unlocked the "I feel..." and "I want to tell you something..." options. I'm gonna clip the "[persistent](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/8867282/persistent.zip)" file, just in case.
> 
> ## The Replication:
> Have Natsuki in "Happy" state. Ask her to make screenshots and then take one.

+1

**Comment by Blizzardsev** [comment]
Hi @FastestDan, thanks for raising this with us.

We'll take a look when we can!

**Comment by Blizzardsev** [comment]
@scohn

**Comment by Blizzardsev** [comment]
As an update - we've come to the decision that we will be looking at retiring the screenshot feature altogether.

As it stands, the screenshot feature has proven problematic for the team through the time it has been available, while we feel it also offers little in return to our users: therefore we plan to cut back on screenshots to a likely one-off reaction, and removing the permissions/consequences aspect altogether.

Given this, I'll be closing this issue and raising another so we don't lose track of what we will be doing.

Thanks for your patience!
