### ISSUE TITLE
[ BUG REPORT ] - snap

### ISSUE THREAD

**Issue by explainfrank** [Just-Natsuki-Team/NatsukiModDev#328]
i wanted to make sure if this is a bug or not. i like playing snap with natsuki every now and then and rematch her. it always starts out slow and easy and she takes a few seconds to call snap if i let her. but after like the first 5 rematches she becomes unbeatable; as soon as one of us places a compatible card she instantly calls snap. i sometimes even have to apologize for cheating because i called snap when i shouldnt have. now is it really cheating when i cant even see what im doing? and it doesnt end there. after apologizing natsuki disables the snap button. so it'll either end up in: 1 - a tie; 2 - i win; 3 - she wins; 4 - she calls snap in the very last moment. thankfully this resets everytime i close the game though. if this is actually a bug then please fix it
thanks

https://user-images.githubusercontent.com/107327380/173207318-db0d1274-fb22-4161-b937-2fed0d9ac25f.mp4

**Comment by explainfrank** [comment]
https://user-images.githubusercontent.com/107327380/173207431-4e185590-5fc4-4f80-96b0-8aa4e0509efb.mp4

here's an unfunny edit i made about this at 3am

**Comment by RaionArt** [comment]
Fixed in v1.0.0.
