### ISSUE TITLE
[ BUG REPORT ] - 

### ISSUE THREAD

**Issue by IllegalSalad** [Just-Natsuki-Team/NatsukiModDev#330]
Something I noticed when opening the log. I think one of the topics aren’t showing up and it is showing an error or something.
![2C02DEF4-94DF-4A83-B0E5-F5B024B4BE04](https://user-images.githubusercontent.com/107746288/174427406-87c88fc2-1cf3-47b9-93e0-48aa655f5811.jpeg)

**Comment by Blizzardsev** [comment]
Hi @IllegalSalad - please refer here for a fix: https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/356
