### ISSUE TITLE
[ BUG REPORT ] - Photo Permission Not Working

### ISSUE THREAD

**Issue by scohn** [Just-Natsuki-Team/NatsukiModDev#334]
I've been trying to get a new screenshot of Natsuki and whenever I go to ask she says I've already asked and to take it soon.
But when I take the screenshot, she acts like I didn't ask and then I have to apologize. I think this might be a bug.

**Comment by Blizzardsev** [comment]
Hi @scohn, thanks for raising this with us.

Another user was kind enough to report this to us also, so we'll close this issue down as a duplicate.

Don't worry - I'll tag you on the related issue so you're kept in the loop.
