### ISSUE TITLE
[ FEATURE REQUEST ] - Can you please make a way to see your relationship level with Natsuki?

### ISSUE THREAD

**Issue by IndependantFlower** [Just-Natsuki-Team/NatsukiModDev#336]
# Overview:
I would like to see how our relation ship is, but I can't find a way to see our affection level

## Must haves:
A way to see affection level with an integer value (Mostly like the affection value in Monika After Story)

## Could haves:
Either a way to see this is the actual game, or just the files

## Is this feature request related to a problem? Please describe.
Not related to a problem

**Comment by multimokia** [comment]
We have no intention to add this feature
