### ISSUE TITLE
[ FEATURE REQUEST ] - Make Natsuki Talk More Frequently Based On Affection Level

### ISSUE THREAD

**Issue by BrandiBlitz** [Just-Natsuki-Team/NatsukiModDev#337]
I wanna suggest to make Natsuki talk to the player more frequently based on how much affection she has for the player.

**Comment by Blizzardsev** [comment]
Hi @BrandiBlitz, thanks for raising another suggestion with us.

This can be done of course, but I would question the value in doing so - JN currently offers a chat frequency setting in the options menu, and we've already shortened the times to a minimum of two minutes: I wouldn't personally think it's worth adding another option based on affinity given the current mechanism.

@multimokia any thoughts?

**Comment by multimokia** [comment]
2 minutes is a very short amount of time, but also feels a lot more natural. If anything keeping this time would keep the experience fresh for longer.

That said I think we can pseudo do this via reserving the 2 minute time for higher affections. When first starting out I think she might be more apprehensive/defensive around you, and might not talk as much, over time as her trust in you grows, maybe she grows a little more comfy talking to you and the slider would allow lower times

**Comment by BrandiBlitz** [comment]
> True, but I think her apprehensiveness/general relationship state is better represented through dialogue itself than the frequency of the dialogue: I see the merit, but I don't really feel as though this is something more rewarding to focus on over things like topics or events.

I see your point. What about special event specific activities? for example, reading manga with Natsuki.

**Comment by Blizzardsev** [comment]
Closing as per explanation given - unfortunately with limited capacity on hand regarding team members - especially active writers - I can't personally justify accelerating the rate at which players run out of topics
