### ISSUE TITLE
[ BUG REPORT ] -  Custom Music AutoPlay Crash

### ISSUE THREAD

**Issue by BrandiBlitz** [Just-Natsuki-Team/NatsukiModDev#338]
the autoplay for custom music works, but crashes when it plays a song that seems to exceed a file size compatibility limit (it may be trying to do multiple things at once).

[traceback.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/9035377/traceback.txt)

**Comment by BrandiBlitz** [comment]
I just noticed in the traceback that it cannot read certain meta data within some songs (aka from official albums)

**Comment by multimokia** [comment]
We don't read metadata of songs. That said, can you screenshot your custom music directory? I'd like to see the filenames to see what caused this. I have an idea but need to confirm

**Comment by BrandiBlitz** [comment]
> We don't read metadata of songs. That said, can you screenshot your custom music directory? I'd like to see the filenames to see what caused this. I have an idea but need to confirm

I just had to delete music files I downloaded from official Youtuber websites (MDK & NCS). The ones that do work are downloaded from Tor sites (3rd party MP3 download sites, like the popular mp3 archive site)

![image](https://user-images.githubusercontent.com/101225938/177061705-c8d8ebe2-baf6-46a5-bdbf-3b9c51e97480.jpeg)
Folders of OSTs and I marked which ones work & don't work

**Comment by multimokia** [comment]
I need the exact song names from your custom music directory, please.

**Comment by BrandiBlitz** [comment]
> I need the exact song names from your custom music directory, please.

Okay, here are the music files (flac version is shown, but I use the mp3 copies I downloaded)
![image](https://user-images.githubusercontent.com/101225938/179127745-df849ccc-9d85-4fe9-b193-8e3857bc6fdf.jpeg)
![image](https://user-images.githubusercontent.com/101225938/179127764-83efa3d2-5345-49e6-b1d2-788e8c62f0ad.jpeg)
![image](https://user-images.githubusercontent.com/101225938/179127783-bd177ffe-4e13-475f-ba2a-4655c3a89893.jpeg)
![image](https://user-images.githubusercontent.com/101225938/179127796-353bb408-14df-46a6-9316-12b902bdec3a.jpeg)
