### ISSUE TITLE
change music bug

### ISSUE THREAD

**Issue by Bella-san** [Just-Natsuki-Team/NatsukiModDev#339]
Hey! So, I have a problem with the "Change music" thing it says 'Cannot find [music_file_name].[ogg/mp3/wav]' but my music files are in the custom_music folder

I press the "Music" menu, and she says "You wanna play smth else? Go for it!" and then when I click any of the music I added, it always says "Cannot find [music_file_name].[ogg/mp3/wav]'". I click ignore and it says that it's playing, yet it isn't playing any sound. I know for sure that my music files have sound since I checked them myself. Can you fix it, please? Oh, and when I click on default, it just plays without any problem at all.

I'm on macOS but I don't think that would mean anything...

**Comment by Blizzardsev** [comment]
Hi @Bella-san, could you please attach a screenshot of the error as well as your custom_music directory?
