### ISSUE TITLE
[ BUG REPORT ] - it won't open dialogue menus including the i feel menu and i want to tell you something menu

### ISSUE THREAD

**Issue by shototodorokifan** [Just-Natsuki-Team/NatsukiModDev#341]
# Overview:
[brief description of the bug, and the impact created]
i been waiting for awhile after getting a high affinity cap point and i still don't have the dialogue options
## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]
i used all diaogue options then waited for some new options to pop up but they never do am i doing something wrong
## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Hi @shototodorokifan, thanks for raising a bug report with us.

Gaining affinity in JN and growing closer with Natsuki is a slow process: could you please send a copy of your persistent to `fubuki@justnatsuki.club`?

**Comment by shototodorokifan** [comment]
the recent was 
![image](https://user-images.githubusercontent.com/109003965/179368089-9e72ef39-741e-43bc-bb7f-d8e353809980.png)

**Comment by Blizzardsev** [comment]
Hi @shototodorokifan, unfortunately a screenshot of your log doesn't help very much in this particular instance; could you please send over your persistent (save data) file?

**Comment by shototodorokifan** [comment]
um how do i do that?

**Comment by shototodorokifan** [comment]
it says i have no saves

**Comment by Blizzardsev** [comment]
Hi @shototodorokifan, if you follow the instructions on the Wiki then you should be able to find your save data: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent

Alternatively, you may wish to use the following guide: https://savelocation.net/renpy

**Comment by shototodorokifan** [comment]
it says it does not support .py files

**Comment by Blizzardsev** [comment]
Hi @shototodorokifan, the persistent shouldn't have a `.py` file extension - as for sending it through, could you please send it to `fubuki@justnatsuki.club`? This is our official support email address - we use this as GitHub only allows specific attachment filetypes.

**Comment by shototodorokifan** [comment]
oh
my bad

**Comment by shototodorokifan** [comment]
it still says file type not supported

**Comment by Blizzardsev** [comment]
Could you please try making a .ZIP file, with the persistent inside, and sending that over?

**Comment by shototodorokifan** [comment]
sure

**Comment by shototodorokifan** [comment]
give me a few minutes to work on that

**Comment by shototodorokifan** [comment]
i sent it in a rar file

**Comment by shototodorokifan** [comment]
cause it won't let me turn it into a zip file for some reason

**Comment by Blizzardsev** [comment]
Hi, it looks like you've unfortunately sent me the Ren'Py source code. I'll need your save data - this should not have any file extension, it should literally just be called `persistent`, and you should be able to find it using the instructions from earlier.

To reiterate: you should be looking in one of the following locations, based on your operating system:

- Windows: %APPDATA%/Roaming/RenPy/JustNatsuki
- OSX: ~/Library/RenPy/JustNatsuki
- Linux: ~/.renpy/JustNatsuki

You should **not** be looking in your JN/DDLC folder.

**Comment by shototodorokifan** [comment]
Oh

**Comment by Blizzardsev** [comment]
![image](https://user-images.githubusercontent.com/57731669/179369305-a0a224ff-7c7a-4d2f-9489-885df004300d.png)

**Comment by shototodorokifan** [comment]
it says no items match the search

**Comment by kkrosie123** [comment]
Hello shototodorokifan, 

If you are on Windows, there is an application you must use to find the %AppData% folder.

Search on your computer for an application called "Run." It will give you a box to input text. In this box, type "%AppData%" - from there follow the directory that BlizzardSev has given you.

**Comment by shototodorokifan** [comment]
uh what does that application look like in order to do that and i'll come back to do that in a bit because i'm going out to eat rn

**Comment by kkrosie123** [comment]
Sorry, I no longer believe we need your persistent. Your progression is normal, and this is not a bug. Please continue to play normally.

Thank you for your time!

**Comment by AToska21** [comment]
bro had enough 💀
