### ISSUE TITLE
[ BUG REPORT ] - Cannot open Just Nastuki in Mod Docker

### ISSUE THREAD

**Issue by RisingVoltageKitsune** [Just-Natsuki-Team/NatsukiModDev#343]
# Overview:
'at' isn't valid so the game doesn't work 

## Replication steps:
follow installation steps and open in mod docker

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on] i use windows 11, monika after story works just fine. had trouble with just yuri, but i play that outside the mod docker

![20220713_110147](https://user-images.githubusercontent.com/109210487/178697934-d686744d-1021-4429-9aa0-7f5d629e53b8.jpg)

this is my first time sending a report so i hope it's passable
 tried to quit the game and this came up
![16577057612892112166943700598313](https://user-images.githubusercontent.com/109210487/178705076-c8dea896-5b4b-4932-aca3-6133f353a8bb.jpg)

**Comment by Blizzardsev** [comment]
@multimokia any ideas? I'm not particularly familiar with Mod Docker myself

**Comment by multimokia** [comment]
Looking at the renpy version, I'm guessing this is an upstream change to screen syntax. If we're planning to do an engine migration at some point to renpy 7.5/8, it's in our best interest to fix this.

Otherwise please ensure you're using an install with renpy 6.99

**Comment by Blizzardsev** [comment]
Hi @RisingVoltageKitsune - as per multi's advice, could you please verify you're using an installation with Ren'Py 6.99?

**Comment by RisingVoltageKitsune** [comment]
i downloaded an old md version 💀 i give myself a headache

**Comment by RisingVoltageKitsune** [comment]
i was using an old version of the mod docker
no idea how i downloaded that while the current one was just above it 💀
guess i'll close the issue for now. thanks for help ig
the current one is compatible eith ren'py 6-7 so i'll check with that later


czw., 14 lip 2022, 23:21 użytkownik multimokia ***@***.***>
napisał:
