### ISSUE TITLE
[ FEATURE REQUEST ] - more different dialogue in the option ''how do you feel about me''

### ISSUE THREAD

**Issue by MasterTengu44** [Just-Natsuki-Team/NatsukiModDev#344]
# Overview:
hello, i would like to ask, would it be possible to put more different dialogue depending on the affection in the option ''how do you feel about me''

## Must haves:
for example for every 0.5 point of gaining or losing Affection, a slightly diferent dialogue will be displayed.

## Is this feature request related to a problem? Please describe.
I'm mostly asking this because I don't really feel like I've progressed, and I know you want to make the progression more transparent. but I have to admit it's a bit frustrating to play blind on whether the relationship with Natsuki is progressing or not.

**Comment by Blizzardsev** [comment]
Hi @MasterTengu44, thanks for raising a suggestion with us.

As it stands, we have dialogue for every possible affinity level when it comes to the topic in question - we feel this is sufficient, as no matter where a player stands on the relationship level list, they are covered by dialogue from Natsuki specifically for that level of affection.

Given the above, and the effort that'd be required in adding extra dialogue for whatever increments is appropriate (10? 25? 50? etc.), I'm unfortunately not personally convinced this would be the best use of development/review time.

Thanks again for your suggestion!
