### ISSUE TITLE
Question: how long to at least reach the affection level to happy?

### ISSUE THREAD

**Issue by MasterTengu44** [Just-Natsuki-Team/NatsukiModDev#346]
hello ! I have to say before I start that I really hope I don't get on the team nerves by asking questions in the issues, 

if so I'm sorry. 

so my question is that, I've been playing the games for at least 4 months, I know that the affinity levels are unlocked after several months of playing the games and I know how to unlock them because I read these: 

https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#ways-to-gainlose-affinity , 

I would like to ask on average how long does it take in months to unlock affection for at minimum unlock Happy affinity level? thank you .                                                                                                     

sorry if there are some errors, English is not really my first language

**Comment by Blizzardsev** [comment]
Hi @MasterTengu44, thanks for raising a question with us.

A lot of this will depend on how you play the game. If visiting daily and ensuring the daily cap is hit each time, then I would expect to meet the Happy state within a month.

Players start at 25 affinity above the baseline for Neutral (0), with Happy only being at 100: players start off being able to gain 5 affinity per day (a cap that increases for each month spent with Natsuki). This would mean that getting the 75 affinity points necessary should take about three weeks.

If you wish to double check, you can ask Natsuki how she feels about you. If she remarks that you're fun to be with, you're at the Happy state. If she gets embarrassed, then you're above the Happy state. If she's neutral or angry, you are at Neutral or below.

I hope this answers your question!

**Comment by Blizzardsev** [comment]
Oh, I should also add - this also assumes of course that your save data/persistent hasn't been deleted and remade, as this will reset any progress you'd have made.

**Comment by MasterTengu44** [comment]
Thank you for answering, ! i have to admit that when i ask her the question she looks surprised at first but she stops being surprised afterwards and tells me that i'm alright, i can't tell if it's neutral or happy but i will just assuming it's neutral since I haven't unlocked the options specific to happy affection levels but I'm a bit confused, that I'm going to see her every day, I listen to all the conversations I ask her sometimes questions even though I've already asked them all, and I let the game turn on for a long time while I'm doing something else in parallel, is there something I'm doing wrong?

**Comment by Blizzardsev** [comment]
No, you aren't - progression is slower than we'd like in the current patch, but we will offer more ways to increase aff in upcoming updates.

I wouldn't worry if you're doing something wrong. Just check back from time to time and enjoy new content as/when it appears.

If you're in doubt, you can check the log to see affinity going up/down.
