### ISSUE TITLE
[ BUG REPORT ] - 

### ISSUE THREAD

**Issue by zirconzed** [Just-Natsuki-Team/NatsukiModDev#347]
# Overview:
Natsuki would get angry if I "took a screenshot without asking" after I asked her.

## Replication steps:
Bug doesn't trigger after I reached affectionate stage. Before I was at that stage, Natsuki would get upset if I took a screenshot even after asking. I tried when her dialogue box telling me I could was open and also after that dialogue box closed to the same result. Since it went away, I think it only triggers for lower affection stages or is somehow affection stage based.

## Additional information:
I run the game on Windows 10 if that matters?

**Comment by Blizzardsev** [comment]
Hi @zirconzed, thanks for raising a ticket with us.

As it stands, the screenshot feature has proven problematic for the team through the time it has been available, while we feel it also offers little in return to our users: therefore we plan to cut back on screenshots to a likely one-off reaction, and removing the permissions/consequences aspect altogether.

I wouldn't worry about it for now - we'll ensure the community is made aware of the changes when the relevant update is ready.
