### ISSUE TITLE
[ FEATURE REQUEST ] - Compliment outfits

### ISSUE THREAD

**Issue by zirconzed** [Just-Natsuki-Team/NatsukiModDev#348]
# Overview:
Complimenting Natsuki on her various outfits.

## Must haves:
I think it'd be very cute for you to be able to compliment Natsuki on her different outfits. It's a small detail of course, but I think it would be very nice to have. Under "I want to tell you something," having an option to say "I like how (x outfit) looks on you," or something.

## Could haves:
Possibly could apply to hairstyles as well, maybe influence what Natsuki wants to wear around the player? More affectionate Natsuki might be more likely to choose to wear something the player compliments?

## Is this feature request related to a problem? Please describe.
When I see someone with a cute outfit or other clothes I like, I tell them, and I think saying that to Natsuki could be immersive and have some nice dialogue attached.

**Comment by Blizzardsev** [comment]
Hi @zirconzed, thanks for raising a suggestion with us.

The good news is that this is something we have in the works! As part of the outfit overhaul we plan on introducing, players will have the ability to compliment Natsuki's sense of style via the compliments feature, and Natsuki will also vary her dialogue when asking about her hairstyle based on if she's rocking her usual twin-tails, or a different hairstyle.
