### ISSUE TITLE
Bug: Can't take screenshots

### ISSUE THREAD

**Issue by Elstorko** [Just-Natsuki-Team/NatsukiModDev#352]
Ok so I don't know why but I can't take a screenshot of Natsuki without losing affection, I ask Natsuki to take a picture but she says quote " I just said you could...... just take it soon" As soon as I hit the screenshot button she reacts like I did not ask her and I still lose affection from it.

**Comment by Blizzardsev** [comment]
Hi @Elstorko, thanks for raising a bug report with us.

The screenshot reaction functionality is going to be removed in an upcoming update, so this should no longer be a problem in the near future.
