### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki gets upset over too much talk

### ISSUE THREAD

**Issue by IndependantFlower** [Just-Natsuki-Team/NatsukiModDev#355]
# Overview:
I noticed that if you press the "talk" button, you can still press it when the menu is up. I though that maybe you could add some sort of dialogue of Natsuki being annoyed by it, or something else .
## Must haves:
Some dialogue for pressing the talk button so many times in a row

## Could haves:
More dialogue if you keep doing it, or different based on affection/affinity level

**Comment by Blizzardsev** [comment]
Hi @IndependantFlower, thanks for raising a suggestion with us.

We'd actually already spotted this! However, we treated it as a bug (as it wasn't intended behaviour) and this has since been fixed such that the player may not select the option to talk to Natsuki if they already are.
