### ISSUE TITLE
[ BUG REPORT ] - Error evaluating conditional on topic 'talk_i_love_you'

### ISSUE THREAD

**Issue by FanOfEveryone** [Just-Natsuki-Team/NatsukiModDev#356]
## Overview:
At higher levels of affinity (Enamoured), the log has a error where it displays:
 [ERROR]: Error evaluating conditional on topic 'talk_i_love_you'. 'StoreModule' object has no attribute 'get_affinity_state'

## Replication steps:
Once you get to a high enough level, the log in the 'log folder' will display the error message.
Edit: It appears in the log after pressing 'How do you feel about me?'
## Additional information:
Nothing else

**Comment by Blizzardsev** [comment]
Hi @FanOfEveryone, thanks for raising a bug report with us.

Could you please send a copy of the log, as well as your persistent if possible?

You can't attach it on this ticket, but you can send your persistent to us through our official email: fubuki@justnatsuki.club

**Comment by FanOfEveryone** [comment]
@Blizzardsev, I have sent a email with the Persistent and Log file.
Subject: 'Ticket: #356'
Thank you for taking your time to help.

**Comment by Blizzardsev** [comment]
Hi, please download the attached, and be sure to change the file type to `.rpy.` If you then paste it into your `/game` directory and run JN, the issue should be resolved.

[dropfix.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/9276840/dropfix.txt)

**Comment by FanOfEveryone** [comment]
@Blizzardsev, Thank you for your help, again.
After I ran the game, it did as it served. I was able to view the new option in the Talk menu.
I don't see any errors anywhere so I think it's working.
Thanks, again.
