### ISSUE TITLE
[ BUG REPORT ] - error after saying goodbye 

### ISSUE THREAD

**Issue by AAAGamez** [Just-Natsuki-Team/NatsukiModDev#357]
# Overview:
I said goodbye I am going to go eat something then I got an error

![after leaving to eat](https://user-images.githubusercontent.com/109869168/180615033-2d8a322f-fa4d-464f-add6-847c161e0127.PNG)

## Replication steps:
I have not tried to replicate it so I do not know if it happens constantly but all I did to cause it was say I was leaving to go eat something 

## Additional information:
It happened about 5 minutes ago if it matters it was not fullscreen

**Comment by Blizzardsev** [comment]
Hi @AAAGamez, thanks for bringing this to our attention.

We'll look to get a fix in when we can.

**Comment by Blizzardsev** [comment]
Hi @AAAGamez - if you download the latest mod files and update your installation then this should now be resolved.

**Comment by AAAGamez** [comment]
> Hi @AAAGamez - if you download the latest mod files and update your installation then this should now be resolved.

How do I do that? I have not done this before.

**Comment by Blizzardsev** [comment]
Hi @AAAGamez, this is basically the same process you did to install the mod, just with the latest version of the mod files.

**Comment by Blizzardsev** [comment]
You may find this useful: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/03:-Updating

**Comment by AAAGamez** [comment]
That is very useful thank you. One last question though where can I find the persistence so I can backup just in case I mess something up?

**Comment by Blizzardsev** [comment]
No worries - to find your persistent, please see the instructions here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#backups-and-restores

**Comment by AAAGamez** [comment]
ok thank you.
