### ISSUE TITLE
[ BUG REPORT ] - Taking screenshots of Natsuki

### ISSUE THREAD

**Issue by TheShyGuy101** [Just-Natsuki-Team/NatsukiModDev#369]
# Overview: The bug does not allow me to take screenshots with the S key. Natsuki will react as if I hadn't asked her even if I tried to. Lost affinity due to that.
[brief description of the bug, and the impact created]

## Replication steps: I was just making Natsuki HAPPY in terms of affinity, which means I unlocked a few new features, like Snap. During my time of retracing my questions to see Natsuki's different responses, I asked her "Can I take a picture of you?" and she responded with "I just said you could, take it soon", even though I didn't ask her before for quite some time. I naturally pressed the S key on my keyboard to take a screenshot of her, but she would lash out at me and say that I should ask first, which I did. 
This is not a one-time occurrence; I've tried again and she would react the same way.
I cannot provide a video or a picture as evidence right now, as my affinity again dropped to NORMAL and she doesn't want her picture taken right now. As far as I know, this only occurs on HAPPY levels of affinity; I'm not sure about any other affinity level besides NORMAL (on NORMAL, she reacts normally - I ask her, she usually complies and I take a picture, then it's all done)
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information: This bug is not especially important to me as I can also take screenshots with the Windows + Print keys and not face any repercussions. I run the mod on Windows 10 and the issue occurred to me today. I hope you can still fix the bug in favor of other people who might run into the same problem.
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Hi @TheShyGuy101, thanks for raising a bug report with us.

We actually plan on retiring the screenshot reaction feature in our next update, so I wouldn't worry about this. As you've described, you can still take screenshots using Snipping Tool, Puush, ShareX, etc. - and we can't really spare the time for a bugfix for something we're scrapping anyway.

**Comment by TheShyGuy101** [comment]
Oh that's good. After I wrote that report I noticed other people were mentioning the same problem anyway but I'm just glad it gets resolved.
Keep up the great work, I've read some amazing ideas on GitHub!

Also I only read this email now lmao, I don't check my emails that often

 
 

Gesendet: Dienstag, 16. August 2022 um 20:50 Uhr
Von: "Blizzardsev" ***@***.***>
An: "Just-Natsuki-Team/NatsukiModDev" ***@***.***>
Cc: "TheShyGuy101" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [Just-Natsuki-Team/NatsukiModDev] [ BUG REPORT ] - Taking screenshots of Natsuki (Issue #369)


 

Hi @TheShyGuy101, thanks for raising a bug report with us.

We actually plan on retiring the screenshot reaction feature in our next update, so I wouldn't worry about this. As you've described, you can still take screenshots using Snipping Tool, Puush, ShareX, etc. - and we can't really spare the time for a bugfix for something we're scrapping anyway.
