### ISSUE TITLE
Just a little question

### ISSUE THREAD

**Issue by MonikaEndDie** [Just-Natsuki-Team/NatsukiModDev#37]
Hi guys! To started, it's nice to see you're still working on this mod to make it better and i wish the best for you and it.

So, since the other Dokie's mods (Monika after story, just Yuri and forever and ever) got a "i love you" button, why not having one here too, so we can express our love for Natsuki? Of course, if needed, it can a affinity/trust prerequisite and differents responses depending of their level.

**Comment by Blizzardsev** [comment]
Hello!

Don't worry - this is definitely on our radar, but we'll get an issue drafted up so we have it on record.

Thank you for bringing this to us!
