### ISSUE TITLE
[ ART REQUEST ] - Table variations for affinity

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#374]
# Context:
Currently, Natsuki's table remains completely plain besides props, which only show up on events.

In keeping with her interest in crafts and cutesy imagery, we could introduce variations of Natsuki's desk to reflect how she feels more comfortable expressing herself as she grows closer to the player.

As an example:
- AFFECTIONATE+ affinity: One or two small star stickers on her desk, kawaii/chibi animals, etc.
- ENAMORED+ affinity: Above, plus small heart stickers or similar
- LOVE+ affinity: Above, more prominent heart stickers

This would also serve as a more obvious visual indicator as to how Natsuki feels about the player!

## Assets needed:
A desk variant for each of the higher affinity levels would be needed, covering AFFECTIONATE, ENAMORED AND LOVED - the stickers should vary between each of these levels, with more stickers and greater prominence of romantic designs such as hearts as the affinity increases.

## Caveats:
Sticker placement shouldn't vary between levels - that way we can make it look like a progression!

Remember that the desk shouldn't feel cramped as a result of the stickers, and no stickers should be placed where Natsuki's arms/hands might be for poses (as otherwise due to rendering orders, the stickers would appear over her body!).

## Notes:
As Natsuki won't feel like arts and crafts at lower affinities, table variants will **not** be needed for HAPPY and below.

**Comment by Blizzardsev** [comment]
![image](https://user-images.githubusercontent.com/57731669/185512119-4c43c8fe-2e2b-4411-bfd7-0e9071514df3.png)

Potential inspiration for chibi animal stickers

**Comment by RaionArt** [comment]
![image](https://user-images.githubusercontent.com/112613077/188329344-c184f78d-9c1f-4b0f-808a-3a269b9a79a7.png)

One of the six new added variation of desks!

**Comment by Blizzardsev** [comment]
Great work! Well done!

**Comment by RaionArt** [comment]
![image](https://user-images.githubusercontent.com/112613077/188329419-58fc54d0-679c-4402-bac7-8e549340049c.png)
Also you have to treat her nice or else..
