### ISSUE TITLE
[ BUG REPORT ] - log.txt has an error with i_love_you

### ISSUE THREAD

**Issue by BrandiBlitz** [Just-Natsuki-Team/NatsukiModDev#378]
I  launched NAS mod and I'm getting this error in my log.txt file. it saying an error with one of its functionalities of some sort.

[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/9402801/log.txt)

**Comment by BrandiBlitz** [comment]
screenshot
![natsu affinity](https://user-images.githubusercontent.com/101225938/186171873-18d2056f-9ec3-4154-9571-a2b601b40fd0.png)

**Comment by BrandiBlitz** [comment]
> This should be resolved with the dropfix issued under #356

I'm at affection 7.5 and been with natsuki since march. Natsuki doesn't accept the confession

**Comment by Blizzardsev** [comment]
Hi @BrandiBlitz - please refer to your own ticket [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/396), and my explanation.
