### ISSUE TITLE
[ FEATURE REQUEST ] - Local weather affecting gameplay

### ISSUE THREAD

**Issue by spaghetsie** [Just-Natsuki-Team/NatsukiModDev#38]
# Overview:
Build a system capable of returning user-readable and easy to filter data containing information about your local weather conditions. This can then be used to change backgrounds, lock locations or have Natsuki comment on it.

## Must haves:

- Function to proccess data from an API call
- A way to limit API calls to every once in a few minutes

## Could haves:

- Add a must_be_weather parameter to `Topic` object
- Add a must_not_be_weather parameter to `Topic`
- Update stuff like background on every API call

## Is this feature request related to a problem? Please describe.
This is a new feature

**Comment by Blizzardsev** [comment]
So in terms of implementation, what did you have in mind?

Something like screenshots for weather-related functionality, (I.E `get_current_weather`) as well as hosting fallback dialogue for scenarios like API downtime, incorrect setup, etc.?

**Comment by spaghetsie** [comment]
I was thinking more of building just the back-end side of things. If possible I would like to avoid as much dialogue writing as possible as I'm not very confident in that aspect.

That being said, I do plan on adding *some* dialogue for stuff like downtimes, wrong player input etc.
But for something like a topic bundle related to weather, I think it would be better for someone else to pick that up

**Comment by Blizzardsev** [comment]
Will be introduced in #270
