### ISSUE TITLE
Making the text bigger so it's easier to read

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#381]
# Overview:
Right now the text ingame is very slim which makes it sometimes hard to read what Natsuki is saying. Especially when playing in windows mode or on smaller monitor the problem is more present. This also correlates with the fact that the cat pattern is a bit attention grabbing, though I don't think the real issue lies there.

## Must haves:
I would suggest to adjust the text by making it bigger or to enhance the white of the letters.

## Could haves:
Maybe a slider in the option could help to customize the text to the player's needs. 

## Is this feature request related to a problem? Please describe.
The problem is the text with a possible feature if a slider is implented.

**Comment by Blizzardsev** [comment]
I agree - making the text more legible would also help when it comes to promotional screenshots, like we post on Twitter.

Is this an issue anywhere else, alongside the textbook? For example, menus, the settings, etc?

**Comment by RaionArt** [comment]
I think it would be more beneficial when every text would be adjusted, simply to keep the consistency. 
But the textbox is clearly the main issue.

**Comment by Blizzardsev** [comment]
Cool! I can take a look at this today

**Comment by Blizzardsev** [comment]
![image](https://user-images.githubusercontent.com/57731669/188216813-1462f1cc-5cc4-474a-8c65-fd3b36c8c3ed.png)

![image](https://user-images.githubusercontent.com/57731669/188216822-feff407a-1a85-4eb6-b188-cfae3be97524.png)

Here's a comparison!
