### ISSUE TITLE
Exiting the menu with esc

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#385]
# Overview:
Almost every game closes menus with pressing escape. Regular players will most likely have the muscle memory to press esc when they want to leave a menu/conversation, which can also makes the game experience a more pleasant one.
## Must haves:
Return to the previous screen by pressing esc instead of clicking "Nevermind."

## Is this feature request related to a problem? Please describe.
It's a feature.

**Comment by multimokia** [comment]
One issue with this is that it may cause inconsistent behaviour with menus, as during idle, esc would open the main settings/history menu, whereas when you open the talk menu, it serves as a back-out mechanic which may lead to an unintended back-out.

Another thing to discuss is the immersion factor, as the reason for using a "Nevermind" button is that it serves as a form of 'verbal communication' between Natsuki and the player.

Perhaps it might be best to discuss our lines on UI/UX as it pertains to JN, as the layer itself heavily reflects the method of communication, if you will

**Comment by Blizzardsev** [comment]
I think I'd agree with @multimokia here - something else to bear in mind is that our players by now will also be accustomed to using Escape to quickly access the settings at any point; suddenly having this change to back out of menus might be jarring!

Was convenience during development a factor? If so, we could look at adding some dev-specific code to allow this for us, for ease of testing things.

**Comment by RaionArt** [comment]
Thank you for your replies! Tbh I somehow didn't notice, that esc opens the settings right now! Also the communication is a valid point I didn't think about.
