### ISSUE TITLE
[ ART REQUEST ] - Refresh older outfits

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#387]
# Context:
With all the extra polish coming in for the new update, we should make sure we're taking all artwork into account: including outfits!

With the massive range of clothing we have now, made over a large stretch of time, it's likely some outfits could use a rework or replacement to help keep things looking sharp, and to reflect our personal improvements as a team!

We should identify individual outfits we'd like to consider for updating/replacing, and list them here for discussion/future work. If needed, we can create issues later for outfits we'd want to work on.

## Assets needed:
See above

## Caveats:
Remember that as with all outfit changes, we keep in mind the possibility of adding new poses later.

## Notes:
N/A

**Comment by RaionArt** [comment]
I agree. Comparing different outfits, it is easy to notice how some outfits are created after gaining more experience in designing!

As an example the white from the "hoodie over turtleneck" is too bright and more details like shorter sleeved to show more of the turtleneck could be added.
![white and purple](https://user-images.githubusercontent.com/112613077/188953653-3a52444b-1d0c-4090-94df-7910cd5ab20c.png)

Other outfits would benefit from a color adjustment. The "heart sweater" as an example is too saturated and would be easier to the eye with a warmer pink.
![Shirt](https://user-images.githubusercontent.com/112613077/188954167-7c9174f8-82ed-46bb-8896-566e8d5d2bdc.png)

**Comment by Blizzardsev** [comment]
Yes, I can see what you mean with the turtleneck: if we compare it with some of the later outfits, like this:

![sitting](https://user-images.githubusercontent.com/57731669/188959889-01228ae2-dadd-4502-a378-978953814472.png)

We can see the difference in the softness of the colours and shading: we could also take the opportunity to add some more styling cues, a bit like Natsuki's skater outfit having writing, etc.

@kkrosie123 - did you have any thoughts?
