### ISSUE TITLE
[ BUG REPORT ] - Game crashes after specific goodbye dialogue 

### ISSUE THREAD

**Issue by EmeraldTheDingo** [Just-Natsuki-Team/NatsukiModDev#393]
# Overview:
[brief description of the bug, and the impact created]
I noticed that after picking the "I'm going to go eat something" option in the goodbye menu at a specific time of day instead of closing normally the game crashed and gave some sort of error. Although no progress/memory seems to have been affected by the crash.
## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]
after loading up the game, pick the "I'm going to go eat something" option at around 12PM to 12:30PM (where ever the time is for Natsuki to comment on you getting lunch) and after/midway through the dialogue the game should crash.
## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]
Just make sure the time is around noon or a while after as this bug doesn't seem to occur when she's not commenting on you having lunch.

**Comment by Blizzardsev** [comment]
Hi @EmeraldTheDingo, thanks for raising a bug report with us.

This will probably be similar to an issue we had with #326 ; I'll look at getting a dropfix sorted for you.

**Comment by Blizzardsev** [comment]
Okay! It looks like the fix described [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/317#issuecomment-1146865604) should work; can you follow the instructions and let me know how you get on?

**Comment by Blizzardsev** [comment]
Ah, sorry, ignore me - I had a different system in mind. Can you please instead try updating your installation? The latest available mod files shouldn't have this issue.

**Comment by EmeraldTheDingo** [comment]
Yeah I can do that, thanks for looking at the issue though, I'll close it after this then.
