### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki plays video games sometimes/Gaming introduction

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#394]
# Overview:
Natsuki already has topics about gaming and states she likes to play video games too. We should reflect that by her playing on an off brand switch sometimes!

## Must haves:
-sprites of her holding the switch (or Mimtendo Twitch)
-an introduction of the topic (such as: Natsuki losing a game)
-random encounter of her playing

## Could haves:
Maybe slightly different sprites to create a movement/animation like she is pressing buttons, when the game gets intense!

## Is this feature request related to a problem? Please describe.
It's a feature

**Comment by Blizzardsev** [comment]
I love this idea! I'd definitely be up to write an introduction or two for her playing her Wintendo Twitch!

What we could look at doing is making a couple of different introductions for variety; for example:
- An introduction where she's playing, only to lose shortly after the player enters from the console losing power (perhaps the console could have a low battery "emote" pop up, like the picture below?)
- An introduction where she's playing, only to jump when the player enters, causing her to lose her game - if the player has already seen the introduction where the console loses power, we could even have the console plugged in this time! (As if she's learned from earlier)

Artwork-wise, I think we'd do this like the books: so we have a pair of hands and console as a separate sprite from Natsuki herself.

**Comment by Blizzardsev** [comment]
![image](https://user-images.githubusercontent.com/57731669/189525371-3c3359ad-c73e-4c45-8c8d-090b320b41fa.png)

As an example for the pop up! We'd want to adjust the colours and shapes, as well as add a low battery icon if we decide to go with the battery dying idea
