### ISSUE TITLE
Natsuki sprites having crossed arms[ ART REQUEST ] - 

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#401]
# Context:
Natsuki's crossed arms is one of her most iconic poses, but sadly it isn't in the mod yet. I feel like adding the option to have Natsuki crossed arms could help to make her feel more livelier in conversations, especially when she is annoyed by something.

## Assets needed:
To make this happening every outfit (with sleeves) would need a fitting sprite.

## Caveats:
Codingwise it would be important that the right sleeves matches the current outfit.

## Notes:
[Any additional information]

**Comment by Blizzardsev** [comment]
Oh - we would also need to update the previewer, but this is straightforward also since it behaves very similarly to the sprite system. I'd be happy to do that also.

**Comment by RaionArt** [comment]
Oh, I think we have two ways to approach this idea!

One possibility would be to redraw the whole pose like in the original
![image](https://user-images.githubusercontent.com/112613077/191332995-dd87d924-8d67-4d0b-96b9-3f97af05b6fe.png)

But I was actually thinking about keeping the frontal view and to add arms!
![image](https://user-images.githubusercontent.com/112613077/191333145-538c0533-c29f-425e-bb9f-964ea75e33d0.png)

**Comment by Blizzardsev** [comment]
Okay - so I think the second pose is the obvious choice here: as her body (and head) would be facing the player, it'd minimise the amount of editing to look at (as we can recycle torso parts of the clothing assets): which is important when we have so many clothes.

In comparison, if we did the first, we'd have to:
- Redraw every outfit, as her body is now facing a new direction - we can't adapt what we have
- If her face wasn't still facing forward, we'd be looking at redrawing anything Natsuki can be customized with - hair, necklaces, headgear, as well as things like her eyes. Also, we'd have to worry about things like the sprite system picking the right eyes, mouths, noses... (also meaning a lot more testing)

Plus of course, all the time saved by going with the first approach can instead be put to better use elsewhere!

**Comment by RaionArt** [comment]
Glad we agree! This was exactly what I was thinking, but I wanted to underline that I had the second pose in mind.

**Comment by Booplicate** [comment]
I also agree, I think there's not enough benefits to go the first approach, but amount of work would be tremendous. And generally I think the frontal view works better.

Will we be able to update all the outfits that would require the change to support the new pose?

**Comment by RaionArt** [comment]
I think the biggest problem would be the outfits with pattern, because I don't have the pattern seperate. 
But this is also not an impossible obstacle to pass! 

Other than that I still have enough free time and motivation for this week to tackle this project!

**Comment by RaionArt** [comment]
Possible version:
![BaseBodyfront2](https://user-images.githubusercontent.com/112613077/204137962-5a2b6e77-9bc6-4066-97e7-e7a84df3a3d9.png)

**Comment by Blizzardsev** [comment]
Work for this has commenced under #463

**Comment by Blizzardsev** [comment]
Will be added in next update
