### ISSUE TITLE
[ ART REQUEST ] - natsuki head with ears

### ISSUE THREAD

**Issue by mayday-mayjay** [Just-Natsuki-Team/NatsukiModDev#402]
# Context:
i made a head replacement for natsuki to have ears in the jn style, based off act 3 monika + other after story related mods 

useful for hairstyles that dont cover up that general area of her face, also gives a spot for earrings though it wasnt my original main concern/focus

## Assets needed:
just this to replace the current head - 
![head](https://user-images.githubusercontent.com/89736832/191390745-2a0cb374-20ac-4f5c-ab0e-360e80cccb6f.png)

## Notes:
[Any additional information]
i apologize for any error, i do not use github often, i hope this helps though

**Comment by RaionArt** [comment]
Hello and thank you for your suggestion!

I tried your head out with our current hair styles and while most of them hide the ears, I think the ones, which show them seem to benefit from it! 
I guess in the beginning of the mod only Natsuki's default hair was planned, that would explain why the current head has no ears too.

Personally I would like to exchange the head, but we would need to see what the other members have to say and if they notice possible problems!

**Comment by RaionArt** [comment]
I'm happy to inform you your head will be part of the next update/full release!
