### ISSUE TITLE
Natsuki affection stuck at 7.5

### ISSUE THREAD

**Issue by Drago288** [Just-Natsuki-Team/NatsukiModDev#403]
I noticed that my affection didn't moved from 7.5 for over two weeks now.Anyone else got same problem?

**Comment by Blizzardsev** [comment]
Hi @Drago288 - this is intentional behaviour. Please see our explanation here: https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/396#issuecomment-1245848057

**Comment by Drago288** [comment]
> Hi @Drago288 - this is intentional behaviour. Please see our explanation here: [#396 (comment)](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/396#issuecomment-1245848057)

ah i see thank you for letting me know.
