### ISSUE TITLE
[ BUG REPORT ] - Textbox is seen in settings

### ISSUE THREAD

**Issue by nekoyourfriend** [Just-Natsuki-Team/NatsukiModDev#404]
# Overview:
When I click esc, and then click the x, textbox is seen in settings. Natsuki ask you if youre going to close the game. Then, if you click return, the options of "nevermind", "..." will show up.

## Replication steps:
-Go to DDLC´S settings menu
-Close the game on Natsuki
-The bug should be there
## Additional information:
I use a Windows 10. Date is 22-9-2022, 11-12 pm

**Comment by Blizzardsev** [comment]
Hi @nekoyourfriend, thanks for raising a ticket with us.

I've built a fix for this; it'll be in the next update.
