### ISSUE TITLE
[ FEATURE REQUEST ] - Introductions for the refreshed outfits

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#412]
# Overview:
After having all outfits refreshed in #387 it is time to talk about how to introduce them!
A few outfits like the pyjama and casual outfit are unlocked in the beginning, but other outfits like the "Qeeb" hoodie have no way to be unlocked at this moment.
We would need to decide which outfits we want to be giftable and which outfits will be unlocked after a certain conversation.

## Must haves:
-introductions to unlock specific outfit set 
-->example: Skater topic unlocks "black_beanie","not_cute_hoodie" and "black_choker"

## Could haves:
could be combined with the added gift option #372 

## Is this feature request related to a problem? Please describe.
feature

**Comment by Blizzardsev** [comment]
I completely agree - with so many outfits coming in, it seems a waste not to introduce a few by either editing existing topics where they fit, or adding a couple new ones!

The only thing I would say - for an outfit to be presented to Natsuki as a gift using the current system, it would have to be introduced as an "optional extra" - so we would remove it from the mod, and offer it as a separate download (like a user would do if they were making their own pack). But there's also nothing wrong with leaving some outfits locked in code, to be unlocked at a later date!

**Comment by Blizzardsev** [comment]
The outfits mentioned have been introduced in v1.0.2; remaining outfits are more seasonal so will have plans for those closer to the time.
