### ISSUE TITLE
[ ART REQUEST ] - Old music player for custom/random music unlock

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#415]
# Context:
Currently, custom music is unlocked in a topic, during which Natsuki finds a music player in her desk. However, we never actually see it on screen!

Now that we're moving towards having more and more props represented, it'd be great to have her music player given some illustrations that we can use both when the topic is unlocked, and when the music changes through dialogue with Natsuki!

## Assets needed:
- A music player, that must be centred in the middle of the desk in front of Natsuki

## Caveats:
- Natsuki specifically notes that the music player is old, so we should try to make the asset resemble an older device - like a CD-based music player! A cassette player would be much too old, and an MP3/MP4 player wouldn't be as interactive - so a CD player seems like a good middle ground!
- The music player does not belong to Natsuki, or any of the other girls - so we have free reign here as far as design goes! It could be brand new, or slightly beaten up: whatever is fitting!
- If desired, we could go a step further and have a few different variants to match the stages of music being changed: a version with the player with its lid closed, a version with it open (without a CD), and a version with it open (with a CD): this would make the dialogue way more interactive and dynamic!

## Notes:
N/A

**Comment by Blizzardsev** [comment]
@Nemu-sus @RaionArt thoughts?

**Comment by RaionArt** [comment]
I made a sketch for a possible audio player. Changes are of course possible!

![Audio_Player](https://user-images.githubusercontent.com/112613077/205455176-1ac01f4e-e11e-4c09-a83f-fabfdd7bc0c1.png)

**Comment by Blizzardsev** [comment]
I like it so far! It looks just like what I'd expect an old classroom music player to look like - the only challenge I can think of that this presents, is that we currently have the event written that the music player is small enough to fit in a desk drawer. If we went with this design, we'd need to modify the custom music unlock topic and random music change topic to reflect this.

Otherwise, I think change-wise it could do with some more wear and tear - if it's been sitting around the classroom for a long time, then some markings like the glasses case would suit it really well!

As a question - would it be possible to have three variants of the player? As it has an LCD display, it would make sense for it to have an "Off" state with a blank LCD (for when she first finds it), the "Play" state (which we have here), and a "Stop" state (for when she changes the music - this could have the lid open too).

Thanks for your work so far!

**Comment by RaionArt** [comment]
Multiple versions of art props are done, here are two examples:
![Music_Player_Off](https://user-images.githubusercontent.com/112613077/207146619-16ab703a-8c17-42cb-84e4-172231279daa.png)
![Music_Player_Play](https://user-images.githubusercontent.com/112613077/207146624-cda2b8ee-ac03-43c4-807d-dc55dcc09323.png)

Now only adjusting the dialogue and adding the assets is left!
