### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki's afraid of lightning!

### ISSUE THREAD

**Issue by Trainerbluetube** [Just-Natsuki-Team/NatsukiModDev#42]
# Overview:
In addition to the weather system in development, I think it would be fitting for Natsuki to be scared of lightning, but especially thunder.

## Must haves:
-Natsuki will change expressions for half a second when thunder occurs in-game, either a shudder or an outright terrified expression that would quickly change back to either neutral or mildly irritated and blushing.
-Natsuki will have a "fears" topic that links to this, one where the player can ask about Natsuki's fears
     *At high Trust she will be open about her fear of thunder
     *At high Affinity and Trust, she will tell the player that them being there makes her less afraid and thank them.
     *At high Affinity and Trust, she will express fear over the player suddenly disappearing, describing both injury or other causes.

## Could haves:
-The player could possibly hold Natsuki during thunderstorms, she would still talk unlike MAS but her sprite would be much closer and the table she's behind would move behind her sprite.
-Natsuki's 'fears' topic could be expanded to other fears, will need a meeting to come to a consensus on what those would be.

**Comment by ZachmanAwesomeness** [comment]
Sounds like a cool feature. I might give this a go.

**Comment by ZachmanAwesomeness** [comment]
I'm ready to try and see how I fare on that electric feature.
