### ISSUE TITLE
[ ART REQUEST ] - Glasses case for new intro

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#420]
# Context:
As part of the work to introduce glasses, a new introduction is being made which has Natsuki surprise the player with her specs!

While work on this is going ahead as planned, a nice finishing touch would be for Natsuki's glasses to have a case we can see on the desk!

## Assets needed:
- A glasses case, that sits on the middle of the desk in front of Natsuki. We only really need one, but if the artist is feeling extra motivated then they could try making an open and closed version!

## Caveats:
- The glasses Natsuki wears for the introduction are quite large rounded glasses: so we should aim to make sure they at least look like they could fit!
- In keeping with Natsuki's thriftiness, the glasses case shouldn't have some kind of premium branded look: but it would be totally in character for the case to be a little worn, and/or have some stickers (or maybe Natsuki's name scrawled on it!).

## Notes:
N/A

**Comment by RaionArt** [comment]
Done and uploaded to gdrive![image](https://user-images.githubusercontent.com/112613077/194753308-4159902e-5c9c-4d53-b28b-d6c32c00e54b.png)
