### ISSUE TITLE
[ FEATURE REQUEST ] - Suggest a temporary outfit

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#421]
# Overview:
At the moment it is only possible to change Natsuki's outfit when the player saves it too. My request is the possibility of choosing an outfit without saving. Natsuki would also be able to change her clothes again, so it feels more natural and less like she is a dress up doll.

## Must haves:
either a new option for "temporary outfit" or the possibility to leave the outfit selection without saving. (There would still be an overall quit option)

## Is this feature request related to a problem? Please describe.
It's a new feature.

**Comment by Blizzardsev** [comment]
This is doable. Only thing to think about would be how to handle the outfit name on quitting - but we can probably just set this to be random based on affinity or something
