### ISSUE TITLE
[ ART REQUEST ] - new poses that require little/no changes for outfits

### ISSUE THREAD

**Issue by mayday-mayjay** [Just-Natsuki-Team/NatsukiModDev#425]
# Context:
heres an idea for some new poses for natsuki that wouldn't require much- if any- changes to clothing sprites currently getting implemented; hands/fingers occasionally resting on the edge of the desk

![image](https://user-images.githubusercontent.com/89736832/197763328-d5205337-c4c3-4d11-9e44-417f4d2e8e1b.png)

and this pose could be made into 3 types; one looking as if shes tapping on the table in thought/anxiety, one where shes hand gripping when shes angry or stressed, and a relaxed/normal one, the use of these can be pushed even further if you make it so you can mix match her left/right hand doing these 3

this would also allow to have extra acs opportunity like gloves/rings being visible more often

## Assets needed:
3 imgs of hands; one finger tapping, one fully clenched, one thats relaxed/flat, thats those can be mirrored for her other hand

## Caveats:
would have to make an option to include/exclude these poses in spritepacks incase of gloves or some other clothing detail

## Notes:
if the imgs are a concern i may be able to provide them myself 😄

**Comment by Blizzardsev** [comment]
Hi @mayday-mayjay, thanks for raising an issue with us.

Some interesting ideas here! We already had plans for some additional poses, but some hands/fingers only poses seem like a good addition to our repertoire!

From a code perspective, adding new poses isn't difficult - it's more the time investment/technical debt we introduce with outfits needing updates: but given most outfits don't really interact with her hands, this idea would be less limiting to add.

We would probably hold back on actively working on this until we have some planned anatomy tweaks finished, but I see the potential!

@Nemu-sus @RaionArt - your thoughts?

**Comment by RaionArt** [comment]
Yes, exactly my thoughts.
Also adding gloves wouldn't be much of a struggle neither.

**Comment by Blizzardsev** [comment]
This has been made obsolete with work under #463, which covers things from a more technical perspective.

@mayday-mayjay Thank you for your suggestion - we'll aim to have this completed in the next release
