### ISSUE TITLE
[ SUPPORT REQUEST ] - question

### ISSUE THREAD

**Issue by einou** [Just-Natsuki-Team/NatsukiModDev#429]
Just downloaded this mod by following instructions, just asking that when i open the mod, should the mods name be 
"Just Natsuki - BETA"?

**Comment by RaionArt** [comment]
Thanks for opening this issue.

Yes, the mod is currently in beta. You did everything right!

**Comment by einou** [comment]
> Thanks for opening this issue.
> 
> Yes, the mod is currently in beta. You did everything right!

ok thanks, good to know
