### ISSUE TITLE
[ BUG REPORT ] - The advice Natsuki gives of drinking 6 to 8 glasses of water per day is slightly incorrect

### ISSUE THREAD

**Issue by RocketHog55** [Just-Natsuki-Team/NatsukiModDev#431]
# Overview:
Some of that 6 to 8 glasses of water will come from the food you eat, as well as other drinks like milk, juice, herbal teas, or even caffeinated drinks.

https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/water/art-20044256
"Is water the only option for staying hydrated?
No. You don't need to rely only on water to meet your fluid needs. What you eat also provides a significant portion. For example, many fruits and vegetables, such as watermelon and spinach, are almost 100% water by weight.

In addition, beverages such as milk, juice and herbal teas are composed mostly of water. Even caffeinated drinks — such as coffee and soda — can contribute to your daily water intake. But go easy on sugar-sweetened drinks. Regular soda, energy or sports drinks, and other sweet drinks usually contain a lot of added sugar, which may provide more calories than needed."

**Comment by RaionArt** [comment]
Hello and thank you for opening this issue with us.

While you are right, that water isn't execluded to just glasses of water, please bare in mind that Natsuki is/was just a regular student. It is quite possible that she sometimes states fact that are not backed up by scientific sources.
If you want you are free to discuss your opinion with other Natsuki enjoyer on our Discord community server in "jn-mod-discussion".

To round it up, this is not a bug and indeed intended.
I hope I could help you.
