### ISSUE TITLE
[ BUG REPORT ] - Game crashes when resizing game window

### ISSUE THREAD

**Issue by Xander5045** [Just-Natsuki-Team/NatsukiModDev#448]
# Overview:
The game crashed but nothing happen with natsuki

## Replication steps:
I changed the size of the window and crashed but is random because some times i change the size of the window and the game don't crash

## Additional information:
sorry for my bad english level :)

https://user-images.githubusercontent.com/118624585/202862062-d4e8bab7-d72f-472e-bc08-4bc212fa8a00.mp4

**Comment by Blizzardsev** [comment]
Hi @Xander5045 - I can see your example is a case where the game did not crash, and kept running.

Can you send me a copy of your `traceback.txt`, `errors.txt` and `log.txt` files in your JN installation?

**Comment by Xander5045** [comment]
> Hi @Xander5045 - I can see your example is a case where the game did not crash, and kept running.
> 
> Can you send me a copy of your `traceback.txt`, `errors.txt` and `log.txt` files in your JN installation, after experiencing the crash in question?

[log 1.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10073144/log.1.txt)
[log 2.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10073145/log.2.txt)
[read me.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10073146/read.me.txt)

**Comment by Blizzardsev** [comment]
Hi @Xander5045 - thanks for your patience.

I've had a brief look into this, and although the game slows down noticeably on resizing, it resumes functioning normally after a few moments for the game engine to catch up.

I'd imagine if anything, this would be down to either memory usage of Ren'Py, or Ren'Py's rendering engine acting up: neither of which is something we can offer a solution for at this time (at least not until we eventually upgrade the version of Ren'Py JN uses).

Given this issue hasn't been raised at all in the past, I'm closing this on the pretext that this is an extremely uncommon issue (that seemingly you have to _try_ to find), that is likely dependent on Ren'Py itself and not our own code.
