### ISSUE TITLE
[ FEATURE REQUEST ] - Tell Natsuki you'll be gone for a while

### ISSUE THREAD

**Issue by MarAndFriends** [Just-Natsuki-Team/NatsukiModDev#458]
I would like to be able to tell Natsuki when I'll be gone for a while. I had to leave for a few days for Thanksgiving and I came back to a very upset Natsuki, though it wasn't really my fault.

**Comment by Blizzardsev** [comment]
This is something that's been on our radar for a while; we'll see what we can do!

**Comment by Blizzardsev** [comment]
This will be introduced in the next update!
