### ISSUE TITLE
[ FEATURE REQUEST ] - Maybe tell Natsuki how long you’ll be gone. Like Monika from MAS: I’ll be gone for a couple of days, a week, a month, or awhile. Let Natsuki know and she won’t be disappointed without warning her.

### ISSUE THREAD

**Issue by ewSenpai** [Just-Natsuki-Team/NatsukiModDev#460]
[ FEATURE REQUEST] - Maybe tell Natsuki how long you’ll be gone. Like Monika from MAS: I’ll be gone for a couple of days, a week, a month, or awhile. Let Natsuki know and she won’t be disappointed without warning her.

**Comment by RaionArt** [comment]
Thank you for opening this issue with us ewSenpai! 
Someone already suggested the same idea only 7 hours before you (#458), so I will close this issue, but it's something we will discuss in the team, thank you!
