### ISSUE TITLE
[ FEATURE REQUEST ] - Sprite rework

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#463]
# Overview:
While we are planning to add new sprite poses like mentioned in #401 and #425 we would need to adjust the way our sprites work.
As an example at the moment the whole body sprite is hidden behind the table. We would want to seperate the arms from the bodies and have it layered in a different way, in which the hands/arms could be in front of the table.
So instead of going
- pose -> necklace/hair/face/etc -> pose.png

we could go
- Necklace -> NecklaceName -> pose.png

## Must haves:
- code adjustment
- splitting the body in different pieces
- adding a new file structure

## Could haves:
It is worth mentioning we need to be cautious about not overlapping possible event props with arm sprites!

## Is this feature request related to a problem? Please describe.
New feature!

**Comment by Blizzardsev** [comment]
[prospective_structure.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10108106/prospective_structure.txt)
