### ISSUE TITLE
[ FEATURE REQUEST ] - Offering Guest Dialogue

### ISSUE THREAD

**Issue by ZenithRev** [Just-Natsuki-Team/NatsukiModDev#467]
# Overview:
A player is offering to write a few dialogue topics for the Talk -> Let's Talk About... -> (etc.) section of the game, without asking to join the team.

## Must haves:
N/A; user is offering to do a little something for the mod that isn't massive in scope nor would it need them to be a team member.

## Could haves:
N/A; see above.

## Is this feature request related to a problem? Please describe.
Would the JN team be interested in a few dialogue segments that expand on ideas Natsuki has raised in other Let's Talk About topics? I've read the team's manual of style and can probably get the expression viewer installed if this offer is accepted; anything I send in could probably be copy-pasted in as-is or need only minor cleanup.

The major topic in my head is further exploring Natsuki's interest in roguelikes, which she mentions pretty early in the mod. I think there is some potential in showing why she likes this kind of game so much. My general take on it would be that she likes them because they really stretch her entertainment budget, since they're highly replayable. Natsuki wouldn't mention specific roguelikes (per the mod's manual of style), but would mention there are all sorts of roguelikes (action, card/deck-builder, traditional RPG, etc.). My guess is she admits she doesn't really care about the difference between a 'roguelike' and a 'roguelite'; perhaps something like "so long as a lot of the game is random each time you play, that's good enough for me!". 

It would be a mostly positive topic, with Natsuki giving roguelikes a big nod if the player is looking for a lot of fun for a fairly low price!

I'd be glad to do a few pieces like this for the mod, without joining as a main writer. I understand that anything I might send in _isn't_ guaranteed to be put in Just Natsuki, and may need some editing, but if you're interested in letting me try then I would be glad to send in a few topics for her to talk about.

**Comment by RaionArt** [comment]
Hello ZenithRev and thank you for opening an issue with us!
Everyone can raise an issue for topic or writing ideas, so feel free to give us your input in an issue fitting to the submission you wanna do. As an example we also included a head edit of a user not being part of the team too, so it is totally possible!
Of course we will give our inputs and review your ideas, when we find the time to spare. As you said yourself, it is possible it won't end in the mod, but we would notify you about it.
So yes, feel free to suggest in a fresh issue! But please keep in mind to include only one issue per topic/writing idea.

**Comment by ZenithRev** [comment]
Sounds good! I'll open a new issue for that later on and see what I can do. Going to close this issue as solved.
