### ISSUE TITLE
[ BUG REPORT ] - Possible Incorrect Idle Art in v1.0.1

### ISSUE THREAD

**Issue by ZenithRev** [Just-Natsuki-Team/NatsukiModDev#469]
# Overview:
User is confused as to whether they incorrectly installed 1.0.1 or are simply bad at reading Natsuki's facial expressions, due to the new Happy-or-higher emotion idle art not quite matching what I expected. Please see Addtl. Information for screenshots.

Impact: Minor - User is confused, but game appears to be working okay.

## Replication steps:
Steps taken:
User was playing 1.0.0, then closed it to install 1.0.1 per the recent release.
Backed up Auto-Save/Persistent to another storage device.
Installed 1.0.1. I believe I got the directory structure intact; was asked to overwrite approx. 1700 files (and overwrote all of them).
Started game.
Verified Natsuki is at least Happy or better; "I feel..." and playing Snap with her are available.
Watched Natsuki's idle animations.
MOST of Natsuki's Happy idles appear correct, but a few make me ask myself "Did I do something wrong? She looks upset."
User is confident they have done nothing to upset Natsuki; a "I feel... Excited" and a "Let's talk about... Weather -> What's your favorite season? (I agreed with her that Summer is best)" are all I've done at the time of this post.

## Additional information:
Playing on windows 10 home 64-bit. Attaching screenshots of the idles I'm unsure about.

<img width="1280" alt="idle0" src="https://user-images.githubusercontent.com/117028434/205399062-e5097058-5879-415d-9b8c-3d3caecaee3f.png">

![image](https://user-images.githubusercontent.com/117028434/205399237-9c3b0cb8-76e8-47ed-b45a-00de2afcff20.png)

![image](https://user-images.githubusercontent.com/117028434/205399099-7558ec3e-7a08-4c13-b6dd-fa0295e1773d.png)

**Comment by Blizzardsev** [comment]
Hi @ZenithRev - just taken a look at this.

Looks like you've found a couple of the new idles! In the ones you are highlighting, it is a sequence (one of two) where she looks pensive/in thought for a moment, before remembering she is being watched/seen and adjusts herself in a tiny bit of fluster: this might be hard to spot if the game is kept minimised and brought up occasionally - during which you might only see her in one "frame" of this animation set.

Can you keep the game up for a little while and see if this pattern matches what you are experiencing?

**Comment by ZenithRev** [comment]
Thanks for the quick reply! Am confirming **you are correct.** What I end up seeing if I take those steps is:
1 frame of Natsuki looking aside, then 1 frame of Natsuki looking down, then two somewhat different frames of her being flustered, then a fifth frame of her looking a bit embarrassed but still in a fairly good mood.

Closing this issue as **not a bug; user misunderstood a feature.**
