### ISSUE TITLE
[ BUG REPORT ] - i cant give headpats

### ISSUE THREAD

**Issue by explainfrank** [Just-Natsuki-Team/NatsukiModDev#470]
once again im not sure if this is a bug or if im doing something wrong but i cant give headpats
like, nothing works
i tried clicking, waving the mouse around her head and even all the keys in my keyboard, literally nothing works

that is all
thank you for continuing to make new content for this masterpiece of a mod

https://user-images.githubusercontent.com/107327380/205403035-3c6b8915-2289-4bc2-8c4c-86abd5d6e37b.mp4

**Comment by Blizzardsev** [comment]
Hi @explainfrank - thanks for raising an issue with us.

When giving Natsuki headpats, can you try keeping your cursor within her hair, and moving it in circles more slowly?

Also, what operating system are you using?

**Comment by Blizzardsev** [comment]
I should also note just in case - you must be in the headpats dialogue via _Extras_ for this to work at all, as you've demonstrated.

**Comment by explainfrank** [comment]
i accidentally closed it, sorry lol
 anyway to answer your question im using windows
i also tried that and it didnt work. does the operating system have anything to do with it?

**Comment by Blizzardsev** [comment]
Your `errors.txt`, `log.txt` and `traceback.txt` files in the base directory of your JN installation would also help!

**Comment by explainfrank** [comment]
yessir (i dont have errors.txt)
![lib](https://user-images.githubusercontent.com/107327380/205404761-edb58f30-4c99-48cd-adcc-865637f0198c.png)

[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10144929/log.txt)
[traceback.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10144931/traceback.txt)

**Comment by Blizzardsev** [comment]
Hi @explainfrank - several team members have attempted to reproduce your issue, and unfortunately we have been unable to replicate this behaviour - neither has this bug been reported by any other user.

Given this, and the lack of any game-breaking consequences, I will be closing this issue. I can suggest a reinstallation, but otherwise until this is more widely reported and reproduceable, there is not much we can do with this.
