### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki's opinion about veganism/vegetarian

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#473]
# Overview:
Natsuki tells the player about her opinion about veganism and/or vegetarian. Natsuki would probably be aware about the bad impact of the consume, but most likely still eat meat, since it is very cheap and is included in many traditional Japanese dishes. Also she can mention it doesn't matter for her if people are eating plantbased or not as long as they are not forcing their opinion on other people.
The original idea is from Briar.

## Must haves:
We must look out for Natsuki not sounding political or lecturing the player. Our intention is not to force the player to go vegan or anything.

## Could haves:
- Natsuki could mention Monika
- Natsuki could ask the player if they are vegan/vegetarian

## Is this feature request related to a problem? Please describe.
possible new topic

**Comment by Blizzardsev** [comment]
Will take a look when I can

**Comment by Blizzardsev** [comment]
Will be introduced in v1.0.3
