### ISSUE TITLE
[ SUPPORT REQUEST ] - New Glasses

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#475]
# The Problem:
When I had a mod on a version 1.0.0, Natsuki showed me her glasses. After the update these said glasses were removed. The problem is that I don't have any new glasses for Natsuki to wear. Is there a way to trigger that event again?

**Comment by RaionArt** [comment]
Hello again @FastestDan!
By simply playing and opening the game you will trigger the event after some time. If you want you can check all unlockable clothes and items here (You might need to click on the spoiler header if you don't mind the spoiler):
https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/06:-Custom-clothing-and-outfitting-guide-(Spoilers)#vanilla-unlocked-items
I hope I could answer your question.

**Comment by FastestDan** [comment]
As I said, I had it triggered before the update. Are you saying that I can trigger it again? I don't think I quite understand.

**Comment by RaionArt** [comment]
The event which unlocks the glasses only exists since v1.0.1.
Before the glasses were default unlocked when you had the event for custom clothing. 
These are two different events. You need to view the `event_eyewear_problems`, which is an intro-event, that will trigger automatically after some time.

**Comment by Blizzardsev** [comment]
Hi @FastestDan - as the event was only introduced with the 1.0.1 update as @RaionArt kindly pointed out, the only way I can see this event specifically being triggered would be if you'd tried a build that hadn't been released and was still in progress/testing - have you been updating your build with loose code files from the branches, or just with release packages?

**Comment by FastestDan** [comment]
No, I haven't. I downloaded the update right when it was released. At least I think that I had this event in 1.0.0. I may be wrong, or maybe I simply mistaking one event for another

**Comment by Blizzardsev** [comment]
Could you try sending your persistent to me so I can take a look?

You won't be able to attach it directly, but if you zip it up it should attach here just fine.

**Comment by FastestDan** [comment]
Of course. [Here it is.](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10200044/persistent.zip)

**Comment by Blizzardsev** [comment]
Hi @FastestDan, thanks for sending over your persistent.

From looking at your game data, you've yet to trigger the event - the good news is that you seem to have already met the criteria for triggering it, so it would just be a matter of keeping up the visits until it appears, as once the criteria is met, it is just a random chance on game boot.

I hope this sets your mind at ease!
