### ISSUE TITLE
[ BUG REPORT ] - Headpat mechanic not working?

### ISSUE THREAD

**Issue by EmeraldTheDingo** [Just-Natsuki-Team/NatsukiModDev#482]
# Overview:
I brought it up in the discord because I was confused since no matter what I tried it would never register after I selected the option. Even after repeating the steps given to me by the devs (drag/hover the mouse over her head without clicking) I still couldn't get the game to register the action. Leading me to believe this is a bug.

## Replication steps:
Try doing the intended steps on version 1.0.1. If I am correct it may not work.

## Additional information:
JN version was 1.0.1 when attempted.

**Comment by JADENLO** [comment]
https://user-images.githubusercontent.com/106132370/208338301-aef07f84-603a-4210-b2d2-ae3e1fea0fbd.mp4

it works just have to find the right spot

**Comment by EmeraldTheDingo** [comment]
Oh! I was trying to do it directly on top just below the counter. I feel dumb now lol thank you, sorry to waste your time.

**Comment by JADENLO** [comment]
its fine

**Comment by explainfrank** [comment]
> 2022-12-18.21-51-17.mp4 
> it works just have to find the right spot

i was having trouble with that too lol. thanks for the tip, friend
