### ISSUE TITLE
[ BUG REPORT ] - 

### ISSUE THREAD

**Issue by MyNameIsPeyton** [Just-Natsuki-Team/NatsukiModDev#484]
After downloading the JN update, I started getting this error upon launch;

![image](https://user-images.githubusercontent.com/92688371/208281780-5b586c74-b40e-4da3-bf55-7bf6ac3dc298.png)

**Comment by RaionArt** [comment]
Hello @MyNameIsPeyton and thank you for raising in issue with us!

The message in the end "Just Natsukui 0.0.2" indicates you didn't updated correctly.
Also it seems like you renamed the .exe. Please don't do that.

Back up your persistent(!), get a fresh copy of DDLC (not from steam) and follow really every step:
https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/03:-Updating

I hope I could help you.

**Comment by MyNameIsPeyton** [comment]
Everything seems to be working fine now. Thanks a bunch!

**Comment by RaionArt** [comment]
I'm glad I could help, enjoy the update!
