### ISSUE TITLE
[ BUG REPORT ] - No apology option when cheating in snap before 1.0.0 update, then updating to 1.0.0

### ISSUE THREAD

**Issue by OOFMaster467** [Just-Natsuki-Team/NatsukiModDev#489]
# Overview:
I'm very late to report this, but after cheating in snap and updating the game without apologizing, the apology option doesn't show up. I'm not sure if this happens with anything else someone would need to apologize for.

## Replication steps:
1. Play on an outdated version of JN, pre-1.0.0
2. Cheat in snap
3. Update to 1.0.0+
4. Apology option won't show up

![image_2022-12-20_011619064](https://user-images.githubusercontent.com/84692023/208606051-8345248e-3bee-4a56-8c7d-de0db446839e.png)

![image_2022-12-20_011438147](https://user-images.githubusercontent.com/84692023/208605789-828b2f38-388d-4c1a-bedf-b7ee0f6f109e.png)

## Additional information:
Operating System: Win 11

**Comment by Blizzardsev** [comment]
As this is quite a specific circumstance, I don't see the value in updating our migration code at this time to take this into consideration. However, I've attached a dropfix that should solve your issue and allow you to play Snap again:

[dropfix.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10282649/dropfix.zip)

Please unzip the archive, copy `dropfix.rpyc` into the `game` folder of your JN installation, run the game and let me know how you get on.

**Comment by OOFMaster467** [comment]
The fix works, thank you!
