### ISSUE TITLE
[ SUPPORT REQUEST ] - How to give Natsuki gifts?

### ISSUE THREAD

**Issue by disownxd** [Just-Natsuki-Team/NatsukiModDev#494]
# Overview:
I'm a little confused about the gift giving feature. Could someone please explain? Is there a list anywhere about the available gifts?

**Comment by Blizzardsev** [comment]
Hi @disownxd,

Currently, only outfits and wearables may be gifted by players to Natsuki. We do not yet have a setup like MAS for gifting, if that is what you had in mind.

Please see the following for gifting outfits/wearables to Natsuki: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/06:-Custom-clothing-and-outfitting-guide-(Spoilers)#adding-pre-made-custom-clothing
