### ISSUE TITLE
[ FEATURE REQUEST ] - gifting custom card packs for snap

### ISSUE THREAD

**Issue by mayday-mayjay** [Just-Natsuki-Team/NatsukiModDev#497]
# Overview:
just like the title says, i think it'd be very sweet being able to gift custom card packs and then pick between said packs for snap! bonus points if you can use these packs for other card games if theyre implemented later down the line

## Must haves:

- adding/gifting cards in a way similar to outfits(?)
- a selection screen that has someway to let you very quickly preview the card pack you're about to select
- being able to switch sets inbetween rounds of snap

## Could haves:
being able to tell natsuki 'you can pick the set we use!' and then she'll pick randomly

**Comment by Blizzardsev** [comment]
Hi @mayday-mayjay, thanks for raising a suggestion with us.

While I do like the idea, I'm not sure how practical this is at the current time. The outfit system was a lot of work, and right now the team's focus is on expansion of content such as topics, greetings, and mechanics that support those.

I think being realistic, this is a lot of investment to put into a single area of the mod - especially when we'd also like to branch out our range of games beyond cards at some stage.
