### ISSUE TITLE
[ BUG REPORT ] - JNActivities not defined

### ISSUE THREAD

**Issue by mayday-mayjay** [Just-Natsuki-Team/NatsukiModDev#498]
# Overview:
![image](https://user-images.githubusercontent.com/89736832/209506453-4aae21a3-8579-4aa4-9aa4-22d8c4edbc4a.png)

## Replication steps:
i honestly don't know, i just was sitting around waiting for topics to appear and then this screen occurred

## Additional information:
windows 10, just turned midnight so it's the day after christmas, and i'm at happy tier with natsuki

**Comment by Blizzardsev** [comment]
Hi @mayday-mayjay , thanks for raising a bug report with us.

I can see the cause of the error; this should be a straightforward fix.

We'll let you know when a hotfix has been made.

**Comment by Blizzardsev** [comment]
Hi @mayday-mayjay - if you download the latest release again and follow the same steps as you would to update, your issue should be resolved.
