### ISSUE TITLE
[ SUPPORT REQUEST ] - had a problem trying to update to 1.0.2

### ISSUE THREAD

**Issue by einou** [Just-Natsuki-Team/NatsukiModDev#506]
so, i tried to update my jn from 1.0.0 to 1.0.2. i followed the steps, and copied the persistent file to my desktop.
i downloaded the 1.0.2, unzipped it and copied the game, lib and update folders into my old jn folder. and when i opened the app, it was like i opened it for the first time. now, did i do something wrong? and where must i put the backup to resume where i left?

**Comment by Blizzardsev** [comment]
Hi @einou , can you please attach your latest log file?

**Comment by einou** [comment]
[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10310563/log.txt)

this is from the current jn, where the game begun again. took it from the "log" folder

**Comment by Blizzardsev** [comment]
I see. Can you please send me your backup persistent?

**Comment by einou** [comment]
Github doesnt support the file i have, i tried to convert it to .txt file, but it didnt work for some reason. i asked the websites staff support, and im waiting for an answer.
ill send the file, when i manage to convert it to a right format. Thank you for your patience

**Comment by Blizzardsev** [comment]
Hi @einou , all you need to do is make a new folder, copy your persistent into it, then zip the folder and attach it here.

Converting the file won't work.

**Comment by einou** [comment]
yeah, i didnt think of that. really simple. heres the folder
[persistent folder.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10310700/persistent.folder.zip)

**Comment by Blizzardsev** [comment]
Hi @einou , is this your current persistent? I would need the backup persistent if not.

**Comment by einou** [comment]
this is the one for the 1.0.0 version

**Comment by Blizzardsev** [comment]
Gotcha. Finally, can you send through your current persistent for me to evaluate?

**Comment by einou** [comment]
i found two persistent files, but i really think this is the current version. 
[persistent folder.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10310833/persistent.folder.zip)

**Comment by Blizzardsev** [comment]
And just to make sure: when you copied your persistent file to your desktop, did you make sure to actually place it back where you found it?

**Comment by Blizzardsev** [comment]
If you didn't do this, then JN assumes you have no save and makes a brand new one.

**Comment by einou** [comment]
well no, i found the persistent file from the appdata place, and i actually have no idea where the persistent file was, i just found it by searching from the appdata place

**Comment by Blizzardsev** [comment]
Then that would be your problem. You need to take your backup and place it into the AppData folder for Just Natsuki.

For reference, you can find it using the instructions here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent

Could you please copy your backup persistent over the one currently in AppData, then run the game and let me know how you get on?

**Comment by einou** [comment]
does this mean that i can now download a new jn and put the persistent there? cuz right now my just natsuki files are a big mess

**Comment by Blizzardsev** [comment]
Yes. I'd recommend a complete reinstallation of the mod if you aren't confident with your current setup.

**Comment by einou** [comment]
so i can delete all my old jn files? except of course the persistent

**Comment by Blizzardsev** [comment]
Yes, that should be fine.

**Comment by einou** [comment]
and one final question, just to be 100% sure: if i delete the "JustNatsuki" folders from appdata, that doesnt delete the persistent file in my desktop? might sound like a dumb question, but really just to be sure

**Comment by Blizzardsev** [comment]
You don't need to delete it. Just copy your persistent from your desktop into that folder, and replace it when prompted.

**Comment by einou** [comment]
it works! thank you so much for help, i was completely clueless how to get it working! so for now on, i just put the backup to the appdata place justnatsuki folder?

**Comment by Blizzardsev** [comment]
If you need to restore, then yes. Otherwise no worries, and enjoy your time with Nat. :)
