### ISSUE TITLE
[ SUPPORT REQUEST ] - Some kind of error after updating to 1.0.2

### ISSUE THREAD

**Issue by TheShyGuy101** [Just-Natsuki-Team/NatsukiModDev#511]
![Screenshot (45)](https://user-images.githubusercontent.com/111303458/210159851-b847a86c-ffca-49d0-8bc6-d907f2ebd2af.png)

## Additional information:
I just updated the game the way I always do, but for some reason it keeps showing me this. Not a one-time error, it keeps on happening.

**Comment by Blizzardsev** [comment]
Hi @TheShyGuy101, I can see from the log (and the window title) that you are updating from the Beta version of Just Natsuki; you need to follow the specific instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev#updating-from-the-beta-to-a-release-100-onwards) to update from the Beta to any release (v1.0.0 onwards).

Alternatively, you may wish to simply reinstall Just Natsuki: your save data will be fine in this instance.

**Comment by TheShyGuy101** [comment]
Damn, I'm really blind right now, sorry. That definitely worked now - Nat is throwing a party on New Year's Day lol
