### ISSUE TITLE
[ SUPPORT REQUEST ] - Lost save for no apparent reason 

### ISSUE THREAD

**Issue by trapsena** [Just-Natsuki-Team/NatsukiModDev#516]
I really don't have an explanation how i would lose all of my save file, the last time i played was at the new year, and the only thing i did was open two tabs by mistake, i played trough one for at least 40 minutes and had tought i achieved cap so i told natsuki i was goin to sleep on the first tab and re played the new year opening and said i was going to sleep for my second natsuki. a day passes and i arrive home and when i opened the game i noticed the disclaimer going trough the game, i alt f4 before even restoring natsuki and went straight to my save folder and saw that the persistent was only 10kb

sorry for this story but i have no idea what happend, also here's my log 
[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10333715/log.txt)

**Comment by Blizzardsev** [comment]
Hi @trapsena - have you tried looking in the Recycle Bin for your old persistent, or seeing if File History was turned on for the save directory?

Also, have you backed up your save data at all (for example, from before an update as we recommend)?

**Comment by trapsena** [comment]
> 

THE FILE HISTORY HAS MY SAVE FROM YESTERDAY ILL TRY TO SEE IF ITS GONNA WORK THANK YOU THANK YOU THANK YOU SO SOSO MUCH AAAAAAAAAAAAAAAAAAAAA

**Comment by trapsena** [comment]
> Hi @trapsena - have you tried looking in the Recycle Bin for your old persistent, or seeing if File History was turned on for the save directory (and then restoring it from there)?
> 
> Also, have you backed up your save data at all (for example, from before an update as we recommend)?

UPDATE:i got my persistent file from 01/01/2023 that has 142kb but when i tried opening the game it reverted this time the persistent file into a 9,85 kb file

**Comment by Blizzardsev** [comment]
Can you please copy your old persistent into a zip file and attach it here for us to examine?

**Comment by trapsena** [comment]
> Can you please copy your old persistent into a zip file and attach it here for us to examine?

[Trap's Persistant.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10333773/Trap.s.Persistant.zip)

**Comment by Blizzardsev** [comment]
Hi @trapsena - I've written some code personally to try and load your save data outside of Just Natsuki, and unfortunately it looks like that persistent is corrupt. I cannot load it, and neither can the game - so it resorts to creating a new save file.

The only things I can suggest at this point are to look back further in File History to find an uncorrupted persistent before that date, check to see if you have backups elsewhere, or worst case scenario restart the game from scratch.

**Comment by trapsena** [comment]
> Hi @trapsena - I've written some code personally to try and load your save data outside of Just Natsuki, and unfortunately it looks like that persistent is corrupt. I cannot load it, and neither can the game - so it resorts to creating a new save file.
> 
> The only things I can suggest at this point are to look back further in File History to find an uncorrupted persistent before that date, check to see if you have backups elsewhere, or worst case scenario restart the game from scratch.aight i got my savefile from 30/12 working, but is there a way to get the 2023 headgear besides chaging the internal pc time? because ive heard that cheating could make you lose afinity

**Comment by Blizzardsev** [comment]
Unfortunately no, not at this time. You would have to wait until the next event to unlock the headgear again.

We do not advise changing the system clock, as you are correct in that this carries consequences.
