### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki struggling to find fitting clothes

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#517]
# Overview:
While drawing sleeves for #463 I noticed some sleeves are really big, which lead to the idea of a topic for Natsuki!
Natsuki could complain about struggling to find fitting clothes as result of her petite body. With higher affinity it can be revelead, that she actually started to shop in the kid section, partly because they are cheaper, but also because they are simply smaller. Natsuki probably added her own style to this outfits by stitching, for example, to cover up the might childish design. We could even make the `pastel_goth_outfit` unlockable after viewing this topic.

## Must haves:
- dialogue for the topic
- unlocks the `pastel_goth_outfit`

## Could haves:
- more dialogue unveiled with higher affinity
- With the new face slot we could add the face glitter for the `pastel_goth_outfit`, which was previously missing

## Is this feature request related to a problem? Please describe.
feature!

**Comment by Blizzardsev** [comment]
Sure, this sounds like a fun topic with some potential to pull some heartstrings - the unlock method is welcome too!

**Comment by Blizzardsev** [comment]
This will be added in v1.1.2.
