### ISSUE TITLE
This happened to me.

### ISSUE THREAD

**Issue by SystemDeKilla69** [Just-Natsuki-Team/NatsukiModDev#519]
Sorry, I just installed the mod and followed the instructions, but unfortunately, I got this:
![proof](https://user-images.githubusercontent.com/84384138/210862776-7a3aaa5d-4f3a-44b1-9dcb-f201b56133b2.png)
Is there a way to fix it? I followed the download instructions, but I'm not able to start the game because of this error. This happened multiple times, in fact. I'm not sure if anyone else got this too...

**Comment by Blizzardsev** [comment]
Hi @SystemDeKilla69, thanks for raising an issue with us,

I can see the issue and I am writing a fix now. I will let you know when this has been completed.

As a heads up for future issues, could you please try to be descriptive with the issue title? Something more descriptive like "Crash after updating to 1.0.2" is much more helpful than "something happened"!

**Comment by Blizzardsev** [comment]
Hi @SystemDeKilla69 - can you please try downloading the latest release again, and install it? You may need to try a complete reinstall, but just try an update first.

**Comment by SystemDeKilla69** [comment]
> Hi @SystemDeKilla69 - can you please try downloading the latest release again, and install it? You may need to try a complete reinstall, but just try an update first.

Sorry, this happened to me multiple times, in fact. Everytime I try to download the mod, I get this error screen. I'm not sure if I did something wrong, because I followed the instructions. Probably 3 times...I tried to download the mod but unfortunately not. Stopping isn't an option, because I think the mod is beautiful, and I am trying to install it.

**Comment by Blizzardsev** [comment]
Could you please try the following steps:
- Completely remove any versions of JN you have downloaded in your Downloads folder
- Completely remove your JN installation (your save data will be fine)
- Follow the instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev#installation), step by step - the latest release has been patched, so should resolve the problem

**Comment by SystemDeKilla69** [comment]
> Could you please try the following steps:
> 
> * Completely remove any versions of JN you have downloaded in your Downloads folder
> * Completely remove your JN installation (your save data will be fine)
> * Follow the instructions [here](https://github.com/Just-Natsuki-Team/NatsukiModDev#installation), step by step - the latest release has been patched, so should resolve the problem

What I'm saying is that I never downloaded the mod before today. So...maybe downloading the patch will help! Thanks.

**Comment by SystemDeKilla69** [comment]
Thanks a lot! I love the mod.
