### ISSUE TITLE
[ SUPPORT REQUEST ] - Is it possible for me to know the exact number that represents Natsuki's affinity level?

### ISSUE THREAD

**Issue by wowm03** [Just-Natsuki-Team/NatsukiModDev#521]
# Overview:
As the title suggests, I'm not sure if there is a way for me to know about the exact level she is in now, I know about the affinity tiers, but I'm just wondering if I can learn about how much more I need to get to the next level.

**Comment by Nemu-sus** [comment]
This is intentional.

   There are some indications however to which she will express to the player that may give you an idea of how she feels about you, such as; by the way the desk appears or its condition, the way she talks or acts or by simply asking her how she feels about you.
