### ISSUE TITLE
Just natsuki Creepy Files 

### ISSUE THREAD

**Issue by IdkNatsukiluver** [Just-Natsuki-Team/NatsukiModDev#523]
# Overview: So I was looking through the JN game's files and uh...
[There were those creepy yet very interesting files, there's this file called youdidthis.png and the sound files where you can find the distressed sayori music and some reversed music and glitches audio as well!
Do these features activate when you are in the distressed mode/specific affection modes or are these coming in new updates or are they just cool easter eggs for those who like to dig into the files??

**Comment by Blizzardsev** [comment]
We'll leave that to your imagination. :-)
