### ISSUE TITLE
[ SUPPORT REQUEST ] - Uncaught Exception

### ISSUE THREAD

**Issue by rakashii** [Just-Natsuki-Team/NatsukiModDev#524]
# Overview:
Error message upon loading the game

## Additional information:
Windows 11
--I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-headpats.rpy", line 50, in <module>
AttributeError: 'StoreModule' object has no attribute 'registerExtrasOption'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:/Windows/system32/script-headpats.rpyc", line 3, in script
  File "C:\Users\------\Downloads\JNMod\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\------\Downloads\JNMod\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-headpats.rpy", line 50, in <module>
AttributeError: 'StoreModule' object has no attribute 'registerExtrasOption'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Just Natsuki 1.0.0

**Comment by RaionArt** [comment]
Hello @rakashii,
this error message implies your game isn't updated correctly to the newest version of the mod.
Please try to backup your persistent and follow the steps for [updating from release onwards](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/03:-Updatingl).

**Comment by Blizzardsev** [comment]
Hi @rakashii - this is an issue we've seen raised a few times before: as @RaionArt pointed out, this is due to an update not being completed correctly.

Under these grounds, I will be closing the issue - you'll be fine if you follow the steps.
