### ISSUE TITLE
[ FEATURE REQUEST ] - Gifting food from Food topics category 

### ISSUE THREAD

**Issue by wowm03** [Just-Natsuki-Team/NatsukiModDev#525]
# Overview:
i remember wanting to gift nat all the food she mentioned and said she was craving for them when I read the dialogues about food she likes, 'm wondering if those may be added in the future, similar to the topic where she talks about her favourite drinks.

**fizzy candies**
![image](https://user-images.githubusercontent.com/90627231/211200633-e13def49-4432-4f50-a6db-36f029acbfe0.png)

**white chocolate**
![image](https://user-images.githubusercontent.com/90627231/211200687-ae31726b-dad9-46d2-983a-69f31f479382.png)

**milk chocolate & dark chocolate** (may not raise affection because she doesn't prefer these as much?)
![image](https://user-images.githubusercontent.com/90627231/211200734-844801a8-0a26-47e7-adcc-aecf5eea4091.png)

## Must haves:
the food mentioned in the topics

## Could haves:
sharing food, where left/right clicks/other interactions can trigger that

**Comment by Blizzardsev** [comment]
This is a decent idea! I can see some fun reactions based on foodstuffs she's already mentioned, although sharing food isn't something I can see working given Natsuki already acknowledges she can't share things like the cake she makes on the player's birthday, or the Valentine's day chocolates.

Non-clothing gifts have been on the radar for a while now, and have already been raised as a request [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/252) - I'll make a note of this issue and close this as a duplicate.

Thank you!
