### ISSUE TITLE
[ FEATURE REQUEST ] - Reappearing books and consoles

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#527]
# Overview:
At the moment once the player has seen an intro about Natsuki reading a book or playing on the wintendo twitch, they are not able to revisit these moments and I think this is a shame! It would be great if there is a random chances which shows Natsuki keep reading or playing with items previously mentioned.

## Must haves:
- Need to figure out how we could keep the animation for her gaming concole while idleing
- special idling while she is reading/playing

## Could haves:
- the player needs to approach Natsuki in some way to get her attention

## Is this feature request related to a problem? Please describe.
It's a feature!

**Comment by Blizzardsev** [comment]
This will be added in 1.0.4.
