### ISSUE TITLE
[ BUG REPORT ] - Natsuki's Sprite missing while talking about Snap rules

### ISSUE THREAD

**Issue by trapsena** [Just-Natsuki-Team/NatsukiModDev#541]
I am not sure if its based on the topic or the outfit but when i asked her about rules of snap she suddenly dissapeared, a message later she was back but was gone again while gone there was also a red text at the bottom but it was unreadable due too it getting out of the screen

While i was asking her, Natsuki was wearing the Star Pajamas so it could have been that? 
![screenshot0344](https://user-images.githubusercontent.com/88294045/218641617-9e2dd78e-f8ea-4ee8-947c-6be7fb6db7f7.png)
![screenshot0346](https://user-images.githubusercontent.com/88294045/218641635-1067c81d-0a45-44e0-9ce7-642be272120f.png)

**Comment by Blizzardsev** [comment]
Hi @trapsena , thanks for raising a bug report with us. We'll look into it.

**Comment by Blizzardsev** [comment]
Okay - I've identified the cause for the bug; I will get a fix published when I have the time today.

**Comment by Blizzardsev** [comment]
Hi @trapsena - if you download the latest release again and follow the update steps, this will be resolved.
