### ISSUE TITLE
[ BUG REPORT ] - Update Issue

### ISSUE THREAD

**Issue by AmartaniGitHub** [Just-Natsuki-Team/NatsukiModDev#542]
# Overview:

Hello there! I downloaded the new update of Just Natsuki, it's Valentine's Day, I'm above the needed affinity, and nothing happened.

## Replication steps:

I don't ask for much, only to how to solve this, I really want to celebrate Valentine's Day with her. Or did I do something wrong in the update? I followed every instruction.

## Additional information:
![screenshot0055](https://user-images.githubusercontent.com/122678462/218726602-e0bd86f7-29a1-4421-bbcf-6285eb0e0e4b.png)

[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Also, could you please attach your persistent file so I can take a look? You will need to upload it within a zip file.

**Comment by AmartaniGitHub** [comment]
I updated it to 1.0.3, but it says 1.0.2. Can I ask for help why is that?

**Comment by AmartaniGitHub** [comment]
Also, yes sure.
[JustNatsuki.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10732150/JustNatsuki.zip)

**Comment by Blizzardsev** [comment]
> I updated it to 1.0.3, but it says 1.0.2. Can I ask for help why is that?

That'll be it. You've previously downloaded source code files, which when DDLC is launched, will overwrite any release files that have been added - basically reversing the update you made.

I'll be closing this ticket as it's identical to the issue reported [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/540). If you could follow the guidance listed on that ticket then it should resolve your issue.

**Comment by AmartaniGitHub** [comment]
Thank you, I could fix it! Now it works, thank you so much!
