### ISSUE TITLE
JN 1.0.3 Starts but nothing comes up.

### ISSUE THREAD

**Issue by ClapTrap125** [Just-Natsuki-Team/NatsukiModDev#544]
Download JN 1.0.3 and updated just as shown in the how to install/update section. However whenever i launch the game it just comes up with a black screen that says “A problem has occurre. please contact JN staff.”. The game itself runs (as evidenced by me being able to bring up the settings)

Thinking this was a possible issue with how i downloaded it, i went and downloaded the previous version with no issues.

If there are any further questions/ things i can provide to help. Pleass just let me know

![image](https://user-images.githubusercontent.com/125423967/218917151-0f6fec61-4bbd-42f6-b937-0ece17cfc0e8.jpg)
![image](https://user-images.githubusercontent.com/125423967/218917185-3deee48f-46bd-44b3-8958-f3e7a1a8fcc7.jpg)

![image](https://user-images.githubusercontent.com/125423967/218915881-d64066d7-bc5c-4b1c-aa95-32541e739d8a.jpg)
![image](https://user-images.githubusercontent.com/125423967/218915984-371d5b76-0830-469d-a497-4f69fb9de6a8.jpg)

**Comment by Blizzardsev** [comment]
I should note: you will need to send it inside a zip file in order for GitHub to allow it to be uploaded.

**Comment by Blizzardsev** [comment]
Also, could you please send through your log file? It should be under the log folder.

**Comment by ClapTrap125** [comment]
After doing some digging, it does seem to be an issue with the persistent. Starting a completely brand new game is fine but transferring the old persistent into the new game causes the problem. @Blizzardsev 
[New Compressed (zipped) Folder.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10744414/New.Compressed.zipped.Folder.zip)

**Comment by Blizzardsev** [comment]
Hi @ClapTrap125 - can you please send a screenshot of your old installation's `game` folder?

**Comment by Blizzardsev** [comment]
Hi @ClapTrap125 - is this no longer an issue for you? I should note that this isn't an error per se, and occurs under limited circumstances. Can you please confirm what steps you took to solve your problem?

**Comment by Blizzardsev** [comment]
Hi @ClapTrap125 - I am closing this issue under the assumption it is no longer of concern to you.

To be frank, that particular screen is presented when unusual game activity/progression in line with cheating is found: given this and the lack of activity on the ticket, as per our [terms](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#i-want-to-modifyhave-already-modified-my-installation-can-you-help-me-if-something-goes-wrong) regarding cheating, we will be withdrawing your right to our support in the future.
