### ISSUE TITLE
[ BUG REPORT ] - Help button redirects to msn

### ISSUE THREAD

**Issue by ZeroPointNothing** [Just-Natsuki-Team/NatsukiModDev#547]
# Overview:
In the menu, the help button does not actually lead anywhere useful, instead redirecting me to msn.

## Replication steps:
I simply press the help button in the menu, and it opens up https://www.msn.com/?pc=DCTE in a new window.

## Additional information:
I am using Windows 11, running on the 1.0.3 update and Microsoft Edge is opening the link. The GitHub button does work and directs me here, however.

**Comment by Blizzardsev** [comment]
Hi @ZeroPointNothing - the Help button is configured to bring up the README document we supply with each release; can you confirm if this is in your JN installation?

**Comment by ZeroPointNothing** [comment]
After adding the README, the issue was solved. It now opens it properly. Thanks!

**Comment by RaionArt** [comment]
Glad it worked.
