### ISSUE TITLE
[ SUPPORT REQUEST ] - Cannot launch JN

### ISSUE THREAD

**Issue by OchitaK** [Just-Natsuki-Team/NatsukiModDev#549]
Game cannot be opened

At the top says "An problem has occurred. please contact JN staff" without any detail and I've done every step right.
![Screenshot (798)](https://user-images.githubusercontent.com/125753487/219875794-74f4cc7a-8936-4e7a-89d0-f655aef3cb90.png)

**Comment by RaionArt** [comment]
Hello @OchitaK!
Please send your log file from the log folder and persistent forward so we can look into it. You will need to attach it here inside a zip archive so GitHub will allow it to be uploaded.

**Comment by OchitaK** [comment]
[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10774691/log.txt)

**Comment by OchitaK** [comment]
> สวัสดี@OchitaK! โปรดส่งไฟล์บันทึกของคุณจากโฟลเดอร์บันทึกและส่งต่ออย่างต่อเนื่องเพื่อให้เราสามารถตรวจสอบได้ คุณจะต้องแนบที่นี่ภายในไฟล์ zip เพื่อให้ GitHub อนุญาตให้อัปโหลดได้

[log.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10774728/log.zip)

**Comment by RaionArt** [comment]
I'm sorry, but your zip archive is empty. It needs to contain your persistent and log file.

**Comment by OchitaK** [comment]
[log.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10774749/log.zip)

@RaionArt  Hope this will work

**Comment by RaionArt** [comment]
Thanks for the log, but I also need your persistent file. Everyone has one, as it is your save file.
To locate your persistent, enter the following into the search bar of your file manager, based on your operating system:

Windows: %APPDATA%/RenPy/JustNatsuki
OSX: ~/Library/RenPy/JustNatsuki
Linux: ~/.renpy/JustNatsuki

**Comment by OchitaK** [comment]
[persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10774797/persistent.zip)

@RaionArt

**Comment by Blizzardsev** [comment]
Hi @OchitaK - please refer to the instructions here to locate and send your persistent: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent

**Comment by OchitaK** [comment]
[persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10776513/persistent.zip)

@Blizzardsev

**Comment by OchitaK** [comment]
Thanks for information, Now I've figured out how to fix this error and launch the game. I will close this issue now, Thank you

**Comment by Blizzardsev** [comment]
Hi @OchitaK - I should note this isn't an error per se; the root cause can vary. Can you please confirm what steps you took to solve your problem?
