### ISSUE TITLE
I'm sorry, but an uncaught exception occurred.

### ISSUE THREAD

**Issue by CyganBlyat** [Just-Natsuki-Team/NatsukiModDev#550]
# Overview:
Hello, an error occurs during the dialog. However, you can skip it and the conversation will continue without problems.
[traceback.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10776609/traceback.txt)

## Replication steps:
Tell me again about->Society->how to interview properly
"And when it comes down to the wire?" - After these words, an error occurs

## Additional information:
OS-Windows 10, Mod version - 1.0.3
Recently, the mod was completely reinstalled

**Comment by Blizzardsev** [comment]
Hi @CyganBlyat - this was something we patched a couple of days ago. Can you please try downloading the latest release again and updating your installation?

**Comment by CyganBlyat** [comment]
I have updated the game again, however, nothing has changed :<

**Comment by Blizzardsev** [comment]
Can you please confirm which files you are using to perform the update? I've checked the release distribution manually and it is patched. Are you running source code files?

**Comment by CyganBlyat** [comment]
No, I download exactly jn-1.0.3.zip,weighing 290 mb and updated 2 days ago
Could there be a reason that I completely reinstalled the mod a couple of days ago?

**Comment by CyganBlyat** [comment]
Sorry, missklick!!!

**Comment by Blizzardsev** [comment]
Could you please send a screenshot of your `game` folder?

**Comment by CyganBlyat** [comment]
![19-02-2023 19-37-53](https://user-images.githubusercontent.com/123293712/219948539-ab09bfdb-7eeb-4402-a8c6-920f44a4a722.png)
![19-02-2023 19-38-27](https://user-images.githubusercontent.com/123293712/219948543-4b24b05f-d7ed-46a7-9c5e-d7f3ff7380d5.png)
![19-02-2023 19-38-34](https://user-images.githubusercontent.com/123293712/219948544-3edf9dd1-3ec6-4b3d-a4c0-bbd5122a9ea0.png)

**Comment by Blizzardsev** [comment]
Okay, I see the problem. You have previously downloaded the source code files - these are the ones with an extension of `.rpy`. When DDLC runs, the `.rpy` files are compiled and overwrite the `.rpyc` files.

When we supply updates, we always supply them in `.rpyc`: by having the source files there, you have basically overwritten the updated files with an earlier version: this is why we always recommend using the releases, not the source code.

Please delete all the `.rpy` and `.rpyc` files in that folder, and copy in only the `.rpyc` files from the `game` folder of a new download of the latest release.

**Comment by CyganBlyat** [comment]
And it worked. Thank you. And I apologize for the time spent because of my mistake

**Comment by Blizzardsev** [comment]
No worries.
