### ISSUE TITLE
[ SUPPORT REQUEST ] - 

### ISSUE THREAD

**Issue by RheaJaneRJ112** [Just-Natsuki-Team/NatsukiModDev#552]
# Overview:
Hello! I'm new here and just started yesterday.
So I downloaded the mod and did everything right but when I said goodbye to her and left when I came back it always resets from the start and I have to start from scratch I even save the persistent file and have a backup but it still doesn't work. :"(
How do I fix this? 
It's kind of frustrating to see. :")

## Additional information:

[just natsuki memo.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10799352/just.natsuki.memo.zip)

**Comment by RaionArt** [comment]
Hello @RheaJaneRJ112. Thank you for your persistent file. Could you please send your log and maybe a screenshot of your `game` file as well?

**Comment by RheaJaneRJ112** [comment]
> Hello @RheaJaneRJ112. Thank you for your persistent file. Could you please send your log and maybe a screenshot of your `game` file as well?

**Comment by RheaJaneRJ112** [comment]
So here's my log I think? 
But I do not know what game files you're that you mention? :")

[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10799445/log.txt)

**Comment by RheaJaneRJ112** [comment]
> So here's my log I think?
But I do not know what are the game files you mention. :")

[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/10799504/log.txt)

**Comment by RheaJaneRJ112** [comment]
> So about this problem of mine, I finally manage to fix it. ^^" I have to reinstall the mod and the game and do it all over again, maybe I did something wrong somewhere but now every time I closed her the game does not reset again tho I have to just start from scratch again. :" ) 
I'm sorry for the trouble I caused. 😅
