### ISSUE TITLE
[ FEATURE REQUEST ] - Daily Jokes

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#559]
# Overview:
To reward players to check on their Natsuki daily, we can introduce `daily jokes`! Natsuki will find a joke book, introduced by a short topic. Everyday Natsuki can read out one joke. We would have a few prepared intros and outros for the jokes, which will appear randomly, with the joke being between. 
As an example:
"Hey! Hey! You're gonna love this one, player!"
(joke)
"Well, this one had a nice twist to it!"

## Must haves:
- introduction of the topic
- art asset for the book
- multiple jokes
- a few intros and outros

## Could haves:
- Maybe some special jokes themed for specific holidays?

## Is this feature request related to a problem? Please describe.
New feature

**Comment by Blizzardsev** [comment]
I like this idea a lot! Giving players a reason to visit Natsuki every day aside from hitting the daily cap and the chance to see a new introduction event is welcome, and this seems right up her alley! The modular approach you describe will help things feel fresh with the randomised intro, outro and joke.

I'd be happy to take this up!

**Comment by Blizzardsev** [comment]
@Obsidian-Knife Any thoughts?

**Comment by Blizzardsev** [comment]
This will be added in v1.1.0.
