### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki talking about job/office experience!

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#565]
# Overview:
Natsuki can talk about her experience in a job office. There are multiple ways to tackle this topic! For an example we could claim Natsuki tried to be more independent and wanted to start working to provide for herself. Another possibility would be that the school made the students experience some work environment. Natsuki could express her concerns and annoyance about office work,l ike the lack of digitalization, struggles with printers (missing magenta?) and so on! With her new and stylish outfit, she could also demonstrates her commitment to leave a positive first impression and mentioned how she fluffed up her hair by herself (probably to save money and to have something to be proud of _as expected from our little gremlin_).

## Must haves:
Maybe need to adjust the `interview` topic slightly, as Natsuki mentions she was too busy for a part-time job or need to be careful of this in the new topic!
- new `office_blazer`
- new `wavy` hair
- additional `formal_necktie`

## Could haves:
Maybe extra dialogue if the player listened to the interview topic!

## Is this feature request related to a problem? Please describe.
New topic with unlockables!

**Comment by Blizzardsev** [comment]
Picking this up.

**Comment by RaionArt** [comment]
Introduced with v1.3.
