### ISSUE TITLE
[ FEATURE REQUEST ] - Log the Affinity Number when the event Affinity+ happens.

### ISSUE THREAD

**Issue by glowberri** [Just-Natsuki-Team/NatsukiModDev#568]
# Overview:
What this does is that whenever the Affinity goes up for example, when you check up on Natsuki for the day. Just like how MAS works it should be able to display what the Affinity is when it's about to log Affinity+. Let's just say that my Affinity went up by 2 and my old Affinity was 73, it should display for example (Affinity+ > 73.2984392 > 75.4023795)

I knew people who played MAS before and I know for sure that without knowing what the Affection/Affinity number is, it makes them impatient. So if you want to add this please do. Thank you so much.

**Comment by Blizzardsev** [comment]
Hi @glowberri , thanks for raising a suggestion with us.

This is something that has come up in the past a few times. Although it isn't publicly visible anymore, we held an FAQ and answered this question some time ago. Our position is as follows:

_"No, we don't plan to add a means of checking the affinity value. This has been brought up a few times, but as a team we feel that it devalues the relationship between Natsuki and the player by tying actions to a solid number - and although not something we fully agree with, the log already offers reassurance that affinity gains/losses/cap changes are taking place. We also want to avoid a situation like in MAS, where players compare affinity values from the log as milestones or competition._"

_"Additionally, we'd also like to note that players can already find out how Natsuki feels about them generally through a specific topic "How do you feel about me?", and we plan to introduce another hint in the form of how Natsuki decorates her desk!"_

I understand where you're coming from, but people will be impatient regardless of how much information is given: and as we've seen in MAS previously, this tends to lead to people asking at what value X feature is unlocked, and so on.

Ultimately, we feel the current logged values are at a good balance between providing enough information for debugging (which is what a log **should** be used for), and to sate player curiosity, and I don't personally see this changing any time soon.
