### ISSUE TITLE
[ BUG REPORT ] - Game fails to register a new custom outfit even though I followed the wiki

### ISSUE THREAD

**Issue by Megalonumber0ne** [Just-Natsuki-Team/NatsukiModDev#574]
# Overview:
Tried to add a custom outfit DM'd to me on Discord, outfit doesn't show up in the outfit list, and produces this error when asking Natsuki to check for a custom outfit: `Cannot register wearable name: red_lady, as a wearable with that name already exists.`

## Replication steps:
I followed the wiki page for adding premade outfits for this error, not sure how to replicate it

## Additional information:
Date: 2023-03-12
Outfit name: red_lady
Operating System: Windows 10 22H2 - Windows 10 Home Edition

**Comment by Megalonumber0ne** [comment]
![image](https://user-images.githubusercontent.com/87905744/224571850-59c8e153-53d7-4800-a840-c9138af4fe10.png)
Custom wearables folder ^
![Screenshot 2023-03-12 203242](https://user-images.githubusercontent.com/87905744/224571883-47f800c9-fcf4-4548-b2d4-9bf232f1b155.png)
Custom outfits folder ^

**Comment by Blizzardsev** [comment]
Hi @Megalonumber0ne - could you please send me a copy of your persistent, as well as a copy of the outfit pack you are trying to set up?

**Comment by Blizzardsev** [comment]
For the persistent, you would need to upload this in a zip file: it'd be easiest to do this alongside the outfit items.

**Comment by Megalonumber0ne** [comment]
> Hi @Megalonumber0ne - could you please send me a copy of your persistent, as well as a copy of the outfit pack you are trying to set up?

It actually started working, I'm not sure what made it work. Do I still link my persistents and the outfit?
I did ping you on discord about this earlier if I'm recalling correctly

**Comment by Blizzardsev** [comment]
Ah, I must have missed it - things have been a little hectic lately. I'd guess you probably had a duplicate definition somewhere that you've since removed, allowing the wearable to be registered successfully and therefore appear in game.

Don't worry about the files: if you're happy everything is working, then I can go ahead and close this issue.

**Comment by Megalonumber0ne** [comment]
> Ah, I must have missed it - things have been a little hectic lately. I'd guess you probably had a duplicate definition somewhere that you've since removed, allowing the wearable to be registered successfully and therefore appear in game.
> 
> 
> 
> Don't worry about the files: if you're happy everything is working, then I can go ahead and close this issue.

I’m happy for you to end the issue now, thank you for your patience.
