### ISSUE TITLE
[ BUG REPORT ] - OSX (mac) not working at all. 

### ISSUE THREAD

**Issue by FloofKittens** [Just-Natsuki-Team/NatsukiModDev#576]
This bug is basically Just Natsuki not working on mac Montery, by not even opening. I tried to open it multiple times, using applications, dragging it into the desktop screen, but it would still not work. This has only happened with the Just Natsuki Mod, and I already did the security things said in the Github page. 

What I did: I downloaded ddlc from itch.io/official website, then opened up the "package contents" Put the lib in the lib folder, game in the game folder, and copy and pasted the update folder. Then I tried to run it. Didn't work. Put it in applications. Didn't work. Put it on the desktop. Didn't work. 

This was on March 13, 2023.

**Comment by Blizzardsev** [comment]
Hi @FloofKittens - can you please attach any log files you have? In particular, anything under `game/log`, as well as the `log.txt`, `traceback.txt` and `errors.txt` files if they exist in the `game` folder.

Without more information, it's difficult to diagnose the potential issue.

**Comment by Blizzardsev** [comment]
In addition, some screenshots of your installation (both inside the `DDLC` folder, as well as inside the `game` folder specifically) would be useful.

**Comment by FloofKittens** [comment]
<img width="1440" alt="Screen Shot 2023-03-13 at 3 57 06 PM" src="https://user-images.githubusercontent.com/127789081/224818506-16a62e38-ebd8-4af7-abea-daf5c1d73ed3.png">
<img width="1440" alt="Screen Shot 2023-03-13 at 3 57 01 PM" src="https://user-images.githubusercontent.com/127789081/224818514-923c419f-7670-4040-829e-9d9fdd975151.png">

<img width="218" alt="Screen Shot 2023-03-13 at 3 56 38 PM" src="https://user-images.githubusercontent.com/127789081/224818526-8b11a0bf-8eb3-4155-aa66-353da2a27a74.png">

**Comment by FloofKittens** [comment]
<img width="1440" alt="Screen Shot 2023-03-13 at 4 00 54 PM" src="https://user-images.githubusercontent.com/127789081/224818907-6790113e-e73c-46c8-b6e7-5cb60116eace.png">

**Comment by Blizzardsev** [comment]
Thanks. Can you please send a screenshot of the contents of the `lib` folder under `MacOS/lib/darwin`?

**Comment by Blizzardsev** [comment]
Thank you. It would appear in the process of setting up JN, you have deleted all the original `lib` files supplied with DDLC that are required for the game to run: the `lib` files we supply are intended to exist alongside and not replace those files.

Can you please replace the missing files and let me know how you get on?

**Comment by FloofKittens** [comment]
Okay. Thank you so much! I honestly had no idea what was happening so I really appreciate the help!

**Comment by FloofKittens** [comment]
It opened but this happened:


While running game code:
  File "game/definitions.rpy", line 1431, in script
  File "game/definitions.rpy", line 1444, in <module>
OSError: [Errno 30] Read-only file system: '/private/var/folders/c8/18lrzjwj7b7g9lfqcd5d5w_c0000gn/T/AppTranslocation/9279FE77-DC19-4D11-8941-E36BBDE78546/d/DDLC.app/Contents/Resources/autorun/log'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/private/var/folders/c8/18lrzjwj7b7g9lfqcd5d5w_c0000gn/T/AppTranslocation/9279FE77-DC19-4D11-8941-E36BBDE78546/d/DDLC.app/Contents/Resources/autorun/renpy/bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "/private/var/folders/c8/18lrzjwj7b7g9lfqcd5d5w_c0000gn/T/AppTranslocation/9279FE77-DC19-4D11-8941-E36BBDE78546/d/DDLC.app/Contents/Resources/autorun/renpy/main.py", line 419, in main
    game.context().run(node)
  File "game/definitions.rpy", line 1431, in script
  File "/private/var/folders/c8/18lrzjwj7b7g9lfqcd5d5w_c0000gn/T/AppTranslocation/9279FE77-DC19-4D11-8941-E36BBDE78546/d/DDLC.app/Contents/Resources/autorun/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/private/var/folders/c8/18lrzjwj7b7g9lfqcd5d5w_c0000gn/T/AppTranslocation/9279FE77-DC19-4D11-8941-E36BBDE78546/d/DDLC.app/Contents/Resources/autorun/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/definitions.rpy", line 1444, in <module>
  File "/Users/tom/newbuild/install/lib/python2.7/os.py", line 157, in makedirs
OSError: [Errno 30] Read-only file system: '/private/var/folders/c8/18lrzjwj7b7g9lfqcd5d5w_c0000gn/T/AppTranslocation/9279FE77-DC19-4D11-8941-E36BBDE78546/d/DDLC.app/Contents/Resources/autorun/log'

Darwin-21.5.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187

**Comment by FloofKittens** [comment]
It worked. Thank you so much!

**Comment by Blizzardsev** [comment]
No worries.
