### ISSUE TITLE
[ BUG REPORT ] - Audio makes cracking noise on new macs

### ISSUE THREAD

**Issue by AToska21** [Just-Natsuki-Team/NatsukiModDev#577]
# Overview:
Whenever you make a lot of SFX in the menu, such as scrolling through topics, a cracking sound will play.

## Replication steps:
Open "Let's talk about..." menu and move your mouse up and down.

## Additional information:
MacOS Ventura 13.2, Macbook Air M2, 2022

**Comment by Boxit379** [comment]
I've noticed this happening with most DDLC mods (on an M1 macbook) so I don't think it's a bug with this one specifically

**Comment by AToska21** [comment]
> I've noticed this happening with most DDLC mods (on an M1 macbook) so I don't think it's a bug with this one specifically

Maybe it's an issue with the audio library RenPy uses?

**Comment by Blizzardsev** [comment]
Hi @AToska21,unfortunately there isn't much we can do here beyond upgrading the version of Ren'Py JN runs on, which is already on our to-do list.

Ren'Py is somewhat infamous for menuing not being a strong point, and this is among the reasons why (alongside game slowdown when rapid menuing, etc.).

Given we don't have an ETA on the Ren'Py version upgrade, and we can't guarantee this will resolve the issue, I will be closing this issue. I would recommend turning down the sounds if it becomes a major annoyance, and we may look at adding a toggle for menu sounds specifically when possible.
