### ISSUE TITLE
[ BUG REPORT ] - Custom Clothing unable to be loaded

### ISSUE THREAD

**Issue by IdkuXD** [Just-Natsuki-Team/NatsukiModDev#579]
# Overview:
[Clothing Assets; specifically “clothes” and “sleeves” cannot be loaded]

## Replication steps:
[The custom assets that I had used were the “Nat in Time” by RaionArt and custom clothings by Mayday mayjay.

Some of the specific assets I had used were the following: “star mesh dress” and “dark red evening dress” from the “clothes” folder, the “rose set” from the “accessory” folder, the assets from the “necklace” folder.

I had made copies of the assets and placed the assets in their respective locations. After placing the assets, I open Just Natsuki and I am met with a greeting from Natsuki and an error message to check the log.

Examining the log, it will state the following: “Cannot load wearable (outfit file name) as one or more key attributes do not exist”.]

## Additional information:
[I had copy and pasted the assets from a separate folder, into the respective locations that the assets were supposed to be. Assets such as “accessory”, “headgear”, “necklace” were the only groups that were able to be loaded. The categories of “clothes” and “sleeves” are unable to be loaded.]

**Comment by RaionArt** [comment]
Hello @IdkuXD! 

There is a problem with the outfit (which consists of multiple parts  of clothes). I think the problem is you pasted the content in the seperate folders, so there is no connection to the outfit. 

You only need to copy the all of the outfit folder contents into your main DDLC folder. It will "sort" all the contents by itself.

This is also stated here: https://github.com/Just-Natsuki-Team/NatsukiModOutfits

It might be worth to delete your manual made additions, before adding the outfit the intended way.

**Comment by IdkuXD** [comment]
Following the instructions you had left, it seems that this is what you meant, correct? If not, could you explain further?

Upon opening Just Natsuki, I was greeted with the same error message.

https://user-images.githubusercontent.com/128346241/226469867-97c38b22-01ff-4eb7-b41a-312e73611bc2.MOV

**Comment by Blizzardsev** [comment]
Hi @IdkuXD - this error specifically pertains to the definition file, and is stating that the definition file given is incorrect and doesn't match our specifications, as confirmed on our wiki here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/06:-Custom-clothing-and-outfitting-guide-(Spoilers)#cannot-load-wearable-as-one-or-more-key-attributes-do-not-exist

Can you please attach the outfit packs you were given for us to examine?

**Comment by IdkuXD** [comment]
I can send a link to the drive I had gotten the sprites from. I hope this helps.

https://drive.google.com/drive/mobile/folders/1Lf69RkxQEOiBi8p4RO9zgOTLoPo0Cg7b

**Comment by Blizzardsev** [comment]
Hi @IdkuXD, can you please also send us your log file? There's a lot of assets to go through here - you've listed some, but the log would give us a complete list of what is failing to load.

**Comment by IdkuXD** [comment]
I highlighted the part of the log that is most important. This is a screenshot of when I had asked Natsuki to check for new outfits. Im the log. It states that the dresses are the only assets that are not loading. I had recently downloaded the newest version of the outfits which at this point includes “Nat in Time” and “Natsupara” dresses respectively, but also, the previously mentioned “Pinkstarmesh” dress. The hats such as the Natsupara’s bonnet is able to be loaded, however the dresses are the only things that are not loading and failing.

![6EDBB0CF-ED43-4EF3-8678-E0BB852EDBAF](https://user-images.githubusercontent.com/128346241/227815261-c58b9997-f7ff-4659-a486-2e5dbc850efe.png)

**Comment by Blizzardsev** [comment]
Hi @IdkuXD - the error messages suggest that the outfits were not added properly: for any officially distributed outfits, all that is required to add them is to copy the contents of each item to the base (DDLC) folder of your installation.

For example, to install the `raionart_natsupara` outfit, following the instructions we provide, the following would be copied from the _raionart_natsupara_ folder in the downloaded pack:

![image](https://user-images.githubusercontent.com/57731669/228671759-2b0f93a7-9493-4864-b87c-320430eff5ce.png)

And pasted here:

![image](https://user-images.githubusercontent.com/57731669/228671833-4819ef44-b7b6-481c-b6f0-a77c345b1af1.png)

The way we arrange/package our official add-ons means they should sort themselves out - we verify this with testing before we release add-ons. This is also why we do not recommend users manually copy assets across.

Looking at the spritepack by May, this should also be the case for their items. Can you please try installing the items again using the instructions listed [here](https://github.com/Just-Natsuki-Team/NatsukiModOutfits#installation-and-usage-instructions) as I have described above?

**Comment by IdkuXD** [comment]
Reading through the instructions given, and executing what was instructed, it seems that the issue is still arising to where only the accessories and headgear are loading properly. I select and copy the contents into the base (DDLC) folder of my installation, as previously instructed.

I’m sure there is an error on my part, considering how it was mentioned that it has been tested before release, as I continue to experience the same issue of specific contents loading/not loading properly. Is it possible you can send a short clip of the process? Many thanks in advance.

**Comment by Blizzardsev** [comment]
Hi,

Please follow the steps as shown:

Download the outfit pack, unzip it, and go into the folder for the outfit you want to add:
![1](https://user-images.githubusercontent.com/57731669/228982486-0cfe2a54-c7dd-4346-8268-5713955c9f12.png)

Copy all the files inside that folder to your clipboard:
![2](https://user-images.githubusercontent.com/57731669/228982497-fbaa929c-01ce-4a42-9969-5f7e3b34c4ed.png)

Paste those files directly into the DDLC directory.
![3](https://user-images.githubusercontent.com/57731669/228982508-53d06637-3fd0-457f-b3c3-0d54e062fab9.png)

![4](https://user-images.githubusercontent.com/57731669/228982516-8abd0c48-a002-42f0-b4d1-5664b3bf0613.png)

Launch JN. **Do not go straight into the outfit designer/selector**: _wait_ for Natsuki to bring up the gifts you have just given her; this may take a few minutes. If she does not do this after a minute or so, ask her to check for new outfits and wait for her to be presented with the gift box.

![5](https://user-images.githubusercontent.com/57731669/228983247-704c66d2-5de1-4564-947f-c5c3e9c99dcb.png)

![6](https://user-images.githubusercontent.com/57731669/228983258-b019a252-8090-4d6f-80cf-609605cd9113.png)

![END](https://user-images.githubusercontent.com/57731669/228983489-c5f9e861-d135-429c-b1c6-11df515d2705.png)

**Comment by RaionArt** [comment]
@IdkuXD Has the guide of Blizzard help you? 

There isn't really much more we can do to show you exactly what you need to do. If it still doesn't work I would think something isn't right with your JN setup

**Comment by IdkuXD** [comment]
Hi @RaionArt, sorry for the late reply. As for the instructions, I followed them properly, however the outfit still does not seem to load properly. I had also tried redoing the installation, backing up my persistent file and running the game, even going as far as wiping all of the custom clothing I had made with the vanilla outfits I could unlock. Nevertheless, after much trial and error, I could only get the accessories to load.

After considering what might be the issue, it’s reasonable to conclude that my JN setup isn’t right, however as to what isn’t right in particular I am unsure of.

**Comment by Blizzardsev** [comment]
Hi @IdkuXD  - if you update to the newest release, this should be resolved - ask Natsuki to wear a custom outfit and she should immediately jump into the gift dialogue.

**Comment by IdkuXD** [comment]
@Blizzardsev Upon installing the update, the outfits are now currently loading properly. I initially started by backing up the outfits I had made from the previous 1.03 version, and had started to importing the outfits. I had started off with the official outfits from GitHub. Many thanks to you and @RaionArt for helping me with this.
