### ISSUE TITLE
[ SUPPORT REQUEST ] - Outfit(s) not loading properly

### ISSUE THREAD

**Issue by YourSeventhShadow** [Just-Natsuki-Team/NatsukiModDev#582]
# Overview:
I recently downloaded the JN Outfits 1.1.0 Pack and tried to follow the README instructions. However, for both the Natsuki in Time and the Natsupara outfits, for whatever reason, only the head wearables are "delivered" to Natsuki. This includes the Natsuki in Time hat, and the Natsupara bonnet. The rest of the clothes aren't loading in. 

## Additional information:
I've tried moving the .json files to different spots. Right now, they're both copied and pasted in both the custom_wearables and the custom_outfits folders. I've also copied and pasted each of the individual subfolders for the different parts of the outfits into their respective folders in the mod_assets folder. For example, the raionart_natsupara_bonnet folder is in the headgear folder, and the raionart_natsupara_dress folder is in the clothes folder. Yet, only the bonnet shows up in the game. The same applies for the raionart_nat_in_time_hat vs. the raionart_nat_in_time_dress. 

Forewarning, I'm not a tech guy and haven't done a lick of coding in my entire life. Is there anything I can do to fix this? I'm more than happy to upload screenshots if that would help.

**Comment by Blizzardsev** [comment]
Hi @YourSeventhShadow - could you please raise an issue on the outfits repository specifically [here](https://github.com/Just-Natsuki-Team/NatsukiModOutfits/issues/new/choose)? This repository is for core game content rather than add-ons.
