### ISSUE TITLE
[ SUPPORT REQUEST ] - says to contact jn team

### ISSUE THREAD

**Issue by shakyevan444** [Just-Natsuki-Team/NatsukiModDev#583]
# Overview:
Random error message thing

## Additional information:
Macos on M1
![image](https://user-images.githubusercontent.com/84460058/227806970-b0e6350a-e127-4c7f-b71a-5165bc67ecfb.png)

**Comment by Blizzardsev** [comment]
Hi @shakyevan444 - please can you provide your log file and persistent? You will need to attach these in a zip folder.

**Comment by shakyevan444** [comment]
[persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/11073177/persistent.zip)
and where do i get a log file from?

**Comment by shakyevan444** [comment]
[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/11073178/log.txt)
nvm here

**Comment by shakyevan444** [comment]
removing my persistent boots fine just has none of my data ofc

**Comment by Blizzardsev** [comment]
Apologies, could you please provide the log file under the log folder?

**Comment by shakyevan444** [comment]
its an empty folder :P

**Comment by shakyevan444** [comment]
i guess ill just use a new save, old one was brand new anyways :P

**Comment by Blizzardsev** [comment]
Hi @shakyevan444 - I think it's pretty clear what you've been doing here:

![image](https://user-images.githubusercontent.com/57731669/227807604-eccf8e30-4c13-4dac-8884-61a6fbec5286.png)

As per our terms and conditions, we will be revoking your right to support for JN.

Thank you!
