### ISSUE TITLE
[ FEATURE REQUEST ] - Additional Twitch-based games

### ISSUE THREAD

**Issue by Catgu20** [Just-Natsuki-Team/NatsukiModDev#585]
# Overview:
Adding more minigames. As we know, Natsuki has that "Wintendo Twitch", so I think it would be cool to add minigames related to it.

## Must haves:
Competitive minigames VS Natsuki

## Could haves:
Maybe Natsuki could randomly offer you to play

**Comment by RaionArt** [comment]
Hello @Catgu20 and thank you for raising an issue with us,

can you be a bit more specific what you have in mind? Like an arcade game and if yes, which kind?

Also please add titles to the issue as there is no way to figure out what  the issues is about when we only see the lists of issues.

**Comment by Catgu20** [comment]
> Hello @Catgu20 and thank you for raising an issue with us,
> 
> can you be a bit more specific what you have in mind? Like an arcade game and if yes, which kind?
> 
> Also please add titles to the issue as there is no way to figure out what the issues is about when we only see the lists of issues.

**Comment by Catgu20** [comment]
I guess I understand my ideas better now. 

Yeah, now I think of some kind of arcade 8-bit games like Super Mario Bros. or Donkey Kong. 

The idea is Natsuki having a highscore and offering you to try beating it. After you beat it, there will be a chance for her to get a new, better highscore (She will tell you about it in a random chatter or in a notification) and offering to beat it again. I think it could be endless, like Natsuki always setting a higscore that is 2x of your previous one. That's all for now


I'm really sorry to waste your time with my vague ideas, but I think it will help. Thanks

**Comment by Blizzardsev** [comment]
Hi @Catgu20, thanks for your input.

While it would be neat to see some more dynamic games, especially given Natsuki has her Twitch, unfortunately this is something Ren'Py as an engine (especially the outdated version we are looking to move away from when possible) isn't equipped to deal with: there's a reason MAS, et al haven't attempted much more than Pong in this regard!

It's also important to remember that games are a huge investment from a dev/testing point of view: even something like a card game carries with it a big requirement for dev effort that cannot then be used elsewhere (like support, topic production, etc.) - I don't think personally that we could justify that level of investment on something the engine really isn't made to handle in the first place.

Thank you for your suggestion, however!
