### ISSUE TITLE
[ BUG REPORT ] - There is an error in the log but im not sure what it means..

### ISSUE THREAD

**Issue by MelodyIsGaymer** [Just-Natsuki-Team/NatsukiModDev#587]
![image_2023-03-27_174244320](https://user-images.githubusercontent.com/129119521/228073528-d5d1ecaa-c10f-43e1-b942-4d5da4f7434a.png)

**Comment by Blizzardsev** [comment]
Hi @MelodyIsGaymer, thanks for raising a bug report with us.

We've identified the issue and will look to introduce a resolution when we can.

**Comment by Blizzardsev** [comment]
Hi @MelodyIsGaymer - if you update to the newest release, this will be resolved.
