### ISSUE TITLE
[ ART REQUEST ] - Cheongsam for Natsuki.

### ISSUE THREAD

**Issue by VendixDilan** [Just-Natsuki-Team/NatsukiModDev#592]
I had the idea for Natsuki to have a Cheongsam, I think it'll look really cute on her.
But since I lack the skills to draw and do it myself, I try asking for help.

I had a Red with a Golden detailed Cheongsam in mind, but feel free to draw it however you want it to!
(Maybe even with a Bun).

Depending on how detailed you want to make it, it can differ. 
You can also make multiple colorations of it, but it's all up to you.

Thanks for reading, I hope I could give some of you some inspiration for what to do next!

**Comment by RaionArt** [comment]
Thank you for the idea @VendixDilan!

I feel like this is a good opportunity to add some hair accessories which could be used with the `twin_buns` hairstyle.

The biggest challenge would be, that we would need to add a way to make this outfit unlockable. So as an example we would need a kind of topic which fits to the given outfit, in this case the cheongsam dress. Do you have an idea what Natsuki could talk about to unlock this?

**Comment by VendixDilan** [comment]
Maybe she's talking about Chinese food? Or just the Chinese Culture in general.
Examples of it would be:
- Chinese New Year
- Forbidden City
and of course, the Great Wall of China!

**Comment by Blizzardsev** [comment]
After some discussion I don't think this is something we'd carry forward into vanilla mod content.

While the Cheongsam is a cute design, I don't think there's really a clean way to fit this into a topic: while we can tie it to something like Chinese New Year (which has already passed, and we try to avoid culture-specific celebrations where they aren't widely known), we're also at a point where a lot of outfits have been introduced through topics so far and it's starting to feel somewhat congested having to shoehorn in an outfit change/outfit mention so frequently.

However, I do think this would be a good candidate for optional content! We can look at adding this to the list in the NatsukiModOutfits repo when we get the chance.

Thoughts @RaionArt?

**Comment by RaionArt** [comment]
I agree with BlibBlub, I'll close this issue, but I want to put that outfit to my list of things I would like to release as an official outfit!

**Comment by VendixDilan** [comment]
[chinese-new-year.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/11325501/chinese-new-year.zip)
I've made a example, it's just a way to maybe include it.
It's okay if you still don't want to do it though, so no pressure.
