### ISSUE TITLE
[ SUPPORT REQUEST ] - natsuki isnt in her chair anymore

### ISSUE THREAD

**Issue by toastyboi56** [Just-Natsuki-Team/NatsukiModDev#596]
# Overview:
[brief description of the issue(s) you are facing]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Hi @toastyboi56 - can you please send your persistent file? You can find it using the instructions here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent

**Comment by Blizzardsev** [comment]
As discussed on Discord, this happens when adjusting the date/time to access events, etc. that are not meant to be accessible until their date - as per our policy on cheating, we will be closing this ticket and revoking support.
