### ISSUE TITLE
[ BUG REPORT ] - Crash screen pops up after clicking “never mind” button

### ISSUE THREAD

**Issue by ewSenpai** [Just-Natsuki-Team/NatsukiModDev#599]
# Overview:
Whenever I want to tell Natsuki something and I changed my mind, I click the “never mind” button and the crash screen pops up.

## Replication steps:
It happens when I click “I want to tell you…” and “I want to say sorry…” option and then I click “never mind ” option. It crashes when that happens.

## Additional information:
It never happened until I updated the mod to V1.1.0

**Comment by Blizzardsev** [comment]
The root cause for this is known - working on a patch now.
