### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki and languages

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#60]
# Overview:
This feature will introduce a new topic prompted by the player, allowing them to discuss languages with Natsuki and her experiences learning them.

## Must haves:
- New topic "Learning languages"; where Natsuki and the player can discuss their experience learning different languages and the challenges of trying to study another language.

## Could haves:
- Ability for the player to specify whether they know any languages other than English, and for Natsuki to respond accordingly with a quip in that language (for example, telling Natsuki you can speak French might have her tease you in French).

## Is this feature request related to a problem? Please describe.
This is a new feature.

**Comment by RaionArt** [comment]
Is included in #507
