### ISSUE TITLE
red rpy files after update.

### ISSUE THREAD

**Issue by Drago288** [Just-Natsuki-Team/NatsukiModDev#601]
![image](https://user-images.githubusercontent.com/114190230/230744685-e26ef8d8-c4aa-4fb3-9a79-37b7ababff0b.png)
this shows after the update.

**Comment by Blizzardsev** [comment]
Hi @Drago288 - please refer to the FAQ entry here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#why-is-my-game-warning-me-about-running-source-rpy-files

**Comment by Blizzardsev** [comment]
Also, v1.1.1 has just been released to resolve an issue related to crashing: please update when possible.

**Comment by Drago288** [comment]
but i don't have any rpy files nor i run modyfied version.

**Comment by Blizzardsev** [comment]
Hi @Drago288, please provide a screenshot of your `game` folder.

**Comment by Drago288** [comment]
![image](https://user-images.githubusercontent.com/114190230/230744906-363feb27-1f53-4b4b-999a-d3a567df6f09.png)
![image](https://user-images.githubusercontent.com/114190230/230744952-965e4819-c9ac-4375-bf31-581a2f569af8.png)

**Comment by Blizzardsev** [comment]
Interesting, I see no `.rpy` files in the folder captures. Can you try running the game again?

**Comment by Blizzardsev** [comment]
@RaionArt - can you sanity check in case I've gone code blind here?

**Comment by Drago288** [comment]
so deleting entire game and downloading everything including mod again fixed the issue.Pretty weird tho cuz i swear i didn't had and rpy files and before update i didn't had any errors.thanks for your time tho.

**Comment by RaionArt** [comment]
Glad reinstalling fixed it.
