### ISSUE TITLE
[ BUG REPORT ] - Vacation, and Default theme not playing after picking custom song

### ISSUE THREAD

**Issue by Gamboink** [Just-Natsuki-Team/NatsukiModDev#606]
# Overview:
When I played a custom song and wanted to go back to either Vacation, or Default theme. The music didn't play.

## Replication steps:
Pick any custom music you put in, then play either Vacation or Default

## Additional information:
It started to happen when I updated to v1.1.1

**Comment by RaionArt** [comment]
Hello @Gamboink! 
What system is your computer running on?

**Comment by Blizzardsev** [comment]
This will be resolved in v1.1.2.
