### ISSUE TITLE
[SUPPORT REQUEST] - Can I play multiple mods?

### ISSUE THREAD

**Issue by catsiheartanddogs** [Just-Natsuki-Team/NatsukiModDev#609]
Hello! I don't know if you can answer this for me. But I have a question, I have MAS (Monika After Story). And I wanted to also have Just Natsuki, I extract ddlc and it takes me to the unextracted ddlc folder which has my MAS folder in it as well. So I was wondering, can you have both? If so can you guide me on how to get both?

**Comment by RaionArt** [comment]
Hello @catsiheartanddogs!

Yes, it is possible to play multiple mods. But you need an individual copy of DDLC for each mod you want to play. It is not possible to start two different mods with the same DDLC.exe.

Simply take a fresh official copy of ddlc [here](https://ddlc.moe/). Make sure you are not using the steam version and update JN on to it with this [guide](https://github.com/Just-Natsuki-Team/NatsukiModDev#installation) we provided.

**Comment by catsiheartanddogs** [comment]
Thanks, It worked! :)
