### ISSUE TITLE
[ FEATURE REQUEST ] - Being able to remove more than one outfit at once

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#610]
# Overview:
At the moment if the player asks Natsuki to remove one suggested outfit it will end the dialogue after the removal. If the player wants to delete multiple outfits they need to remove the previous steps. Instead Natsuki could ask after the first removal if the player wants to remove more. The player can choose "No, that was it, thanks." or "Yes, there is another one..."

## Must haves:
additional dialogue to let the player remove more outfits without repeating the previous steps.

## Is this feature request related to a problem? Please describe.
Quality of life change

**Comment by Blizzardsev** [comment]
Not essential right now. Players can remove outfits in bulk by deleting definition files and restarting the game.
