### ISSUE TITLE
[ SUPPORT REQUEST ] - Can I look at my Affection?

### ISSUE THREAD

**Issue by catsiheartanddogs** [Just-Natsuki-Team/NatsukiModDev#612]
Hello, developer(s)! You probably remember me from "Can I play multiple mods?" Which I have another question. Is there any possible way to look at your affection yet? I'm always curious to what my affection could be and what I could do to raise it. So I just wanted to know if there is any way to look at your affection. Thanks!

**Comment by RaionArt** [comment]
Hello again!

Please check our [FAQ](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-view-my-affinityaffection--do-you-plan-on-adding-a-way-to-check-affinityaffection) for these kind of questions.
