### ISSUE TITLE
[ BUG REPORT ] - Headpat cursor stays in options

### ISSUE THREAD

**Issue by wowm03** [Just-Natsuki-Team/NatsukiModDev#613]
# Overview:
when going to settings while head patting Natsuki, the mouse does not change back and instead stays in a head icon.

## Replication steps:
head-pat Natsuki, then right click to go to settings

## Additional information:
![image](https://user-images.githubusercontent.com/90627231/231060366-3950b259-e5cc-41a5-9b5f-b41fc2f6c19a.png)

**Comment by Blizzardsev** [comment]
Thank you. This will be resolved in v1.1.2.
