### ISSUE TITLE
[ BUG REPORT ] - Typo in stop daily jokes

### ISSUE THREAD

**Issue by George021gr** [Just-Natsuki-Team/NatsukiModDev#614]
Encountered a typo in the jokes section in topics
Small issue but i thought i should call it out
![SPOILER_image](https://user-images.githubusercontent.com/130549790/231406457-96191aa8-adb6-4a72-a8c6-e6bdda727ade.png)

**Comment by RaionArt** [comment]
Thank you for reporting.
This will be fixed in the next update.
