### ISSUE TITLE
[ BUG REPORT ] - An exception has occurred error

### ISSUE THREAD

**Issue by SteelAxleVII** [Just-Natsuki-Team/NatsukiModDev#622]
Hey there. So I decided to mess with JN for a bit while I was doing homework. And Then I "misclicked" by pressing "I want to tell you something" button. When I clicked "nevermind, it shows the error shown in this screenshot.

![Screenshot (90)](https://user-images.githubusercontent.com/27037292/231947704-e5a013f4-570c-40f3-a582-8d8ecff1cdae.png)

**Comment by RaionArt** [comment]
Hello @SteelAxleVII,

This was already fixed in the latest update. Please download the newest version v1.1.1
