### ISSUE TITLE
[ BUG REPORT ] - Typo

### ISSUE THREAD

**Issue by wowm03** [Just-Natsuki-Team/NatsukiModDev#623]
# Overview:
lack of space between punctuation and word in the 'i love you more' war.
"Wait... can you hear that? Oh! It's how wrong you are - I love you more, **dummy! You're** only wasting your time, [player]~. I love you waaay more!

## Replication steps:
N/A

## Additional information:
![image](https://user-images.githubusercontent.com/90627231/231968106-4bf6ce79-662e-4966-9612-0443a1bc3c84.png)

**Comment by RaionArt** [comment]
This issue will be fixed in the next update. Thank you for reporting to us!
