### ISSUE TITLE
[ FEATURE REQUEST ] - More poses!

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#635]
# Overview:
With some newly added expression like the `concerned` eyebrows gave us the ability to explore many more new emotion for Natsuki! To compliment that even further we could add new poses! 

## Must haves:
Base arts for three new poses:
-`finger_touching`
-`thinking`
-`finger_pointing`

Also updating all sleeves for already existing outfits and of course adding the code for the main game and the expression previewer!

## Could haves:
We could use the same right sleeves for `thinking` and `finger_pointing`
And adjusting/revisiting previous topics/dialogue.

## Is this feature request related to a problem? Please describe.
New feature

**Comment by RaionArt** [comment]
Might be also worth to take a look at both of the `arms_crossed` as the wrist of the left arm is too thin

**Comment by Blizzardsev** [comment]
@RaionArt if you're comfortable with where this stands, did you want to raise a pull request for it?

**Comment by RaionArt** [comment]
I only finished a fix for all `amrs_crossed ` poses one of the three new poses for now. I feel like as people would need to redraw/draw more sleeves, it would be best to do a pr when all poses are done.
This would also be better, when we want to revisit some topics to include the new poses.

**Comment by RaionArt** [comment]
Will be added in v1.3, still need to update custom clothes

**Comment by Blizzardsev** [comment]
I'll close this off here since we can effectively consider it finished for the main mod, and make an issue for the extras repository
