### ISSUE TITLE
[ FEATURE REQUEST ] - 

### ISSUE THREAD

**Issue by Gamboink** [Just-Natsuki-Team/NatsukiModDev#640]
# Overview:
A Boop Feature, like booping Natsuki on the nose.
(I got the idea from Comet2023#4926 in the server)

## Must haves:
Possibly being at happy state for it to be unlocked

## Could haves:
Possibly could be in extras menu because there's nothing unlocked in the extras menu at happy state, or you can just boop her nose with the mouse.

## Is this feature request related to a problem? Please describe.
there is no problem, just an idea.

**Comment by RaionArt** [comment]
Hello @Gamboink,
such an issue already exists: #480.
We already started working on a feature like this, but the biggest challenge still remains which is a suitable hitbox, that will work in every resolution.
