### ISSUE TITLE
[ BUG REPORT ] - Natsuki gets upset when I call her "Muffin"

### ISSUE THREAD

**Issue by Megalonumber0ne** [Just-Natsuki-Team/NatsukiModDev#641]
# Overview:
Called her muffin, she got sad, despite Raion confirming it's not blacklisted anywhere

## Replication steps:
Just name her Muffin and she'll be angry

## Additional information:
Dialogue said (since I had to do it again, it's a bit different than what it would be normally):
Cookie: "You want to give me a new nickname?"
Cookie: "Alright, [my name]."
Cookie: "E-excuse me?!"
Cookie: "What the hell did you just call me, [my name]?!"
Cookie: "..."
Cookie: "I seriously can't believe you, [my name]. Why would you do that? Are you _trying_ to get on my nerves?!"
Cookie: "..."
Cookie: "I can't believe you did that again to me, [my name]."
Cookie: "I told you it hurts, and you went ahead anyway!"
Cookie: "..."
Cookie: "I... really... like you, [my name]. It hurts extra bad when it's you."
Cookie: "Don't test my patience like this. You're better than that."

Final note: ouch. I can't believe she got mad :(

**Comment by Megalonumber0ne** [comment]
Extra note: when apologising, her dialogue didn't change from last time I had to do it for the report (i backed up my persistents before, thankfully)

**Comment by RaionArt** [comment]
Thank you for raising this issue for us, @Megalonumber0ne! 
This will be fixed in the next update.

**Comment by Megalonumber0ne** [comment]
No problem! Happy I could help out.
