### ISSUE TITLE
[ BUG REPORT ] - Natsuki repeating topics with repeat topics turned off in settings

### ISSUE THREAD

**Issue by riatheddlclover** [Just-Natsuki-Team/NatsukiModDev#642]
# Overview:
[Repeat topics option is always turned off in settings but Natsuki keeps repeating topics.]

## Replication steps:
[Just turning repeat topics off]

## Additional information:
[I have the latest version.]

**Comment by Blizzardsev** [comment]
Hi, can you please tell me what version of JN you are playing? You can find this on the title window, or the settings on the bottom right.

**Comment by Blizzardsev** [comment]
Ignore the above, just spotted you are running the latest version. We'll take a look.

**Comment by RaionArt** [comment]
Hello, could you please send a screenshot of your settings?

**Comment by Blizzardsev** [comment]
Hi - Natsuki is repeating topics because you have Repeat seen enabled: a filled checkbox means the corresponding setting is turned on.

**Comment by riatheddlclover** [comment]
> Hi - Natsuki is repeating topics because you have Repeat seen enabled: a filled checkbox means the corresponding setting is turned on.

But it’s disabled, it’s shown there

**Comment by Blizzardsev** [comment]
If the checkbox is pink, it isn't disabled. Click the checkbox to make it blank. Then it will be disabled.

**Comment by Blizzardsev** [comment]
Closing due to explanation given. The next update will also make checkbox state more obvious.
