### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki Talking About Doki Doki Takeover

### ISSUE THREAD

**Issue by Amazingpotato917** [Just-Natsuki-Team/NatsukiModDev#644]
# Overview:
Natsuki would ask the player if they've heard about the game and would talk about it

## Must haves:
If the player knows about the game she could ask if we liked it and what was the hardest song

## Could haves:
It would be funny if she bragged about how her songs were the better ones, and ask which doki sang our favorite song from the game

**Comment by Blizzardsev** [comment]
Hi @Amazingpotato917, thanks for your suggestion.

Unfortunately, this isn't something I think would be a good fit for the mod: we always try and avoid direct references to other franchises, be it a TV series, movie, game, manga, etc. - the last thing we want or need is for another organisation to disagree with our inclusion of their property, or feel like we're painting their content in a negative light based on dialogue we write.

Like with any series, we also have to account for the following:

- Not everyone will be familiar with DDTO, or FNF for that matter: as it happens, none of the development team have played FNF either: we'd have to play the game ourselves to be able to write anything meaningful, and the interest just isn't there (at least for me).
- Once we include a concrete reference to one franchise, this opens the door to people requesting _their_ favourite franchise being added as a topic/event/item too: this overshadows more meaningful topics, and could come across as favouritism.
- Natsuki should never be seen as a vehicle for the interests of the development team, or any community members: this is something we work hard to avoid already.
- References to pop culture/current trends age _poorly_: we strive for JN to be as timeless as we can make it, and inclusions of things like this can date topics pretty badly. Will people remember DDTO in three years time? Five? Etc.

A better suggestion would be for Natsuki to talk about something more generic that is relatable to far more players - for example, Rhythm games, or music genres.

@RaionArt @Obsidian-Knife thoughts?

**Comment by RaionArt** [comment]
I totally agree what @Blizzardsev said. A topic like this opens a door I would rather keep closed. 
As much as I understand how fun it could be to see crossovers, I fear too many people would ask to include multiple other mods, that perhaps not many people are familiar with.
Common known topics are for sure the way to go.

But I feel like a topic about Rhythm games would be nice compromise to not just shut down this idea.

**Comment by Amazingpotato917** [comment]
Ooo, yeah, I didn't think about it like the way you guys said, I'm sorry about that- But I like your guy's idea 😄

**Comment by RaionArt** [comment]
As the suggestion was declined, I will close this issue, but feel free to open one for rhythm games if you feel like it!
