### ISSUE TITLE
[ BUG REPORT ] - Player's name on birthday

### ISSUE THREAD

**Issue by FastestDan** [Just-Natsuki-Team/NatsukiModDev#647]
# The Bug:
When starting up the mod for the first time I gave myself a name "Kitsurou". After being able to change it, I named myself "Dan".
When Natsuki congratulated me on my birthday, she called my by the name I gave her at the very beginning of playing, not by my nickname. It only happened in her first line of dialogue, after that she continued calling me "Dan".
Is Natsuki supposed to address the player by their name on their birthday, rather than by their nickname?

## The Replication:
1. Having an ability to change your name
2. Change your name to something different
3. Trigger the Player's Birthday event

**Comment by Blizzardsev** [comment]
Hi @FastestDan, thanks for the report.

No, this isn't intentional behaviour - we'll take a look when we can; I already have an idea of the solution.

**Comment by Blizzardsev** [comment]
This will be patched in the next update.
