### ISSUE TITLE
[ FEATURE REQUEST ] - More window reactions

### ISSUE THREAD

**Issue by Megalonumber0ne** [Just-Natsuki-Team/NatsukiModDev#648]
# Overview:
Have Natsuki react to more open windows, such as games!

## Must haves:
Must haves would have to be stuff like websites like eBay, Amazon, MSPaint, Itch.io, Scratch, Minecraft, A Dance Of Fire And Ice

## Could haves:
Newgrounds, Epic Games Store, GTAV, Fortnite, Deltarune, Undertale, Terraria, Channel 4 (for shows and movies)

## Is this feature request related to a problem? Please describe.
It's not, it would just be nice to have more things for Natsuki to react to when playing games or browsing the web

Edit: I forgot to capitalise Natsuki's name 😞 
Second edit: added ADOFAI to the Must Haves

**Comment by RaionArt** [comment]
Hello @Megalonumber0ne and thank you for your addition! 

Overall more window reactions would be something we could look into in the feature, but we wouldn't want to include medias such as games, as people would want to have *their* favourite games represented. So when we add Minecraft, somebody else could ask for wow or fallout and so on...

So more reactions to websites many prople use: Sure! Games: not so much

**Comment by Megalonumber0ne** [comment]
Alright! I was hoping for something like minecraft to be something added (ima be real, I know nobody who dislikes it), but if anything else comes to mind (non-game related), I'll be sure to make another suggestion

**Comment by Blizzardsev** [comment]
Adding to @RaionArt - we'd like to avoid having particular/individual games here if possible. Currently, we stick to things like platforms such as Steam, Origin, Battle.NET and Netflix as they encompass a wide range of activity without having to worry about supporting activity for every new game or thing that pops up: this is mentioned in our writing guide too for clarity.

E-commerce sites are fair; we can also look at adding Paint/Scratch/Itch under the existing relevant categories.
