### ISSUE TITLE
[ FEATURE REQUEST ] - Being able to see past jokes from the Joke Book

### ISSUE THREAD

**Issue by Slothbypoke** [Just-Natsuki-Team/NatsukiModDev#661]
# Overview:
This feature I'm requesting is basically just letting you be able to see past jokes from the Joke Book that Natsuki has said.

## Must haves:
A new option in the Jokes topic. The option could say, "Can you say a Joke that you have said before?"

## Could haves:
Natsuki will have a different response if you keep wanting to hear the same joke twice. The response can be different depending on the joke that you keep asking Natsuki to repeat. For example, "Wow, you must really like this joke [player] if you keep asking me to repeat it." or something like that. (for the different response thing I'm sure that there is another way of saying it but I don't know what it is)

Based on the affinity level with Natuski, the jokes that you asked Natsuki to repeat will have a different response.

This might be kinda hard to do since I don't really know much about ren'py and such but when you click the option to look at the jokes Natsuki has said from the Joke Book before, it will show you the Joke Book allowing you to look inside it and click which Joke you want to hear again, and you can flip the pages via arrows to look for other jokes. (this is just a suggestion but would be cool to add though)

## Is this feature request related to a problem? Please describe.
I actually heard a funny joke from the Joke Book when Natsuki said the joke. I wanted to see what the joke was, then I remembered that there was no way you can see past jokes that Natsuki has said. So that's why I am requesting a feature for it. (P.S. This is my first time making an issue on GitHub, or a Feature Request for the Just Natsuki mod, so please don't be too harsh on me, I still think that this is a good feature that can be added)

**Comment by RaionArt** [comment]
Hello @Slothbypoke and thank you for raising and issue with us!

As the joke book was only introduced in v1.1.1 there aren't only around 30 jokes available at the moment, which means it is most likely that Natsuki will repeat the jokes after a month or so. I feel like a feature you mentioned would work better once we have a bigger repetoire of different jokes!

Another thing we would need to look into is to thinking about how we would like to arrange the different jokes as there would be quite a lot of them and it might not be too user friendly to choose between, let's say, 100 jokes at once.

For the time being I would like to point out you can always click on the `History` button at the bottom of the text font to see the last couple of lines Natsuki just said!

**Comment by Slothbypoke** [comment]
> Hello @Slothbypoke and thank you for raising and issue with us!
> 
> As the joke book was only introduced in v1.1.1 there aren't only around 30 jokes available at the moment, which means it is most likely that Natsuki will repeat the jokes after a month or so. I feel like a feature you mentioned would work better once we have a bigger repetoire of different jokes!
> 
> Another thing we would need to look into is to thinking about how we would like to arrange the different jokes as there would be quite a lot of them and it might not be too user friendly to choose between, let's say, 100 jokes at once.
> 
> For the time being I would like to point out you can always click on the `History` button at the bottom of the text font to see the last couple of lines Natsuki just said!

Hello, thanks for the reply! I don't think I have gotten all the jokes from the Joke Book yet, so I don't think I ever saw any jokes repeated, but I see how it would be a feature once there are more jokes in the Joke Book. I also see how arranging all the jokes that Natsuki has said into a list if there are over 100+ jokes can be a hassle. I can just imagine people scrolling down the list just to find a specific joke they want to hear again. But I would still like to see this feature in a future update or something. Or just add another page to the wiki all about the jokes Natsuki can say. But overall, thank you again for the reply! (I'm still new to the GitHub issue request/Feature request for Just Natsuki, do I close this or just wait?)

**Comment by RaionArt** [comment]
You can keep this issue open and we will revisit it once we have a bigger repertoire of jokes!

**Comment by Slothbypoke** [comment]
I thought of some extra things you can add for the feature.

**Comment by Blizzardsev** [comment]
This will be introduced in v1.3.
