### ISSUE TITLE
[ BUG REPORT ] - Typo found in dialogue

### ISSUE THREAD

**Issue by Megalonumber0ne** [Just-Natsuki-Team/NatsukiModDev#666]
# Overview:
With the LOVE affinity (don't fully know if it's required, pretty sure it is), there's a tpyo if you say that you feel insecure 2 consecutive times

## Replication steps:
Read above

## Additional information:
![image](https://user-images.githubusercontent.com/87905744/235508171-412059b4-bb5a-42d1-91d2-ce66d2e5e9ad.png)

**Comment by RaionArt** [comment]
Hello @Megalonumber0ne and thank you for reporting the typo to us!
This will be fixed in the next update.
