### ISSUE TITLE
[ FEATURE REQUEST ] - Ability to thank Natsuki

### ISSUE THREAD

**Issue by ElsenIsCute** [Just-Natsuki-Team/NatsukiModDev#669]
# Overview:
Simple, sometimes you might be grateful for something that Natsuki did for you, and that's when you want to thank her!

## Must haves:
It can be like the "I'm sorry" menu where it's in "Talk" and has a drop down with a few things to thank her for, like advice, and the like. With a "For something" at the bottom which is more generic.

## Could haves:
Have it be like the "I'm sorry" menu where as random topics or certain things happen, new things get added rather than just having a few default things like "for giving me advice" and the like.

**Comment by RaionArt** [comment]
Hello @ElsenIsCute ,
we already had a similar issue opened only a few days ago. 
In the issue #649 we already explained our stance about it.
Thank you for suggesting an issue though!
