### ISSUE TITLE
[ BUG REPORT ] - Sprinkles disappearing

### ISSUE THREAD

**Issue by LariLit** [Just-Natsuki-Team/NatsukiModDev#674]
# Overview:
[ Sometimes the acessory for her face sprinkles don't show up and sometimes it does ]

## Replication steps:
[ I made an outfit using the acessory for her face, the sprinkles ( the new one available after she talks about the issue on finding clothes her size ). When I save the look it's still there, but when I reopen the game only the sprinkles are not on her face anymore. I tested to see if the one she made, the Pastel goth getup, the sprinkles also disappeared, but it didn't. ]

## Additional information:
[ I don't if it matter but the outfit I made it's basically the same as the Pastel goth getup, I just changed the hair for the double buns.
I'm on Windows 10, I play on windowed mode, I saw the bug on May 3rd and my version is v1.2.0]

**Comment by RaionArt** [comment]
Hello @LariLit and thank you for reporting this bug to us!

After some testing, I discovered this is the same case for the `plaster`, so I would think this seems to be in issue with the `facewear` itself. We will take a look into this.

**Comment by Blizzardsev** [comment]
Hi @LariLit - this will be resolved in v1.2.2.
