### ISSUE TITLE
Slight grammer issue with Vibing Headphones Idle

### ISSUE THREAD

**Issue by Project-Archangel** [Just-Natsuki-Team/NatsukiModDev#675]
Just a slight grammar issue with the vibing headphones idle after the player talks to Natsuki to stop the idle
![Screenshot 2023-05-03 114234](https://user-images.githubusercontent.com/104313945/235992039-dd5673a2-5907-4aaf-ada8-5d4dd7b0bde8.png)

**Comment by RaionArt** [comment]
Thank you @Project-Archangel to bringing this to our attention, this will be improved with the next update.
