### ISSUE TITLE
[ FEATURE REQUEST ] - A confirmation message if the X button/quit is pressed

### ISSUE THREAD

**Issue by Megalonumber0ne** [Just-Natsuki-Team/NatsukiModDev#678]
# Overview:
Give the player a warning before closing the game, just in case there was a mis-click on the player's behalf

## Must haves:
A pop up (similar to MAS), asking the player if they're sure they want to quit without saying goodbye

## Is this feature request related to a problem? Please describe.
It's not related to a bug, but it can be a pretty big issue if you're prone to mis-clicking...

**Comment by Blizzardsev** [comment]
Hi @Megalonumber0ne - I wouldn't personally think this is necessary. Unless the player is in one of the in-game menu screens (in which case we ignore the quit action unless the action is repeated quickly several times, which is OS controlled), the player will either go through the first force quit dialogue (which incurs no penalty), or Natsuki will prompt them not to force quit with additional dialogue.

We had a prompt as MAS did a long time ago, and switched to the current solution as the prompt felt clunky, and we could give Natsuki much more personality without her response to the player quitting being tied to a small textbox with no reactions, etc.

**Comment by Blizzardsev** [comment]
@RaionArt thoughts?

**Comment by Megalonumber0ne** [comment]
That's understandable, I just wouldn't want to press the close window button on accident is all
Thank you for your feedback!

**Comment by RaionArt** [comment]
I feel like adding a pop up menu for it would hurt the immersion and in general we try to avoid stuff like that. 
Also being aware to not force quit in JN, which you could normally do with other games/programs, adds to the experience of JN imo.
