### ISSUE TITLE
[ FEATURE REQUEST ] - Star for new topics

### ISSUE THREAD

**Issue by gorillagrip** [Just-Natsuki-Team/NatsukiModDev#679]
Just a simple little yellow star at the top right of each box for new topics or otherwise haven't chosen yet. Could extend into their higher categories to indicate that the player unlocked a topic.

**Comment by RaionArt** [comment]
Hello @gorillagrip and thank you for your suggestion,
There already is an indicator for new topic as they are written in the italic font, but I agree this could be made more obvious with a little star.

**Comment by gorillagrip** [comment]
> Hello @gorillagrip and thank you for your suggestion, There already is an indicator for new topic as they are written in the italic font, but I agree this could be made more obvious with a little star.

Oh, they're in italics? I've just been eyeing stuff for the most part. I have her in half of the resolution she's intended to be viewed in so I can do other stuff while I wait for her to think of stuff, so I never noticed that.

**Comment by RaionArt** [comment]
No worries! Like I said I feel like a little star could improve the clearification anyway.

**Comment by RaionArt** [comment]
This will be introduced in v1.2.2
