### ISSUE TITLE
[ FEATURE REQUEST ] - Reduce "repeat topics" question

### ISSUE THREAD

**Issue by ashyashton** [Just-Natsuki-Team/NatsukiModDev#680]
Whenever Natsuki runs out of topics, she has dialogue mentioning this and asking the player if they want to enable repeat topics. This is great for when you run out of dialogue, but currently, it's a daily thing because of the joke book. The joke seems to register as a new topic, so once it's said, the game seems to register that as Natsuki running out of topics again. Thus, she brings up the not-very-short "out of dialogue" dialogue for the umpteenth time, including asking if the player wants her to repeat herself.

I think there are two ways to fix this. One would be to somehow not have jokes register as new topics in the first place, so you don't get the "out of dialogue" dialogue. The other would be to not have Natsuki ask about repeating topics every time, and instead have her ask about them the first time followed by her telling the player that if they change their mind, there's an option in settings to re-enable it. After that, her "out of dialogue" dialogue could just be a very short one, maybe two lines, so that we can move on quickly.

Honestly, I personally think _both_ solutions should be implemented, as they'd both be good QOL improvements, but that's just my opinion.

**Comment by RaionArt** [comment]
Hello @ashyashton and thank you for raising an issue with us!

Normally Natsuki should only bring up the question if the player is fine with repetetive topics once. To have her keep repeating it every day after reading out a joke is not intentional behaviour. 
We will look into it, thank you for reporting this!

**Comment by RaionArt** [comment]
This will be introduced in v1.2.2.
