### ISSUE TITLE
.rpy files problem

### ISSUE THREAD

**Issue by PTLD93** [Just-Natsuki-Team/NatsukiModDev#683]
Ive been playing the game for a few weeks now,but theres this little message on the top left of my screen saying "You are running source (.rpy) files! Unless you know what your doing,Please switch to release files."

whats the solution i gotta do here?

**Comment by RaionArt** [comment]
Hello @PTLD93,

like the game says you downloaded and use the source files. When updating the game you only need to download the jn.zip (a.e. `jn-1.2.1.zip` at the moment) as we also always mention in our update and install guides.

You would want to delete all source files (the one ending with .rpy) and reinstall the mod with the intended way I just discribed. Make sure to backup your persistent file. If you need more support we also have this question listed in our [FAQ](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#why-is-my-game-warning-me-about-running-source-rpy-files).

I hope I could help you.

**Comment by Blizzardsev** [comment]
Closing due to explanation given.
