### ISSUE TITLE
[ FEATURE REQUEST ] - I made some dialogue to be reviewed

### ISSUE THREAD

**Issue by Megalonumber0ne** [Just-Natsuki-Team/NatsukiModDev#684]
# Overview:
Made one farewell and one greeting
Greeting:

`# Natsuki getting caught off guard by the player (again)`
`init 5 python:`
`    registerTopic(`
`        Topic(`
`            persistent._greeting_database,`
`            label="natsu_startle_greeting",`
`            unlocked=True,`
`                affinity_range=(jn_affinity.LOVE, None),`
`                ),`
`            topic_group=TOPIC_TYPE_GREETING`
`            )`

`label natsu_startle_greeting:`
`    n 1kcsunl "..."`
`    n 1kwmunleqm "...?"`
`    n 1kskemleex "A-ah!"`
`    n 1kwmssleaf "[player_initial]-{w=0.1}[player]!,{w=1}{nw}"`
`    extend 1uchssl " I'm so glad to see you again..."`
`    n 2kslajl "Y-you scared me..{w=0.5}{nw}"`
`    extend 1kwmajl " It doesn't matter. What would you like to talk about, [chosen_endearment]?"`

`    return`

Farewell:

`# Natsuki wishes the player a nice rest of their day`
`init 5 python:`
`    registerTopic(`
`        Topic(`
`            persistent._farewell_database,`
`            label="natsu_nice_rest_of_the_day_farewell",`
`            unlocked=True,`
`                conditional="store.jn_get_current_hour() >= 18 or store.jn_get_current_hour() <= 0",`
`                ),`
`            topic_group=TOPIC_TYPE_FAREWELL`
`            )`

`label natsu_nice_rest_of_the_day_farewell:`
`    n 2kllajl "Oh, you're heading out, [player]?"`
`    n 1ksgssl "That's alright... {w=0.6}{nw}"`
`    extend 1nwmssl " Have a nice rest of your day, [player]."`
`    if Natsuki.isLove(higher=True):`
`        n 3uchbgl "I love you, [chosen_endearment]!"`
`        n 2uchbgleaf "I'll catch you later!"`
`    else:`
`        n 3uchsml "Stay safe!"`
`    return { "quit": None }`

Edit: code blocks weren't working correctly
Final edit: tried to make the code blocks work

**Comment by Blizzardsev** [comment]
Hi @Megalonumber0ne - if you are looking to introduce code you have written and tested personally, could you please submit this as an MR using your own fork of JN? We can then go through the proper code review process as we would with an official MR.

**Comment by Megalonumber0ne** [comment]
What does MR mean?

**Comment by RaionArt** [comment]
Merge Request
