### ISSUE TITLE
[ FEATURE REQUEST ] - i think what would be good for the mod

### ISSUE THREAD

**Issue by WilliamRocks2** [Just-Natsuki-Team/NatsukiModDev#693]
i think what the next update should have is similar to MAS where when you reach max affection you can give natsuki a ring, probably also more questions to ask her too

**Comment by RaionArt** [comment]
Hello @WilliamRocks2,

we only handle one suggestion per issue to document it better. Also your title doesn't give any idea what you are talking about.
If you want to share any suggstions please open an issue for each with an actual title relating to it and a **detailed** description what you would like to see. Simply adding more "questions" would happen one way or another anyway, so please write down if you have anything in mind particular.
