### ISSUE TITLE
[ FEATURE REQUEST ] - Greeting, farewell mini-expansion

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#696]
# Overview:
Currently, we have a decent range of new greetings and farewells: however, over time these can feel stale - particularly to long-time players, or those still working on a certain affinity.

We can expand these a little to add a bit more variety and freshness when booting up the mod and saying goodbye to Natsuki.

It should be noted this is aimed to be introduced in the upcoming 1.2 patch, so should be limited in scope and not include any large, sweeping/complicated items: added greetings/farewells should be relatively simple in nature (no complex dialogue trees).

## Must haves:
- One new greeting for each tier
- One new farewell for each tier

## Could haves:
- Additional greetings as appropriate
- Additional farewells as appropriate

## Is this feature request related to a problem? Please describe.
This is related to the existing greeting/farewell functionality.

**Comment by RaionArt** [comment]
Is featured in the new version v1.2.2.
