### ISSUE TITLE
[ BUG REPORT ] - "Nastya" picked up as an insult for nicknames

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#697]
# Overview:
The name "Nastya" is being picked up as an insult by Natsuki when it is a legitimate name choice for a player.

## Replication steps:
- Choose "Nastya" as your name when starting the game, or requesting a name change

## Additional information:
N/A

**Comment by RaionArt** [comment]
Will be fixed in v1.2.2.
