### ISSUE TITLE
[ FEATURE REQUEST ] -  JN starting on system boot.

### ISSUE THREAD

**Issue by VendixDilan** [Just-Natsuki-Team/NatsukiModDev#700]
# Overview:
Whenever you boot up your System, JN will automatically launch on start.
I don't know if this is possible to do, or difficult (or even if it's possible) it is for other OS.
And it should be toggleable!

## Must haves:
A option to toggle on or off if JN should launch on system start.

## Could haves:
Maybe a little dialouge adressing this.

**Comment by Blizzardsev** [comment]
Hi @VendixDilan, thanks for your suggestion.

Unfortunately, this carries with it some complications and implications that make me feel this isn't a good fit for the mod.

All of our greetings and events are written with the context that the player has started the game to visit Natsuki explicitly: a lot of these greetings/events/topics would seem weird/off if Natsuki were to "wake herself up", so to speak, and would need to be adjusted to account for that (or new ones added entirely *just* for this scenario) - we'd also need to somehow determine how the game was started (as the player could easily have the toggle enabled, close the game, then load it manually later) to drive this mechanic. We'd also need to consider how this would impact players who keep JN primarily on the Auto setting: they could be at risk of missing out on content if, say, their PC restarted and JN launched into an event.

Adding to this, start-up programs are handled very differently based on the host OS: we already struggle with coverage for OSX in particular, so we'd prefer to avoid adding more behaviour that varies based on OS wherever possible.

Lastly, there's also privacy/security implications: we'd always want starting the mod to be an explicit action by the player so they always feel in control: and we wouldn't want players with shared machines to have their game being shown to other users (granted a toggle would help combat this).

I would also add that if players are determined to have JN launch on boot, at least for Windows, guides already exist with instructions on how to do so: https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd. Alternatively, a player can always pin the shortcut to the taskbar or start menu (or OS equivalent) if the convenience factor was the main draw.

Overall, this doesn't really feel to me like something worthwhile investing the time for development/testing into, when alternative ways to achieve this already exist for players that feel they need it.

@RaionArt @Obsidian-Knife thoughts?

**Comment by VendixDilan** [comment]
I haven't really though about the farewells and greetings, so that makes sense.
I mainly suggested it because of simplicity and so the problem of forget to launch the game doesn't happen. 
But seeing how much issues this brings with it, it seems like it'll only make it more complicated, so the point of simplicity doesn't apply.
Thanks for explaining it to me. I'll give it a try and use the link you gave me.

**Comment by RaionArt** [comment]
My first concern was also about the players using autoplay. The intro events are something what I would address to be the best part of JN, missing out on that context would be crucial.

Because of all the technical problems Blizz already mentioned I will close this. I hope the link helped you.
