### ISSUE TITLE
[ FEATURE REQUEST ] - Remind me about repeating topics

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#706]
# Overview:
With the new update in v1.2.2  player can chose to tell Natsuki to stop reminding them, when she runs out of topics to say, so she won't repeat the warning every time it happens. We could add a new topic to tell Natsuki it is fine to remind them again if the player told her to stop previously. 

## Must haves:
New topic to let her remind the player again.

## Is this feature request related to a problem? Please describe.
More of an extension.

**Comment by Blizzardsev** [comment]
This will be added in v1.3.
