### ISSUE TITLE
[ BUG REPORT ] - game isnt working

### ISSUE THREAD

**Issue by JADENLO** [Just-Natsuki-Team/NatsukiModDev#708]
everytime i tried to open the game this pops up 
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/106132370/99d2808b-ca98-433a-8beb-424c47f4e573)
why is this happening
if the image doesnt work the error says : A Problem has occurred. Please contact JN staff

**Comment by RaionArt** [comment]
Hello @JADENLO,

can you please describe your problem more? When did it start appearing? Also please send in your log (from inside of the log folder).

**Comment by Blizzardsev** [comment]
Hi @JADENLO - please also send your persistent for evaluation. You will need to send it inside a ZIP folder so GitHub allows you to attach it to a comment.

**Comment by Blizzardsev** [comment]
Information on how to locate your persistent can be found here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent

**Comment by JADENLO** [comment]
I fixed it when i was gonna send you it i forgot i deleted it so i opened the game up and it works now 
sorry to waste your time
