### ISSUE TITLE
[ FEATURE REQUEST ] - Entry Dialogue apology (Player interupts Natsuki's game)

### ISSUE THREAD

**Issue by Ionlylike1kindofcheese** [Just-Natsuki-Team/NatsukiModDev#712]
# Overview:
There's this entry dialogue where Natsuki is playing a game heavily focussed until the player enters without knocking and therefore interrupts her causing her to lose her game. 
Normal course of action would be to tell her you're sorry.
However when you go to "I want to say sorry..." section after the dialogue, there ain't really a button to even apologize regarding the entry dialogue which is odd tbh.

## Must haves:
A way to follow-up for when you interupt Natsuki's game which allows you to apologize.

## Could haves:
- A button in the "I want to say sorry..." section which allows the player to apologize after the dialogue has ended.
or
- An adjustment to the dialogue itself where Natsuki tells the player in some way that she forgives the player.
or
- A new dialogue which plays after this entry dialogue has played for the first time.

## Is this feature request related to a problem? Please describe.
No, it's just some honest feedback.

**Comment by Blizzardsev** [comment]
I can see where you're coming from, but I'd question how much utility this would see - and whether the situation really warrants an apology in the first place!

It's worth noting that apologies are intended for making up to Natsuki for a situation that can happen repeatedly: while this doesn't mean we can't add one for this, we'd ideally want any apology to be capable of being seen more than once to get the most bang for our buck out of the writing investment. Remember, non-holiday events are a one-time only affair: all players can experience each event once, but players who have experienced it in the past would be missing out on that! (It would seem odd to apologize for an event that we have no record of when it happened).

I'd also note that Natsuki isn't _actually_ upset when the event concludes! She's irked, but the ending of the event has Natsuki quickly bounce back by expecting you'll make up for that by having extra fun with her together instead! (So we can end on a high note before going into the regular game):

```
"...And now I gotta do that all over again? Man..."
"..."
"I guess I'll just do that later."
"Again."

(Natsuki tidies away her Twitch)

"..."
"Well, [player]."
"I hope you're buckled up."
"...'Cause now you owe me twice as much fun today to make up for that."
"..."
"Well? Get to it then, [player]!"
"Ehehe."
```

Overall I wouldn't call it a hard no, but it'd be an odd thing to add to the current roster: and given the circumstance that would make this apology available, it'd be lower in our priorities to work on.

@RaionArt @Obsidian-Knife thoughts?

**Comment by RaionArt** [comment]
I don't think it is necessary to add an apology for this event, but maybe we could make it even clearer in the dialogue that Natsuki is not *actually* mad about the interruption?

**Comment by Blizzardsev** [comment]
@RaionArt That seems like a fair compromise.

**Comment by Blizzardsev** [comment]
We've decided to go with an adjustment to the original event - this will be introduced in v1.3.
