### ISSUE TITLE
[ FEATURE REQUEST ] - More options for the Player.

### ISSUE THREAD

**Issue by VendixDilan** [Just-Natsuki-Team/NatsukiModDev#720]
# Overview:
I notice that Natsuki knows very little about the actual player. Which makes her feel a lot more disconnected to us.
She knows our birthday, name and location (_if you choose to tell her, that is_).

So, I thought that by topics like "Do you drink alcohol?", that Natsuki would ask the player if _they_ do or don't do.
This can also be used for later conversations, for example:
"Do you like Parties?", Natsuki could recall on what the player choose.

Something like "I remember you saying X.", that way it feels like Natsuki actually knows stuff about the player.
But it must be simple _yes_ and _no_ questions. So something like "What's your favorite Animal?" obviously doesn't work.

## Must haves:
A dialouge option/menu option for the player to choose from.

## Could haves:
Maybe with some dialogue, re-write it a little so a question can be asked.

**Comment by Blizzardsev** [comment]
Good news! This is actually something we're looking to address already: while newer topics (such as our artwork or preference on hot drinks) offer more interaction with the player in the way you described, it's definitely something the team have noticed (among a few other problems!) in our older topics!

The only things I would say is that it's always good to remember a couple of points:
- We always want to try and keep responses neutral in terms of language, and avoid giving the player a voice they don't have
- We want to try and have options feel productive!

I'll be closing this topic down as we'd already be covering the points of concern in #548 , but I'll make sure this particular aspect is made more clear as a point to address.

As a side note (spoiler warning), you might be interested to know Natsuki also gets a chance to learn the following!
- The player's current pet
- The player's favourite season
- The player's appearance:
    - Hair colour, length
    - Eye colour
    - Height
 - Whether the player is multilingual
 - How often the player games
 - If the player is into cars
 - If the player can drive
 - If the player has flown anywhere
 - The player's tea/coffee preference
 - If the player wore any uniform at school, or has to wear uniform now
 - If the player draws regularly/has drawn before/at all
(and probably a few more I've missed!)

Thanks for your suggestion!
