### ISSUE TITLE
[ FEATURE REQUEST ] - Blackjack!

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#721]
# Overview:
Currently, JN only features a single game in the form of Snap. While this has some re-playability and is a popular feature, recent polling has indicated players would like to see more games they can play with Natsuki!

With Blackjack, we can introduce a game requiring a little more reading up from Natsuki (as she isn't familiar with card games, as she admits) that makes use of pre-existing assets that is engaging and easy to learn for our players, while remaining within the bounds of the engine we have to work with. In addition, Blackjack is also a more fitting game for players that struggle with reaction times, and may be struggling with Snap.

Most importantly, Blackjack can be played with only the player and Natsuki!

## Must haves:
- Blackjack as a replayable card game, available as a topic similarly to Snap
- An introduction sequence for Blackjack, perhaps involving Natsuki reading up on more card games
- Scorekeeping, dialogue and reactions as per Snap, to keep the gameplay engaging

## Could haves:
- Persistent bets/chips across sessions, so the player can continue where they left off
- Difficulty scaling, where Natsuki's bets become better, or Natsuki becomes less risky/more thoughtful with her decisions on Hit/Stand

## Is this feature request related to a problem? Please describe.
This is a new feature, but should make use of existing assets/code from Snap where it makes sense

**Comment by Blizzardsev** [comment]
@RaionArt @Obsidian-Knife @dankoismad Thoughts? I wouldn't mind giving this a shot!

**Comment by dankoismad** [comment]
Ooh that was always a favorite casino game of mine. Sounds good to me!

**Comment by RaionArt** [comment]
I like the idea and additional games would be always nice to see.

Would it be worth to add some kind of new book prop, which features new card games to learn? Or perhaps a prop for a package of cards, which we could also add for snap?

**Comment by Blizzardsev** [comment]
> I like the idea and additional games would be always nice to see.
> 
> Would it be worth to add some kind of new book prop, which features new card games to learn? Or perhaps a prop for a package of cards, which we could also add for snap?

A prop would be good, yes - alternatively we could have Natsuki use her laptop if that asset has been completed.

I could see the card pack being nice for some polish too.

**Comment by Blizzardsev** [comment]
This will be introduced in v1.3
