### ISSUE TITLE
[ ART REQUEST ] - Golden necklace version without turtleneck needed

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#725]
# Context:
At the moment the `golden_necklace` is meant to be used with the whole `plaid_chocolate_outfit`. When players try to use the necklace without the turtleneck, the necklace is floating and cut. We should provide another version which allows the player to combine the necklace with any other outfit too.

## Assets needed:
- new art assets
- code declaration for the new version
- needs to be unlocked alongside the `plaid_chocolate_outfit`

**Comment by Blizzardsev** [comment]
Makes sense! Should be a nice easy addition code-wise for some extra QoL.

**Comment by Blizzardsev** [comment]
Code portion is already set up, just needs asset(s)

**Comment by Blizzardsev** [comment]
This will be introduced in v1.3.
