### ISSUE TITLE
[ FEATURE REQUEST ] - Potted plant intro event

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#729]
# Overview:
As we introduced desk items, we should take more use of it! Once the player opens JN they have a chance to see Natsuki taking care of a plotted plant, preferably a cactus, the most tsundere of all plants! Natsuki could've found the plant on her teacher's desk, furthermore a cactus would be easier to take care of than other plants, which also justifies why it didn't wither before.

## Must haves:
-writing of the intro event
-The potted plant as prop

## Could haves:
- random chance to see Natsuki having the plant on her desk after entering with a unique greeting (like Nat mentions she was just caring for the plant)
- have the plant in the background, on the window ledge if she is not caring for it at the moment
- give the plant a name
- Pot of the plant could've a "Izu" logo to reference the Japanese cactus park
- mentions the cactus in the pet topic

## Is this feature request related to a problem? Please describe.
New intro!

**Comment by Blizzardsev** [comment]
This will be introduced in v1.3
