### ISSUE TITLE
her birthday is today but no birthday update????[ BUG REPORT ] - 

### ISSUE THREAD

**Issue by kaydenkimkim** [Just-Natsuki-Team/NatsukiModDev#737]
# Overview:
[brief description of the bug, and the impact created]

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by RaionArt** [comment]
Hello, 

we consider Natsuki's birthday to be the first day of May and we did release a birthday update for it as you can see [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/releases/tag/v1.2.0).
