### ISSUE TITLE
[ BUG REPORT ] - Why does my jn log apperars that Affinity blocked-CN!

### ISSUE THREAD

**Issue by pocenko** [Just-Natsuki-Team/NatsukiModDev#738]
# Overview:
[brief description of the bug, and the impact created]

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by pocenko** [comment]
I really cant see why

**Comment by Blizzardsev** [comment]
Please see the FAQ: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#my-log-says-affinity-is-blocked-what-do-i-do
