### ISSUE TITLE
Natsuki Not Recognizing Clothing

### ISSUE THREAD

**Issue by BananaQuack98632** [Just-Natsuki-Team/NatsukiModDev#739]
# Overview:
There have been many times where I have given Natsuki an outfit or accessory and she doesn't recognize it. She has only once recognized an outfit as a gift, but other times it shows up in-game with no reaction to the gift itself,

## Replication steps:
Give Natsuki an outfit or accessory in the appropriate folders. The outfit shows up and can be accessed but it is not recognized by Natsuki as a gift.

**Comment by RaionArt** [comment]
Can you please also confirm you put all of the outfits folder content to the main game folder and are **not** putting each part of it in the appropriate folders individually?

**Comment by RaionArt** [comment]
Gotta close this because of inactivity.
Feel free to reopen after answering the questions from above.
