### ISSUE TITLE
How do i get Natsuki to play snap with me again?

### ISSUE THREAD

**Issue by Kitsuism** [Just-Natsuki-Team/NatsukiModDev#742]
I played snap with Natsuki half an hour ago, and i want to play more with her, but telling her i'm bored like how i did at first just makes her tell me to go outside or play games
There's also nothing in the extras menu

**Comment by RaionArt** [comment]
Hello, 
you can play with Natsuki again by talking.
`I want to talk about...` > `Games` > `Do you want to play Snap?`
For questions like these you can always check our wiki too!

**Comment by Blizzardsev** [comment]
Closing due to explanation given. I've noticed the wiki doesn't point out where the option is found, so we'll update that too.

**Comment by Blizzardsev** [comment]
Wiki updated in light of this.
