### ISSUE TITLE
[ BUG REPORT ] - Natsuki saying I'm rude for naming the new outfit "Demon Realm Outfit"

### ISSUE THREAD

**Issue by Amazingpotato917** [Just-Natsuki-Team/NatsukiModDev#743]
# Overview:
So I installed the outfit, gifted it to her, then I tried naming it "Demon Realm Outfit" and she called me rude-

**Comment by Blizzardsev** [comment]
Thanks. We've identified the source of the issue and will update soon.

**Comment by Blizzardsev** [comment]
This will be resolved in v1.2.3.

**Comment by Blizzardsev** [comment]
Hi @Amazingpotato917 - v1.2.3 has just been released; you will be able to use this outfit name once you have updated your installation.
