### ISSUE TITLE
[ SUPPORT REQUEST ] - "A problem has occurred. Please contact JN staff."

### ISSUE THREAD

**Issue by menherahime** [Just-Natsuki-Team/NatsukiModDev#752]
my natsuki mod broke, it said "A problem has occurred, please contact JN staff" what should I do?, if I deleted presistent file my natsuki will be reset.. it broke after I say goodbye to natsuki

**Comment by menherahime** [comment]
[Uploading log and persistent.zip…]()

**Comment by RaionArt** [comment]
Hello @menherahime,
please send your persistent forward so we can look into it. You will need to attach it here inside a zip archive so GitHub will allow it to be uploaded. Additionally please send your log file from the log folder as well.

**Comment by menherahime** [comment]
https://drive.google.com/file/d/1yRk6I74yyVjSB6M3YJIvPyJnEJMXoECR/view?usp=drivesdk idk how to upload it in github since im using phone rn, is this okay?

**Comment by menherahime** [comment]
Im sorry, I already set it to public now

**Comment by Blizzardsev** [comment]
Hi @menherahime - thanks for sending over your persistent and log. Your persistent and log data indicates unusual values associated with affinity; I.E cheating. For example, I can see that your cap went from the usual value of 5 from a new game up to **1000+**, which is not attainable during normal gameplay:

![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/57731669/03824639-040a-4c39-bec4-a1fce01b6b9b)
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/57731669/cf60a35c-42c5-4698-9514-3631b589dfeb)

As per our [terms](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#i-want-to-modifyhave-already-modified-my-installation-can-you-help-me-if-something-goes-wrong) on cheating, this issue will be closed and we are making the decision to withdraw your right to support.

You may opt to restart if you wish, but will not be eligible from any further assistance from the JN team.

Thanks!
