### ISSUE TITLE
[ SUPPORT REQUEST ] - Persistent file transport and convert issue

### ISSUE THREAD

**Issue by AKThompson47** [Just-Natsuki-Team/NatsukiModDev#753]
# Overview:
so, now what? was trying to backup "persistent" from a different device but when pasted like this. suki still acts like i just met her lol.

![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/108931894/7901e2c4-ef46-47fc-a308-1ffad829fd4a)

**Comment by Blizzardsev** [comment]
Hi - `persistent` must be copied as-is from your existing installation without renaming it or adding any file extensions. The game engine looks for a file named just `persistent` specifically, and if it cannot find that it will default to restarting, creating a new save file in the process.

In this case, `persistent.py` and `persistent.pyo` are not valid file names. Delete these and the newly created persistent, then copy in your original persistent *exactly as it is* without renaming or modifying it.

**Comment by Blizzardsev** [comment]
I would also add the files you have copied in appear to be from the game engine's source code itself and not your actual save file. Please see the wiki article on locating your persistent here: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent

**Comment by AKThompson47** [comment]
[weirdafpersistentfile.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/11845759/weirdafpersistentfile.zip)

last backup of my previous device persistent file.
