### ISSUE TITLE
[ ART REQUEST ] - Plant care book for more idles

### ISSUE THREAD

**Issue by Blizzardsev** [Just-Natsuki-Team/NatsukiModDev#755]
# Context:
With the new content around Sanjo on the horizon, this opens up the possibility of creating a new idle involving him! As part of this, a new book-based prop for plant care would be a great way to show off how Nat is trying to learn more about her new friend.

This would tie into #677.

## Assets needed:
- A new book-based prop in line with the existing book props, focused around plant care. It would be great to have themes around green, cream and other bright colours to contrast against Natsuki's existing collection and bring out the nature-based aspect of the book.

## Caveats:
N/A

## Notes:
N/A

**Comment by RaionArt** [comment]
Besides a book I think we should add a small watering can as well.

**Comment by Blizzardsev** [comment]
> Besides a book I think we should add a small watering can as well.

Sure! Since we have three slots then so long as it's positioned on the right, then that'll work since we clear it away afterwards.

If we're going to have a little can, perhaps a few sachets of plant food clustered next to it would be an idea too? (Included with the can as a single item)

**Comment by RaionArt** [comment]
Will be introduced in v1.3.
