### ISSUE TITLE
[ FEATURE REQUEST ] - Card house intro event

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#756]
# Overview:
Natsuki is bored and built with her cards a card house. When the player enters, the card hourse collapse which results into Natsuki being upset.

## Must haves:
- writing for the intro event
- art props from the scattered cards
- already existing `card_pack` is laying around
- give the player the possiblity to apologize afterwards or within the event

## Could haves:
- maybe a build card house that is shown for just a second before collapsing
  - if we decide to add this we could include the card house prop for an idle as well.

**Comment by Blizzardsev** [comment]
This sounds like a fun one to do! I'd be up to work on it for sure!

**Comment by Blizzardsev** [comment]
@RaionArt This is just awaiting some art assets now.

**Comment by Blizzardsev** [comment]
Will be added in v1.3
