### ISSUE TITLE
[ BUG REPORT ] - text not showing when im click talk and lets talk about theres no text like romance family but im can click it maybe im just screwed up with installation but im dont think so (and sorry for my english)

### ISSUE THREAD

**Issue by GrayWolfPl** [Just-Natsuki-Team/NatsukiModDev#758]
# Overview:
[brief description of the bug, and the impact created]

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by RaionArt** [comment]
I'm gonna close this because of inactivity, feel free to open it again once you are able to provide a screenshot and a description in more detail.
