### ISSUE TITLE
[ BUG REPORT ] - Affinity+ missing in log

### ISSUE THREAD

**Issue by silvertiz** [Just-Natsuki-Team/NatsukiModDev#759]
# Overview:
[The affection+ command in the log doesn't show up. Idk if it is a problem in the logs or in the game but i don't think i want to spend time talking to her for nothing]

## Replication steps:
[I usually just do the normal thing, i talk to her and don't see the affection+ being logged]

## Additional information:
[Windows 10 as my operating system, this happened first at the 27th of june 2023]

**Comment by RaionArt** [comment]
I'll close this because of inactivity and I assume the log needed to load longer to show the affinity+.

**Comment by silvertiz** [comment]
Yeah it worked eventually, i got affection but only from her asking me stuff not that i initiated conversation. Unsure if it's intentional that i can't ask the same questions over and over and still get affection. If i'm wrong then please correct me
