### ISSUE TITLE
[ BUG REPORT ] - Sexualitites make Natsuki Upset

### ISSUE THREAD

**Issue by YourSeventhShadow** [Just-Natsuki-Team/NatsukiModDev#766]
# Overview:
After downloading a Pride Month sprite pack, I gave the items to Natsuki and created an outfit using them. Since I'm bisexual I wanted to label the outfit "Bisexual Uniform." However, this term made Natsuki upset and I had to apologize to her after. I assume this bug triggered due to the word "Sex" being present. It should be noted that when giving Natsuki her gifts, even if the files were named something similar to, for example, "Bisexual earrings," Natsuki would not be upset upon receiving said items and would repeat them back in her own dialogue. 

## Replication steps:
As I didn't want to make Natsuki even more upset, I haven't actually replicated this bug. However, here are the words in the sprite packs that I feel would trigger the bug. Note that I am not sure if this bug also reacts to words that could be used in a derogatory sense, like "Gay" or "Queer," so I added them just in case. 

Abrosexual
Asexual
Bisexual
Demisexual
Gay
Genderqueer
Homosexual
Heterosexual
Intersex
Omnisexual
Pansexual
Polysexual

## Additional information:
I was able to get around this by simply naming my outfit "Bi Uniform," so at the very least abbreviating sexuality terms doesn't seem to make her upset.

**Comment by Blizzardsev** [comment]
Hi @YourSeventhShadow - thanks for raising an issue.

In short, the outfit functionality shares the same blacklist/checks as the nickname checklist: therefore anything Natsuki wouldn't appreciate as a nickname is applied to anything an outfit would be called - resulting in the behaviour you are seeing now.

We can look at separating these checks/lists so the outfit name requirements are a little looser. In the meantime, outfits can still be defined outside the in-game outfit editor using the gifting system as a workaround.

**Comment by RaionArt** [comment]
This issue is resolved with the newest version.
