### ISSUE TITLE
[ SMALL CHANGE ] - Natsuki no longer being dumb during SNAP 

### ISSUE THREAD

**Issue by ElsenIsCute** [Just-Natsuki-Team/NatsukiModDev#767]
Alright, so, during Snap, there's a small issue with Natsuki's dialog. There are some times where she'll call me dumb for calling Snap wrongly, and then afterwards when it's her turn she calls a wrong Snap on the same wrong card. You could fix this easily by having it so that she's guaranteed to place a card on her turn if you call Snap wrongly.

**Comment by Blizzardsev** [comment]
We'll look into it.
