### ISSUE TITLE
[ SUPPORT REQUEST ] - I want to ask where is the textor the script in JN

### ISSUE THREAD

**Issue by pocenko** [Just-Natsuki-Team/NatsukiModDev#768]
I am tryin to make a translation of JN to translate it into Chinese.but I can't find out the script part in JN'file.Could u tell me pls？
thanks alot

**Comment by Blizzardsev** [comment]
Hi @pocenko - just to be clear, if you wish to modify JN for your own purposes that is fine, but please bear in mind the terms of our [licence and guidelines](https://github.com/Just-Natsuki-Team/NatsukiModDev/blob/master/LICENSE.md#overview). In particular:

- **You must be absolutely explicit that your work is not affiliated with the official mod effort.**
- **You must credit the original mod effort.**

To answer your question: we do not have a script in the way you describe. Everything we do is straight to code, so if you are adamant on working on your own translation then you will need to work with the individual files as we do.

Please also note that JN is currently undergoing a rewrite of the majority of conversation topics as documented in #548, so unless you are prepared to rewrite as those progress then you would be best advised to wait.

I must stress that like all submodding (and translations) currently, this is **not** something the JN team are prepared to offer support with: this would include any users that decide to play your translation.

**Comment by pocenko** [comment]
oh I see .thanks for ur patience.

**Comment by RaionArt** [comment]
I have nothing to add, I'll close this to the explanation given above.
