### ISSUE TITLE
[ BUG REPORT ] - Crash when running JN and tabbing out alongside Wallpaper Engine

### ISSUE THREAD

**Issue by Hardwaresss** [Just-Natsuki-Team/NatsukiModDev#769]
# Overview:
Recently installed the mod for the first time on a new installation of DDLC, whenever I tab out it crashes.

## Replication steps:
Be on a copy of DDLC with the JN mod installed and tab out.

## Additional information:
On windows 10, made sure my operating system is fully updated.

**Comment by Blizzardsev** [comment]
Hi @Hardwaresss, unfortuantely I don't seem to be able to replicate your issue, also on Windows 10. Can you please provide the following information:

- Your system specs
- Whether you are running JN in windowed mode, or fullscreen
- Whether you are using a Steam installation, and/or using any mod management software or other custom modifications to JN
- The scenario in which you are tabbing out; I.E when doing nothing with Natsuki, when in a conversation, when the main menu is open, etc.

**Comment by Hardwaresss** [comment]
Hi! Sorry I didn't specify that, was in a rush to send the first report since I had to go some where.

1.
Processor AMD Ryzen 9 5900HX with Radeon Graphics  3.30 GHz
Installed RAM	16.0 GB (15.4 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch	No pen or touch input.
2. It happens when I use windowed mode or fullscreen.
3. Not using a steam installation, not using any mod management software on my system.
4. No specific scenario, it just happens whenever I tab out regardless if I'm in the menu, talking to natsuki or not talking.

**Comment by Hardwaresss** [comment]
Hi again! I found the problem, seems like Wallpaper Engine doesn't like Just Natsuki running for some reason, and crashes the software.
