### ISSUE TITLE
[ SUPPORT REQUEST ] - So I was messing around with the time skip (date and time settings) and I was curious to see what would happen if I kept doing it. After the second time, I opened the game and was greeted with Natsuki missing. I've put a ton of hours into this mod and was wondering if there was anything I could do to fix this. Thanks.  

### ISSUE THREAD

**Issue by Maho365** [Just-Natsuki-Team/NatsukiModDev#771]
# Overview:
[brief description of the issue(s) you are facing]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Maho365** [comment]
eh sorry for making the title the whole subject

**Comment by RaionArt** [comment]
Hello @Maho365,

Natsuki made it already real clear in her first dialogue that you shouldn't tinker with the date as it hurts her physically. We consider time traveling as cheating as it is trying to bypass intended game mecaniques.

As per our [terms](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#i-want-to-modifyhave-already-modified-my-installation-can-you-help-me-if-something-goes-wrong) on cheating, this issue will be closed and we are making the decision to withdraw your right to support.

You may restart if you wish, but will not be eligible for any further assistance from the JN team.

Have a good day.

**Comment by Maho365** [comment]
Alright thank you for letting me know.
