### ISSUE TITLE
[ FEATURE REQUEST ] - Adding Some More Low Affinity Stuff

### ISSUE THREAD

**Issue by TheGameGlitcher** [Just-Natsuki-Team/NatsukiModDev#774]
Yes, I know, no one wants to be in the low affinity zone, but the devs have put in a lot of work already, so I thought I may as well make a suggestion based on it. My suggestion is to, as the title says, expand a little on the scenes at low affinity. Currently, there's no different notification messages for being below "neutral" for example. There could also be more special unique messages for going from high affinity to low affinity. Also, I noticed in the code one reference to a tier below broken, which is "ruined," although its never used. Naturally, my suggestion would be to use it, at the very least to change up the dialogue. I don't really have that many examples since my suggestion is so broad, but I can come up with some more in the discord if you ask.

**Comment by Blizzardsev** [comment]
Hi - thanks for your suggestion. In the future, I would ask that you stick to one suggestion per issue as we advise.

Regarding notification messages: we see these as an affirmative action. Natsuki is in a good relationship with the player, and therefore _desires_ their attention: this isn't unique to conversation notifications, but player activities too. If Natsuki is upset with the player or worse, it stands to reason she probably wouldn't want to draw attention from the person responsible for making her feel that way (and probably make things worse for herself). This might work for Upset, but beyond that doesn't seem realistic.

Regarding the Ruined tier: something to bear in mind is that we usually condition reactions/variations in dialogue in bands, with exceptions where they make sense - this is also the case with Ruined, which is usually tied in with Broken. Writing and testing variations for every individual tier isn't really practical given the scale of what we're working with: and ultimately, aiming to get to the lowest relationship states possible isn't what the vast majority of our player base actually do.

We can look at further incorporations of the lower tiers in our bands (I.E slight variations), but this isn't going to be a high priority for the team. At the end of the day, this is a mod about _building_ a relationship - not destroying one.

@RaionArt thoughts?

**Comment by RaionArt** [comment]
Blizz already explained it in detail, but to put it simple Natsuki should not notify the player at all under Normal tier, because why would she care?
Also ruined is indeed used as you already noticed with your desk for an example.

The main problem from JN we are trying to tackle at the moment is the lack of content, which means we want to introduce more topics and intro events. After we created a bigger variety of options for positive tiers, we could think about adding more to the negative ones as well.

Also as side note we would never asked for more details in discord as the discussion would get lost or forgotten.

**Comment by TheGameGlitcher** [comment]
Well your replies make sense, so I'm satisfied at least. I meant "more details in the discord" as in you tell me "hey you were vague with X" but I suppose you could just do the same here and get a reply. I do agree you should prioritize positive emotion stuff, but I wanted to see where you guys stood on adding more negative stuff too.

**Comment by Blizzardsev** [comment]
Closing given the above.
