### ISSUE TITLE
[ BUG REPORT ] - JN possibly causing issues with File Explorer

### ISSUE THREAD

**Issue by ZeroPointNothing** [Just-Natsuki-Team/NatsukiModDev#775]
# Overview:
While JN is running, I've been noticing the File Explorer (and everything else it controls) is slow and buggy. It takes longer to load, the task bar vanishes for a second sometimes, etc.

## Replication steps:
Simply run JN and try using File Explorer.

## Additional information:
Windows 11
Nvidia RTX 3060
AMD Ryzen 7 5800 8-Core Processor
16 GB RAM

### extra things

- I think Task Manager is slower too, but I am not sure because that's always been a little sluggish when switching menus.
- I believe it has always been like this, though I could be wrong.
- Nothing else seems to be slow, just File Explorer. (which as a dev makes things difficult when trying to move around and it's extremely sluggish.)

---

I'm not sure if it's just RenPy, JN, or something else I'm doing but as far as I can tell, having JN open is the only time this begins to happen, and it stops immediately after JN is closed. Sorry if this is something inevitable and a waste of time to make a report on lol.

**Comment by Blizzardsev** [comment]
Hi @ZeroPointNothing - can you please verify what version of JN you are running?

JN performs minimal interaction with the file system, and only uses the tray for notifications and I'd have expected to see this much sooner if it were a widespread issue.

Can you try running JN with chat notifications and activity notifications set to Off on the settings menu?

**Comment by Blizzardsev** [comment]
Also, is this an issue that occurs after JN has been running for some time or immediately after booting? Any logs you have would also be a big help.

**Comment by ZeroPointNothing** [comment]
Unfortunately, this issue may just be with my computer. The issue is on and off (as of writing this, File Explorer is running perfectly fine) and I can't seem to replicate it at will. Logs show no indicator that Ren'Py/JN is struggling with anything whatsoever.

I am using 1.2.3, but this issue has been here for as long as I can remember having JN.

I've recently opened my PC to booting Linux so I'll soon try running it under there and see if any odd performance drops happen that don't make sense like this one. However, the bottom line is that I don't _think_ JN itself is the root cause of these weird issues.

**Comment by Blizzardsev** [comment]
Thanks for getting back to us - let us know how you get on.

**Comment by RaionArt** [comment]
Just wanted to check if using Linux resolved the problem for you, @ZeroPointNothing?

**Comment by ZeroPointNothing** [comment]
While I haven't had the time to check Linux, I've narrowed it down to just my computer being "quirky". I've had multiple odd issues which, with research, have all lead to the simple fact that my computer is an Alienware one.

As of writing this, I haven't experienced the issue again since I made this Issue.

**Comment by Blizzardsev** [comment]
Thanks for the update. We'll close the issue given the clarification.
