### ISSUE TITLE
[ FEATURE REQUEST ] - give

### ISSUE THREAD

**Issue by pocenko** [Just-Natsuki-Team/NatsukiModDev#778]
# Overview:
[brief description of what this aims to achieve]

## Must haves:
[features that you deem essential for this issue]

## Could haves:
[features that you deem would be good, but not essential, for this issue]

## Is this feature request related to a problem? Please describe.
[A clear and concise description of what the problem is. Ex. I'm always frustrated when...]

**Comment by pocenko** [comment]
I think if we can give her some kind of food that will be pretty awesome xd

**Comment by RaionArt** [comment]
Hello, 

If you want to suggest an issue, please fill out the structue (Overview, must haves, etc.) we gave you instead of only filling out the title.

**Comment by pocenko** [comment]
> Hello,
> 
> If you want to suggest an issue, please fill out the structue (Overview, must haves, etc.) we gave you instead of only filling out the title.

sry, my internet is pretty bad now and I will try to fix it  later
