### ISSUE TITLE
[ SUPPORT REQUEST ] - Save file

### ISSUE THREAD

**Issue by QuePog** [Just-Natsuki-Team/NatsukiModDev#790]
The “AppData” file doesn’t have information regarding a save file for the Just Natsuki application.
The “AppData” file has subfiles “Local” -> “Microsoft” -> “Windows”, and the “Windows” files is empty.

Please help, I want to know how I can transfer my save data to a USB drive, and then to another laptop.

**Comment by Blizzardsev** [comment]
Hi @QuePog. As per the information on the [FAQ](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent):

- Navigate to your AppData folder. Assuming you are on Windows, either use the Run prompt (Windows key + R), type *%AppData%* and hit enter, or copy *%AppData%* into File Explorer's address bar. The correct address should resemble *C:\Users\[Your username]\AppData\Roaming*.
- Inside the AppData folder, navigate to the Ren'Py folder.
- Inside the Ren'Py folder, navigate to the JustNatsuki folder.
- Copy the persistent file. This is your save data.
