### ISSUE TITLE
[ SUPPORT REQUEST ] - 

### ISSUE THREAD

**Issue by infonic4321** [Just-Natsuki-Team/NatsukiModDev#792]
]# Overview:
Affinity is too slow, i think...
![Ekran görüntüsü 2023-09-10 005358](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/144565321/cce869db-9aee-45c6-93c1-ff2171e7a987)
![Ekran görüntüsü 2023-09-10 005421](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/144565321/4e44f29c-c65e-44f9-af64-7b11601b448a)
![Ekran görüntüsü 2023-09-10 005443](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/144565321/ed7613db-4c07-4227-9d9c-1f73b046315f)
?

## Additional information:
Yesterday, my affinity cap was: 5.76455350704. Today it is: 5.77395058505. I think its too slow, isnt it? And i gain all the affinity. Is there a way to make it faster? And also how to know how much affinity i gained? Thank you.

**Comment by Blizzardsev** [comment]
Hi @infonic4321: JN is intended to be played over a period of several months; therefore a small increase in the affinity cap over time is the intended behaviour.

Please see the following article on affinity: https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#affinity
