### ISSUE TITLE
[ SUPPORT REQUEST ] - Problem has occurred

### ISSUE THREAD

**Issue by SilverWolfxx** [Just-Natsuki-Team/NatsukiModDev#794]
I installed the just Natsuki 1.0.0 a long time ago I found it yesterday realising I can update it using the jn installer I installed the installer and updated the game I went to open it and it said "a problem has occurred. please contact JN staff." I went back to the update 1.0.0 and the game worked completely fine no issues at all. 
(sorry if this wasn't enough detail I'm trying my best)
![Screenshot 2023-09-10 142434](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/144603510/27fb1623-3809-41e7-9461-f0ab50718c3b)

**Comment by Blizzardsev** [comment]
Hi @SilverWolfxx - as mentioned on Discord, can you please attach your log (found under the log folder in your JN installation), and your persistent file?

Instructions on how to find your persistent can be found [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).

**Comment by SilverWolfxx** [comment]
[log and persistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12568289/log.and.persistent.zip)

**Comment by Blizzardsev** [comment]
Hi @SilverWolfxx - thanks for sending across your log and persistent. Seeing as you began playing on v1.0.0 and moved up to v1.2.3 through updates, the log should have evidence of save data migrations having taken place as the mod ran through the update sequence after booting the game; this would indicate the log was deleted recently.

The warning screen you are seeing is triggered when the game detects unusual save data, such as when affinity values have been tampered with. Additionally, I can see a number of indicators with your save data that would indicate progression through illegitimate means: for example, a total visit count of just 62, yet an accepted confession from Natsuki (requiring Love affinity, which takes several months and hundreds of visits to unlock), as well as many features which should be unlocked in the timespan of a normal playthrough still being locked.

As we highlight in our [FAQ](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#i-want-to-modifyhave-already-modified-my-installation-can-you-help-me-if-something-goes-wrong), and considering this would be the result of a modified installation (I.E cheating), we are making the decision to withdraw your right to support as a result.

If you wish to continue playing JN, you may consider deleting your save file and starting again. Seeing as your true affinity value was very low, this wouldn't take long to make back legitimately anyway.

Thank you.
