### ISSUE TITLE
[ SUPPORT REQUEST ] - Natsuki Died and i dont know is it a bug or not, but i reinstalled the mod but she stills dead, how do i bring her back?

### ISSUE THREAD

**Issue by MalakElMalardo** [Just-Natsuki-Team/NatsukiModDev#795]
# Overview:
[brief description of the bug, and the impact created]

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[Accidentally i messed up with the time and i forgot about natsuki and she died]

**Comment by Blizzardsev** [comment]
Hi @MalakElMalardo - if you have been playing with the system clock to the point where Natsuki is gone, then you will need to start a new game by deleting your save data: instructions on where to find said data can be found on the FAQ.
