### ISSUE TITLE
[ SUPPORT REQUEST ] - Somes outfits has vanished at some point

### ISSUE THREAD

**Issue by MonikaEndDie** [Just-Natsuki-Team/NatsukiModDev#797]
# Overview:
[brief description of the issue(s) you are facing]
So, i don't don't know when, but a bunch of outfits i've unlocked don't appear anymore in the list when i ask Natsuki to wear a different outfit. Actually, i've managed to get back a good portion of them thanks to topic who unlock them, but others like ruffle neck sweater or cosy gardigan are obtainable once, can i get help?
## Additional informations
[any other information you think is relevant - I.E operating system, date and so on]
look like seasons themed outfits are gone too

**Comment by Blizzardsev** [comment]
Hi @MonikaEndDie - can you please supply your log and persistent files? Instructions on where to find your persistent can be found [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).

Also, can I ask if you have performed any system restores or resets at any point? If you have rolled your machine's state back to an earlier point using something like restore points or the _Reset this PC_ on Windows, then you may have reverted your save to a point where you had not unlocked these outfits. The game does not re-lock outfits, so this would suggest an external event.

**Comment by MonikaEndDie** [comment]
Sure, here is the log one but the persistent seem to ne be supported...
[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12623583/log.txt)

**Comment by MonikaEndDie** [comment]
Sry, i didn't reseted my computer in anyway recently i think btw.

**Comment by Blizzardsev** [comment]
> Sure, here is the log one but the persistent seem to ne be supported... [log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12623583/log.txt)

If you copy your persistent file into a folder, then zip the folder, you should be able to attach it here.

**Comment by MonikaEndDie** [comment]
Ah, i see, there you go.
[justnatpersistent.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12623864/justnatpersistent.zip)

**Comment by Blizzardsev** [comment]
Hi @MonikaEndDie - I'm struggling to see a distinct cause in our code that could have resulted in your issue; oddly I can see that you have constituent parts of the affected outfits unlocked (I.E the cosy cardigan remains available), yet the parent outfits are not.

Can you please confirm if you are/have run any unofficial code I.E submods, or have made your own modifications to your installation?

**Comment by MonikaEndDie** [comment]
The only thing who aren't native from a fresh installation are the installer and everything in thos customs files
[customsassets.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12624040/customsassets.zip)
and btw, natsuki don't seem to detect the demon realm shirt, unless it is mean to be used for custom outifts only?

**Comment by MonikaEndDie** [comment]
Maybe should i zip my entire mod folder so you can analyse it entierly?

**Comment by Blizzardsev** [comment]
> Maybe should i zip my entire mod folder so you can analyse it entierly?

Yes please, that would be helpful.

**Comment by MonikaEndDie** [comment]
Damn, too big...

**Comment by Blizzardsev** [comment]
@MonikaEndDie Can you send over the contents of the _game_ folder, excluding anything from _mod_assets_?

**Comment by Blizzardsev** [comment]
Additionally, any screenshots you can provide of the _game_ folder's contents would help too.

**Comment by MonikaEndDie** [comment]
It's still too big, i'll try screenshot.

**Comment by MonikaEndDie** [comment]
![Screenshot (1)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/59206332/2029acbe-102e-4e7e-b31e-7b86bec5342c)
![Screenshot (2
![Screenshot (3)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/59206332/bb760985-9bd4-4e11-9f45-035c944bef69)
![Screenshot (4)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/59206332/56d25969-d26c-4e26-af85-3fbb001f3bd6)

)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/59206332/24116c43-ef90-4538-8e6b-c7fb47db2cc0)

**Comment by MonikaEndDie** [comment]
python-packages file got a lot of people in there, do you want screenshots from inside as well?

**Comment by Blizzardsev** [comment]
> python-packages file got a lot of people in there, do you want screenshots from inside as well?

The existing screenshots are fine, thank you.

While we investigate, you should still be able to create custom outfits using the parts you have unlocked from the outfits that are locked if you go to the outfit menu and select _Can I suggest a new outfit?_.

**Comment by MonikaEndDie** [comment]
Ok, let's hope and pray then. But about the demon realm shirt, it is affected by the issue or did i missed something?

**Comment by Blizzardsev** [comment]
We will let you know when we have more information.

**Comment by MonikaEndDie** [comment]
Allright! See you next time then.

**Comment by Blizzardsev** [comment]
Hi @MonikaEndDie, thank you for your patience. The issue has been identified and a fix will be rolled out when time permits.

**Comment by MonikaEndDie** [comment]
Sweet! Nice work and many thanks guys, can't wait to get back every missings outfits.

**Comment by Blizzardsev** [comment]
This has now been resolved in v1.2.4.
