### ISSUE TITLE
[ SUPPORT REQUEST ] - Problem has occured

### ISSUE THREAD

**Issue by oldtoonsfan** [Just-Natsuki-Team/NatsukiModDev#805]
I recently put converted music into Just Natsuki, in .ogg format using a converter. However, when I click on the music to play it in game, the game closes instead. I didn't have issues with music in the past, so I'm confused as to why its not working now. In the log, this message appeared though, which I'm not sure what it means: (<JNMusicOptionTypes.custom: 2>, u'DDLC THEME.ogg'). Can anyone help?

[log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12677461/log.txt)

I am on a windows 10.

**Comment by Blizzardsev** [comment]
Hi - can you please attach the .ogg file you were trying to play? If you can't attach it directly, then you can upload it inside a zip file.

The log entry you mention isn't of any importance; just an entry that was added during development that wasn't removed - it has no impact.

**Comment by Blizzardsev** [comment]
Also, can you please attach the _traceback.txt_ file from your installation?

**Comment by oldtoonsfan** [comment]
Well, I don't have a traceback, but I can attach the music file.
[music.zip](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/12677617/music.zip)

**Comment by Blizzardsev** [comment]
Hi @oldtoonsfan - it would appear the file itself wasn't converted successfully. Trying to play it on other software reports that the file is corrupt.

VLC:

![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/57731669/71fb4bc2-5423-49a6-b77c-f0a61985217f)

Audacity:

![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/57731669/d7094a34-5490-4c3f-901c-7a7d50269178)

Did you try playing this file after converting it? You may need to revise the options you are using to convert the file, or use an alternative tool/service.

**Comment by oldtoonsfan** [comment]
No I didn't, though okay. i'll try something different. Thank you.

**Comment by Blizzardsev** [comment]
Also as a side note - I would *highly recommend* renaming files that use kanji or any other non-alphanumeric characters; the font JN uses does not support these and so will use placeholders for any of these characters.

**Comment by Blizzardsev** [comment]
> No I didn't, though okay. i'll try something different. Thank you.

I would personally suggest Audacity for conversions if you are wary of using online converters, as this has built in options for exporting a track to MP3, OGG, etc. It also functions as a testing tool so you can make sure whatever you have downloaded is a valid file in the first place.

**Comment by oldtoonsfan** [comment]
I'll give it a try, then. Thanks again!
