### ISSUE TITLE
[ SUPPORT REQUEST ] - Headpats

### ISSUE THREAD

**Issue by Tight-Cicada3415** [Just-Natsuki-Team/NatsukiModDev#807]
# Overview:
Hello. I recently unlocked the headpats feature in the "Just Natsuki" mod, but everytime I try to give her headpats, it doesn't register them and ther counter stays at 0. Please help me.

## Additional information:
I'm running version 1.0.2 and my OS is Windows 11

**Comment by Tight-Cicada3415** [comment]
OK, I updated to 1.2.4 and it still doesn't work

**Comment by RaionArt** [comment]
Hello @Tight-Cicada3415,

as we mention in our wiki, at the current version the headpats are only working in the default window mode of the game. Within the next version you will be able to pat Natsuki in any resolution size til then please make sure to tick the window box in the options. Thank you.

**Comment by Tight-Cicada3415** [comment]
Still, I tried for 10 Minutes and it didn't register a single one. I am in windowed mode :(

**Comment by RaionArt** [comment]
In the default size?

**Comment by Tight-Cicada3415** [comment]
Yes

**Comment by RaionArt** [comment]
I'm gonna close this as the next update already features a fix for this issue.
