### ISSUE TITLE
[ BUG REPORT ] -  mano eu jogo just Natsuki no mobile (celular) e eu consigo adicionar as músicas e tal, mas quando eu vou colocar as músicas simplesmente não sai nenhum som (mesmo eu estando com o volume no máximo, do jogo e do celular) e até a Natsuki já falou "como você quer ouvir algo se está com o volume no zero? Deixa eu aumentar" ai ela tentou aumentar o negócio e eu falei "ah, agora vai dar certo" mas não adiantou nada, eu só quero ouvir musica no jogo e não tá dando, favor resolver 

### ISSUE THREAD

**Issue by IWaffleslalala** [Just-Natsuki-Team/NatsukiModDev#809]
mano eu jogo just Natsuki no mobile (celular) e eu consigo adicionar as músicas e tal, mas quando eu vou colocar as músicas simplesmente não sai nenhum som (mesmo eu estando com o volume no máximo, do jogo e do celular) e até a Natsuki já falou "como você quer ouvir algo se está com o volume no zero? Deixa eu aumentar" ai ela tentou aumentar o negócio e eu falei "ah, agora vai dar certo" mas não adiantou nada, eu só quero ouvir musica no jogo e não tá dando, favor resolver

**Comment by Blizzardsev** [comment]
Hi @IWaffleslalala - unfortunately, it would seem you are playing an unofficial port of our mod as we do not support or release for any mobile platform and therefore we are unable to offer our assistance.

Please raise this with the author of the unofficial port you are playing.
