### ISSUE TITLE
[ FEATURE REQUEST ] - New content star for categories

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#810]
# Overview:
As we added a tiny star to make new topics easier to resemble, I think the star should also appear to the coresponding category, so player don't miss newly unlocked or added content.

## Must haves:
New content star added to the categories of newly unlocked topics.

## Is this feature request related to a problem? Please describe.
Small feature, qol

**Comment by Blizzardsev** [comment]
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/57731669/25b6dbd1-d98f-4253-8c99-2b7b86970046)

Preview

**Comment by Blizzardsev** [comment]
This will be added in v1.3.
