### ISSUE TITLE
[ BUG REPORT ] - Natsuki eyes following mouse resulting in error (v1.3.0)

### ISSUE THREAD

**Issue by betapop** [Just-Natsuki-Team/NatsukiModDev#818]
# Overview:
A bug with the new v1.3.0 update, with Natsuki's eyes following the mouse. Basically, I get an "An exception has occurred" screen from Ren'py whenever Natsuki is trying to follow my eyes down/toward the bottom of the screen. (Though it works perfectly fine when it tracks my mouse up)

## Replication steps:
Whenever the idle starts, direct the mouse to the lower end of the screen. I've done this a few times and it yielded the same results as well.

## Additional information:
I would like to mention that this is the exact error i get when it crashes:

While running game code:
  File "game/script-ch30.rpy", line 291, in <module>
  File "game/definitions.rpy", line 968, in jnPause
AttributeError: type object 'Natsuki' has no attribute 'getMouseIsDown'

And that this is a very new save. I got this mod a few hours ago, so im not sure how much that has affected it. Ive also tried closing and reopening the game, with the same results. (I am also using Windows 11 if that helps at all)

**Comment by Blizzardsev** [comment]
Working on a solution. Will notify when complete.

**Comment by Blizzardsev** [comment]
Hi - this has been resolved in v1.3.1.
