### ISSUE TITLE
[ BUG REPORT ] - tiny typo

### ISSUE THREAD

**Issue by Chamelllemon** [Just-Natsuki-Team/NatsukiModDev#821]
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/111662346/0153681e-3ee2-4174-ad96-5a0c99e63909)
I don't think I have to explain anything, dunno what dialogue it was but she talked about being noisy in public transportation

**Comment by RaionArt** [comment]
Thank you for bringing this to our attention. This will be fixed in the next version.

**Comment by RaionArt** [comment]
This will be fixed in v1.3.2.
