### ISSUE TITLE
[ BUG REPORT ] - When I click on "Nevermind" in any menu, the animation that returns you to the desk has low fps.

### ISSUE THREAD

**Issue by AlchysFall** [Just-Natsuki-Team/NatsukiModDev#824]
# Overview:
[brief description of the bug, and the impact created]

## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by Blizzardsev** [comment]
Hi @AlchysFall - can you please clarify the following:

- What operating system are you running?
- What version of the game are you running?
- Does this happen every time you return from the menu, or just every so often?

**Comment by AlchysFall** [comment]
I'm using windows and the mod version is 1.3.1 and yes it occurs everytime I click on "nevermind"

**Comment by AlchysFall** [comment]
I've updated the mod to version 1.3.2 right now and I've noticed the same problem.

**Comment by AlchysFall** [comment]
I've done what you said but still the same issue. The game was perfectly fine before updating it to 1.3.1 also the other animations looks smooth so it's only the option "nevermind" that has the problem.

**Comment by Blizzardsev** [comment]
Can you please supply some gameplay footage to demonstrate how severe this FPS drop is?

**Comment by AlchysFall** [comment]
https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149626972/5f9baca7-b069-4d6a-8a7f-faba258f1df4
as you see here, when I click on "nevermind" the animation is buggy, but when I choose a topic or something to tell natsuki, the animation is smooth.

**Comment by Blizzardsev** [comment]
We'll look into it. As mentioned, due to the low amount of reports concerning this and lack of mention on our other channels, this will be low priority for the time being - especially given this is purely visual.

**Comment by AlchysFall** [comment]
Thank you for you time and keep up the good work. You guys are amazing.

**Comment by RZed01** [comment]
**Version 1.3.4, which is apparently supposed to fix this bug, did not work on my system.**

**Comment by Blizzardsev** [comment]
Unfortunately at this point, without stripping back animations to the point of no diversity (or engineering our own way of conditional sprite switching independent of Ren'Py) there isn't much more we can look to achieve in this area. We'll keep an eye out for further developments but there isn't much else we can suggest other than trying the mod on alternative hardware.

**Comment by RZed01** [comment]
I understand. I noticed this with other games I've played, that when I move them from the secondary 5400rpm HDD to my main NVMe SDD, that all the stuttering practically disappears due to the much faster read speeds. I personally don't mind the lag myself- as it is not a detriment to this mod's experience in any way.
