### ISSUE TITLE
[ BUG REPORT ] - "[player]" instead of actual player name while quitting blackjack

### ISSUE THREAD

**Issue by DeadmanShogun** [Just-Natsuki-Team/NatsukiModDev#826]
When I was playing Blackjack, I exited in the middle of a game, and it gave me this bug. Not sure if you guys know about but I wanted to bring it up just in case. 
![Screenshot 2023-11-02 233837](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149751316/bff890c4-e3e7-488b-b377-ba9e7e6062a1)

**Comment by RaionArt** [comment]
Thank you for reporting this issue! We will take a look at it.

**Comment by Blizzardsev** [comment]
This has been fixed in v1.3.2.
