### ISSUE TITLE
[ BUG REPORT ] - 2 copies of Ren'Py for dummies

### ISSUE THREAD

**Issue by RaionArt** [Just-Natsuki-Team/NatsukiModDev#827]
# Overview:
When Natsuki has her Ren'Py for dummies book on the desk, it is still possible for her to enter her idle reading it, which gives the impression she dublicated the book or simply has two copies.

## Replication steps:
- Have the Ren'Py for dummies book as desk item
- Have her entering her idling reading said book

## Additional information:
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/112613077/aa7d24ef-c63c-4da2-8ba5-07c7a534da25)

**Comment by Blizzardsev** [comment]
This has been fixed in v1.3.2.
