### ISSUE TITLE
[ BUG REPORT ] - Update Checker not working

### ISSUE THREAD

**Issue by RZed01** [Just-Natsuki-Team/NatsukiModDev#830]
# Overview:
After launching the game and checking the log, it will say that it has failed to check for updates with the error:
Failed to check for updates: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /Just-Natsuki-Team/NatsukiModDev/releases/latest (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

## Replication steps:
Launch the game and then check the log. It may look like this:
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149847536/bc6ababb-af62-4df4-b7f1-327d62f2c105)

## Additional information:
Observed several times consistently on 11/3/2023, on Windows 10 22H2 ver 19045.3570. I have not seen a single occurrence in the log where the check was successful. I do not know if Mac or Linux are affected, or if other features in game that use the Internet are affected, as I have not unlocked those features in my playthrough yet.

**Comment by Blizzardsev** [comment]
Hi @RZed01 - thanks for bringing this to our attention. This is due to a missing script that should have been included in the build.

As we're not far off releasing a patch for a number of other issues and this isn't really a code issue, we'll look at fixing this with the release of the next patch.

**Comment by Blizzardsev** [comment]
This has been fixed in v1.3.2.
