### ISSUE TITLE
[ BUG REPORT ] - Birthday Errors

### ISSUE THREAD

**Issue by Project-Archangel** [Just-Natsuki-Team/NatsukiModDev#834]
# Overview:
Got theses errors on my birthday, not entirely sure what they are but the log does not show them so I took screenshots for the time being unless told otherwise what I should/can send

## Replication steps:
Open JN on birthday

## Additional information:
Nothing I can think of
![1](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/104313945/c41a9ea2-33db-4d4d-8b33-77fe6ed8e81d)
![2](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/104313945/f9dcd720-2c0e-4945-a4b8-1207fd2a0444)
![3](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/104313945/35da3d90-ee58-4ae9-8a0a-651d5159d99b)

**Comment by Blizzardsev** [comment]
Hi @Project-Archangel , thanks for raising this with us and apologies for the inconvenience considering the day.

The issue has been identified and a fix is in progress.

**Comment by Project-Archangel** [comment]
No worries! Did not cause an inconvenience at all!

**Comment by Blizzardsev** [comment]
This will be resolved in v1.3.3 - we'll hold off for a short time in case other issues crop up before committing to a release.

**Comment by Blizzardsev** [comment]
This has been resolved - please update to v1.3.3.
