### ISSUE TITLE
I don't get anything new to talk about with Natuski

### ISSUE THREAD

**Issue by Lucasdem00** [Just-Natsuki-Team/NatsukiModDev#835]
I don't know if it's a bug but it's been 3 days and i don't get anything new to talk about with Natsuki is it a bug or i just have to wait ?

**Comment by Blizzardsev** [comment]
Hi @Lucasdem00 - content in JN is unlocked gradually over time (days, weeks and months), with unlockable content based on both how close you are to Natsuki as well as the total amount of time spent in-game (not just with JN installed).

If you are struggling to unlock new content, I would suggest visiting frequently and aiming to hit the maximum amount of affinity you can gain per day by talking to Natsuki, listening to her bring up topics, etc. The amount of ways you can get close to Natsuki will be more limited initially so slower progress to begin with is to be expected.

For a full list of ways to get closer to Natsuki and what the mod has to offer, you may wish to consult the [wiki](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/05:-All-features-(Spoilers)#affinity).
