### ISSUE TITLE
[ BUG REPORT ] - Exception occurs if you already have custom outfits installed before unlocking them

### ISSUE THREAD

**Issue by RZed01** [Just-Natsuki-Team/NatsukiModDev#842]
# Overview:
If you already had custom outfits in the game directory before the custom outfits feature is unlocked, after Natsuki brings up the custom outfits feature and you finish her conversation, the game may display this exception screen: 
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149847536/ec5a16b4-9d94-4519-9e3d-01d6c27d9312)
It can be safely ignored, but it is still confusing that it appears.

## Replication steps:
Have custom outfits from the NatsukiModOutfits repository (https://github.com/Just-Natsuki-Team/NatsukiModOutfits) installed in the current 1.3.3 version of the game, but have it installed before the feature itself is unlocked. Wait until Natsuki brings up the topic, and then click through it until it finishes.

## Additional information:
This is on Windows 10 22H2 build 19045.3693. It is also not a fatal error. I am bringing this issue up because it happened with outfits from an official repository. I would not have brought it up if I were using some other unofficial outfit pack.

**Comment by RZed01** [comment]
There is also a possibility that this bug can happen even if no custom outfits are present, but I cannot wait two weeks to test it again with a new install.

**Comment by RZed01** [comment]
Further observation: This exception does not seem to result in any outfits breaking. Changing outfits and gifting Natsuki the installed custom outfits works as intended.

**Comment by Blizzardsev** [comment]
The issue has been identified. We'll let you know when a fix has been released.

**Comment by RZed01** [comment]
Just saw the patch. Hopefully, it fixes the issue.
