### ISSUE TITLE
[ BUG REPORT ] - Blackjack game Ace card problem

### ISSUE THREAD

**Issue by SteelAxleVII** [Just-Natsuki-Team/NatsukiModDev#848]
[Ace cards do not read as "1"]

Hi there! I just recently unlocked the blackjack game and it is very fun. However there is one problem I am encountering and that is if you play an ace card, it only reads as 11 if your card numbers add up more than 10. In blackjack, Aces count as 11 or 1 depending on the the number count. See the attachment below this section. This isn't really a bug, but it's the only place I can talk about it.

![screenshot0008](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/27037292/1df77306-bea8-4879-bdeb-6b4f6938d842)

I have a Jack, 3 and an ace. This is suppose to add up 14, but adds up 24 instead.

**Comment by RZed01** [comment]
Someone asked a similar question in the Discord- I think it is best that you ask Natsuki to go over the rules of Blackjack again. They are probably different in comparison to the Blackjack you may see at a casino.

**Comment by RaionArt** [comment]
Just gotta add this works like intended. If you are not sure about the value of aces you can ask Natsuki to repeat the rules or look up the rules online. They are the same for most blackjack games.
