### ISSUE TITLE
[ BUG REPORT ] - Minor typo in intro event

### ISSUE THREAD

**Issue by RZed01** [Just-Natsuki-Team/NatsukiModDev#853]
# Overview:
There is a grammatical error on one of Natsuki's greetings. Here it is:
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149847536/24bab723-0845-4085-8d49-0f68335b6fff)
I think what should be said here is either "N-not that I was just _sitting_ around waiting for you or anything, obviously." or "N-not that I just sat around waiting for you or anything, obviously." (change sat to sitting in the first case, and remove "was" in the second case)

## Replication steps:
If Natsuki is on at least Affectionate affinity, she may bring up this greeting upon opening the game.

## Additional information:
This is a minor bug that should not take much to fix, so if you are releasing a bugfix patch soon, please include this.
Observed on Windows 10 22H2 build 19045.3803 on 12/14/2023

**Comment by Blizzardsev** [comment]
Will be fixed in v1.3.5.
