### ISSUE TITLE
[ BUG REPORT ] - Rapid idle animations due to OpenWeatherMap API lag

### ISSUE THREAD

**Issue by RZed01** [Just-Natsuki-Team/NatsukiModDev#854]
# Overview:
If you have the Real-time weather feature on, there is a small chance that the API pinging the server to update the weather may cause a momentary freeze. During this freeze, the commands to change Natsuki's idle pose will continue to execute, so that by the time this check is finished, you may experience Natsuki briefly rapidly cycling through her idle poses before going back to normal behavior.

## Replication steps:
This bug cannot be replicated consistently, since how long the bug lasts (and hence the rapid cycling of animations) is dependent on the connection lag between the home computer and the OpenWeatherMap server that the API will check.

## Additional information:
Observed several times on Windows 10 22H2, non-insider preview build. In fact, it has occurred to me several times in the past few days. **This is already a known issue that is actively being worked on**, but since no report was filed, I am filing this myself for anyone who wants to take a shot at fixing this. I personally do not consider this as a fixable issue, but feel free to try and solve it.

**Comment by RaionArt** [comment]
Gotta close this as we are already aware and acknowledge this in #852. A fix is already in the works.

**Comment by Blizzardsev** [comment]
A (mostly complete, given Ren'Py limitations) fix for this has been found - it is however unrelated to weather functionality. In short, the way that Ren'Py handles transitions has the effect of speeding up the progression of images that make use of multiple choices, this including the idle displayable used for Natsuki,

**Comment by RZed01** [comment]
So this issue is related to #849 ? That's interesting.
