### ISSUE TITLE
[ BUG REPORT ] - Fps Drops during idle

### ISSUE THREAD

**Issue by oskarekgra** [Just-Natsuki-Team/NatsukiModDev#855]
# Overview:
[brief description of the bug, and the impact created]
The game's fps drop to 5-15 (in my expirance) while there's no interaction ongoing, goes back to normal when you ex: press on "Talk"
Noticable after pressing "Nevermind." Or in the game's menu if opened during the time. (Man my english is dying)
## Replication steps:
[please describe with as much detail as possible how to *consistently* recreate the bug]
You just... Do nothing. 
## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]
Windows 11.. Not sure if anything else is needed.

**Comment by RZed01** [comment]
This issue was already reported in #824 - there is not much that could be done further than what was already done.

**Comment by RZed01** [comment]
Also, this is a visual novel that uses 2d sprites. FPS is not really important in this kind of thing

**Comment by oskarekgra** [comment]
> I believe this issue was already reported in #824 - there is not much that could be done further than what was already done.

Welp, I guess i didint notice that.  Sorry.

**Comment by oskarekgra** [comment]
> Also, this is a visual novel that uses 2d sprites. FPS is not really important in this kind of thing

Its just kind of weird when the menu runs in 15 fps when it can run in 60 if you just open it during an interaction.

**Comment by RZed01** [comment]
All I can say on that is that this is because of the game engine. Not much can be done there

**Comment by oskarekgra** [comment]
Alright. I guess nothing to be done with that.

**Comment by RaionArt** [comment]
As mentioned this issue was already improved with the last update, v.1.3.4, to keep it simple I'll just quote Blizz why we decided against improving this issue furthermore for now:

              Unfortunately at this point, without stripping back animations to the point of no diversity (or engineering our own way of conditional sprite switching independent of Ren'Py) there isn't much more we can look to achieve in this area. We'll keep an eye out for further developments but there isn't much else we can suggest other than trying the mod on alternative hardware.

_Originally posted by @Blizzardsev in https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/824#issuecomment-1830505835_
