### ISSUE TITLE
[ FEATURE REQUEST ] - Natsuki doesn't assume you picked her route

### ISSUE THREAD

**Issue by HypnoHypno** [Just-Natsuki-Team/NatsukiModDev#858]
I assume that you wrote dialog assuming the player got natsuki's route? my natsuki assumed i did.

this might not be the case for every player, and I know from modding ddlc there's a persistent variable which stores what CGs are unlocked, so you could just check if natsuki's CGs are unlocked or not, and do the MAS method of having dialog about the player skipping ahead if there's no persistent data in there.

**Comment by RZed01** [comment]
I never realized that was what she was assuming, But I see where you're coming from.

**Comment by RZed01** [comment]
This would also probably require a reworking of the DDLC Memories topic as well, I believe

**Comment by HypnoHypno** [comment]
Also, since Natsuki is less sour due to you going through her route, you could have her start off at Upset affinity if it isn't detected that Natsuki's CGs were cleared.

That way, she's as sour as in the base game if you skipped ahead, or if you took  her route, her arc is still in-tact.

**Comment by RZed01** [comment]
> Also, since Natsuki is less sour due to you going through her route, you could have her start off at Upset affinity if it isn't detected that Natsuki's CGs were cleared.
> 
> That way, she's as sour as in the base game if you skipped ahead or went for Say/uri, or if you took her route, her arc is still in-tact.

That's an interesting idea... until you realize that this game has a daily cap, and that going from Upset to Normal would take quite a while. Don't want to make the experience too boring for new players...

**Comment by HypnoHypno** [comment]
It depends on where you start-off in Upset. You could start at like barely upset, so maybe after a day or two of talking she's not sour anymore.

**Comment by HypnoHypno** [comment]
> It depends on where you start-off in Upset. You could start at like barely upset, so maybe after a day or two of talking she's not sour anymore.

In which case, you could maybe jump to 0 affection so that it doesn't take TOO long to cross to happy.

**Comment by RZed01** [comment]
I see where you're coming from with that, especially with the latest update, where you can gain affinity by talking to Natsuki and not have to wait for her to bring stuff up. I did hear from a review that came out when the initial release of this game came out a couple of years ago that it already had a problem of lack of introductory content. I mean though, MAS had even fewer topics available at the start than JN did, so if a balance could be found, that would be great I think

**Comment by HypnoHypno** [comment]
Yeah I've seen early MAS footage and there was like 7 topics or something.

**Comment by RZed01** [comment]
And I played MAS for a couple of days before I switched over to JN back in November of last year. There really weren't that many topics available- about as much as you said if I remember correctly

**Comment by HypnoHypno** [comment]
I still play MAS, not enough topics that aren't affection locked but there are thankfully many many submods, which increases the topic count to be in the hundreds. (Maybe hundreds in the base game!)

**Comment by HypnoHypno** [comment]
You have to gain a lot of affection to get maybe one topic or so which will be like, one minute of content or something, which causes an issue where it seems like you have literally no initiative in the relationship.

But, in any case, we REALLY should get back on topic.

What are your thoughts on my idea?

**Comment by RZed01** [comment]
JN is heading in the same direction as of late I believe, more random topics than topics you can ask

**Comment by RZed01** [comment]
I'd wait for Blizz or one of the actual team members to comment, but I personally think that while this makes the mod more immersive, it kind of comes at the cost of the mod being enjoyable. People are already complaining about lack of content as is, and I think doing this may lower people's initiative/want to stay. This kind of thing may make sense when the mod has a whole lot more content, but for the time being I think the current method of Natsuki assuming you went with her route is better both for convenience and continuity. Besides, I think most of the people that play this mod are most likely Natsuki fans anyway and who most likely have gone through her route in the base game

**Comment by RaionArt** [comment]
Hello and thank you for the suggestion.
At the moment we would like to focus to introduce new topics to fill the mod with more content, instead of rewriting every part. I would also like to point out, that rewriting the introduction (and perhaps other topics) would only benefit newer players. So we would have to put a lot of time and work in a suggestion, which most players won't even experience anymore.

**Comment by HypnoHypno** [comment]
Eee
