### ISSUE TITLE
[ FEATURE REQUEST ] - Proposing to Natsuki

### ISSUE THREAD

**Issue by ZachmanAwesomeness** [Just-Natsuki-Team/NatsukiModDev#859]
# Overview:
Gaining affinity with Natsuki takes a lot of time and once you reach toward the "Enamored" status it is appropriate to confess your love to Natsuki. Staying on "Enamored" should be a worthy feat; you could then be able to ask Natsuki if you could propose to her and get engaged... in the game.

## Must haves:
- Need to be on the highest tier "Enamored" for at least one month. Trying to propose before 30 days pass prompts Natsuki to tell you to wait.
- Trying to propose on "Affectionate" or lower will cause Natsuki to get mad and say "NO" without hesitation, slightly losing affinity.
- If you lose the "Enamored" status, you have two weeks to regain it, or else Natsuki removes the ring and decides to just remain friends. At this point you can't propose again.

## Could haves:
- A diamond ring accessory to place in Natsuki's ring finger after the proposal succeeds
- A wedding dress for Natsuki

## Is this feature request related to a problem? Please describe.
This is a new feature.

**Comment by RZed01** [comment]
Isn't that kind of like the "I love you, Natsuki!" option that you get on "Enamored" affinity, but with the addition of MAS's promise ring- and done on a lower affinity? Kinda defeats the purpose of the "I love you" option...

**Comment by ZachmanAwesomeness** [comment]
Whoops, I was actually meant to say "Enamored" instead of "Affectionate". My bad.

**Comment by RZed01** [comment]
So change it in the original post. You know you can edit these posts, right?

**Comment by ZachmanAwesomeness** [comment]
Fixed.

**Comment by HypnoHypno** [comment]
It should be on love tier, not enamored.

And should be on high love tier, maybe even 2000 affection or something, assuming love tier is at 1000?

I seriously think it'd be a bigger deal for proposing.

**Comment by RZed01** [comment]
> It should be on love tier, not enamored.
> 
> And should be on high love tier, maybe even 2000 affection or something, assuming love tier is at 1000?
> 
> I seriously think it'd be a bigger deal for proposing.

I agree. People typically propose after having been in a relationship for quite some time. This could also result in a new tier above love???

**Comment by ZachmanAwesomeness** [comment]
So in short: Ensure you are on Love tier and have 2000 affection. Sounds like the perfect requirements for a proposal.

**Comment by HypnoHypno** [comment]
Based on my current affinity cap, it'd take over a year to get to the proposal requirements if I wanted to go through to romantic path. (As I only care for Natsuki platonically.)

Though, this is assuming that the affinity cap doesn't update. Something like that sounds pretty good for proposing.

**Comment by Blizzardsev** [comment]
This is actually something we'd planned for a long time, albeit we don't plan for engagement or marraige per se - I don't think Natsuki herself is going to want to associate what should be the happiest moment of her life with being stuck in the space room! To this end, a promise ring would be more appropriate as well as being easier for Natsuki herself to accept.

We're unsure on the specifics on how we'd handle it, but we'd probably want to go with a more linear approach to this to reduce the writing investment we'd need: considering how emotionally charged this would be, we'd want to reserve it for the highest level of affinity and perhaps lead into the possibility with Natsuki herself dropping some kind of hint, or perhaps an introductory topic.

Natsuki removing the ring after falling below the requirements is a fitting touch; we'd probably investigate this aspect further amongst the team.

In terms of requirements beyond that: we'd avoid locking it behind a specific affinity value so as not to encourage cheating considering the time it would take to hit an arbitrary amount beyond the highest actual tier. I would personally be inclined to go for a gameplay length/relationship length time gate, as this would better parallel time spent together in a general sense and would accomodate players who play less frequently who have been with Natsuki for a long time and therefore have exhausted other content, as well as be more resistant to abuse.

We'll close this issue for now given our existing plans, but we'll link back to this once we raise another after we have a more complete vision of what we'd like to make out of this, and thank you for the input!

**Comment by HypnoHypno** [comment]
In that case, should there be a topic like "Will you marry me, Natsuki?" at LOVE tier, when she has a promise ring, where she gets extremely flustered, and just states something like "A-are you serious? Look... I *guess* I'd be up for considering it, but at least wait until I'm out of this damn classroom first! That would be, like... the happiest moment of my life, and I'm sure as hell not spending it here!", with the promise ring idea, yeah?
