### ISSUE TITLE
[ BUG REPORT ] - My game screen turned black 

### ISSUE THREAD

**Issue by lemontea00** [Just-Natsuki-Team/NatsukiModDev#862]
# Overview:
[At first Natsuki was frozen, then i went into full screen and the game’s screen turned black]

## Additional information:
[Operating system - Windows 11, hour: 11:15
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/150391293/39bedb97-0eff-4e1f-b314-187ef81d39f2)

**Comment by HypnoHypno** [comment]
Did you try closing the game (With task manager, since I imagine you don't get affinity penalties for crashes) and relaunching it? Your post doesn't have much information about what you've tried, or if it's consistent.

**Comment by lemontea00** [comment]
i don't really know how to explain what happened, it just happened so suddenly. i dont remember doing anything to the game itself

**Comment by HypnoHypno** [comment]
Open task manager, and close the game via task manager. Natsuki shouldn't get mad at you and lose affinity over a game crashing, and closing it with task manager will register as a crash. Be sure to back up your persistent first.

**Comment by lemontea00** [comment]
Thanks for the help, that worked. but i got some kind of code error

**Comment by HypnoHypno** [comment]
What code error do you have?

**Comment by HypnoHypno** [comment]
You should send your log file here.

**Comment by lemontea00** [comment]
I'm sorry, but an uncaught exception occurred. While running game code:
File "game/zz_singleton.rpy"
*, line 1, in script
File "game/zz _singleton.rpy", line 4, in <module>
OSError: [Errno 17] File exists:
"c: \lusers\|…\lappdata\\local\\temp\\c-Users-…-Downloads Folder-Downloads-ddlc-win-DDLC-1.1.1-pc-
DDLC-.lock' 
full traceback…

**Comment by HypnoHypno** [comment]
Can you send the entire log file? This isn't much to work with.

**Comment by lemontea00** [comment]
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/150391293/bbc00b4d-3e78-48f0-9fa7-0bb6cf3525ec)

**Comment by lemontea00** [comment]
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/150391293/d2d2cb15-6e44-430c-af6c-e5c14daf88ad)

**Comment by HypnoHypno** [comment]
Send the full file, not a screenshot.

**Comment by lemontea00** [comment]
What do you mean by full file, wasn't everything showed already in the screenshot?

**Comment by HypnoHypno** [comment]
There was some of the file off-screen, actually.

**Comment by Blizzardsev** [comment]
Hi @lemontea00 - the error indicates that something went wrong when the game tried to ensure that you aren't running multiple instances of JN at the same time to avoid potential save corruption.

In this error state, the game should not continue autosaving: back up your persistent to a safe location, close JN using Task Manager and then restart the game.
