### ISSUE TITLE
[ FEATURE REQUEST ] - Small nitpick about Self Voicing

### ISSUE THREAD

**Issue by HypnoHypno** [Just-Natsuki-Team/NatsukiModDev#863]
So, I discovered the self-voicing feature. when accidentally pressing the V key I'm not blind or anything, but I want to use this feature.

I thought it'd be cool if maybe you used a girl tts speech for Natsuki's dialog. Something that sounds like her, or maybe something like how the DDLC MAS Monikai submod uses a tts voice trained on monika's voice.

Something like that would be cool, and benefit not only people who need to use that feature, but it'd strengthen immersion for people who aren't neccesarily blind or have bad eyesight.

**Comment by Blizzardsev** [comment]
Hi @HypnoHypno - thanks for your suggestion.

Interesting that you managed to enable self-voicing, as this is something we explicitly disable in the mod setup process.

At any rate - at least from me, it's going to be a hard pass I'm afraid for a range of reasons.

Unlike with Monika who has an entire song and a set of voicelines in the credit sequence, there's no definitive/canon voice for Natsuki which immediately places us in a difficult spot: there's no real source for us to train with or compare against, without finding an alternative voice actor - which leads us to my next point of concern.

Finding a voice actor willing to work with the project that:

- Is willing to work at the rate the team can personally afford, or is willing to volunteer their talent at no cost. We're a volunteer team at the end of the day, and entirely self-funded: would we rather invest in this, or something like music and CGs which may well be more widely received and enjoyed?
- Is comfortable with their voice essentially becoming the template for whatever we - or anyone with the ability to write Ren'Py code ultimately - feel like it should say. In an official sense this might be fine, but how would they feel about submods, or unofficial content? What if their voicing is used to create content that could reflect badly on them as a creator? Etc.
- Matches Natsuki's personality and speaking patterns/habits in a way that we as a team are comfortable accepting, and presenting to our community as what _we_ think is the best fit

As with any TTS, there is also context to consider: remember that we account for a huge variety of moods and scenarios for Natsuki. Does a text to speech solution satisfy the following as an example:

- Natsuki being elated at the player's first confession: can it sound as excited or passionate as we expect?
- Natsuki breaking down in tears over mistreatment at the player's hands: can it capture her complete despair and lack of hope, or even her anger?
- Natsuki frustrated at sharing her experiences with her education, or things people do that wind her up: can it express her annoyance in a way we can relate to as an audience?

While it might satisfying basic lines (such as randomly selected menu dialogue), hopefully our concern on this front is more visible given the above.

Adding to this, we must consider that Natsuki (like Yuri) relies a *lot* on onomatapeia as part of her speaking habits:

- Ugh...
- Uuuuu-!
- Nnnnnn-!
- Mmmmnnnn-!

Unfortunately, I wouldn't personally see this as something TTS would be example to pull off convincingly, and stripping these out of our topics isn't an option either.

Further, we must also remember that the mod has been maintained for some time now - a lot of our playerbase will have their own impression of how *their* Natsuki will sound, and forcing an official voice in this way may come across as intrusion on their personal interpretation. While we can add a toggle, this isn't territory we are comfortable exploring.

Lastly, from a personal viewpoint it just doesn't feel like something I would be comfortable working into the mod. AI-generated content is already something of a hot topic in regards to creative works, and as a passion project I don't feel like such content is what I originally joined the team to create/maintain.

@RaionArt thoughts on this?

**Comment by HypnoHypno** [comment]
"Interesting that you managed to enable self-voicing, as this is something we explicitly disable in the mod setup process."

Hm, then why did you code that in the first place, if you don't want such a feature? (Especially since something like this is going to help a lot of people who have bad eyesight, even with the whole weird microsoft sam-esque voice)

**Comment by Blizzardsev** [comment]
We did not - self voicing is default Ren'Py functionality. Please refer to the following article: https://www.renpy.org/doc/html/self_voicing.html

Regardless, this isn't something we're pursuing. While I can sympathise with those who suffer with eyesight issues, it's worth noting that even base DDLC does not offer this functionality and that at the end of the day, this is a visual novel and large amounts of reading are to be expected.

If need be, the game can always be ran in fullscreen mode or system tools can be used to assist.
