### ISSUE TITLE
[ FEATURE REQUEST ] - "How do you spend your time when I'm gone" topic

### ISSUE THREAD

**Issue by HypnoHypno** [Just-Natsuki-Team/NatsukiModDev#866]
Simple, a topic which is like "What did you do when I was gone?" that registers after you say goodbye to Natsuki for the first time. It'd have a random quip when stated (which if you repeat the topic would be the same quip until the game is closed, probably choosing a quip for it at startup).

Quips would be like just a few dialogs about how she was reading manga, or looking for something around the spaceroom, or trying to muster up courage to exit the spaceroom. Something like that!

Potentially also a dialog about her having found some scrap paper in the closet, and writing some poetry on it. (Could have a dialog where you ask her to show you, but that may be overkill since a poem would need to be written for this.)

**Comment by RaionArt** [comment]
Hello @HypnoHypno and thank you for your suggestion,

I feel like there are already multiple occassions in which the player gets an idea what Nat is doing while the player is gone. Basically with every intro event you run into Natsuki in the middle of something. There are also the idles, which start to play if you leave JN running without interacting with her, (which some times include her trying to write poems btw). 

I also feel like a topic like that would clash with some of the exisiting writing. For example Nat cannot tell you that she build up the courage to leave the class space room, but then again tell you in another topic, that she didn't manage to get out yet.

If you meant that the quips should play after starting up JN, these could also interefere with the greetings line, while some of  them already explain what she were doing before you entered as well (Looking at you Sanjo)
