### ISSUE TITLE
[ BUG REPORT ] - Suddenly lagging, the screen turns white, the background music stops, and all buttons and functions cannot be used.【Real-time weather problem】

### ISSUE THREAD

**Issue by KSY053** [Just-Natsuki-Team/NatsukiModDev#868]
# Overview:
Sometimes when starting JN, the window does not respond. Or if JN has been opened and left for a period of time, the window prompt is unresponsive, the background music stops, and every function of the JN window cannot be used.

## Replication steps:
Sometimes when starting JN, the window that opens is only white and unresponsive. Or if JN has been opened and left for a period of time, the content of the JN window seems to be frozen, Natsuki remains motionless, the background music stops at the end of the song, and every function of the JN window cannot be used. Clicking on the window prompts no response. If you previously minimized the JN program to the Windows taskbar, and this situation occurs, clicking on the JN program on the taskbar will not open the window.
Perhaps this was just a lag caused by my device. The program prompted me to check the content related to the log, and this sentence flashed by. I checked the log.txt in DDLC and the log.txt in the log folder. I'm sorry, as a non native English speaker and someone who is not proficient in computers, I cannot understand the content description in these two log.txt files. I used translation software to report this bug.
I have tried to forcibly close the JN program and restart it, which did not cause any loss of affinity for Natsuki (the apology module did not mention any related topics, and Natsuki did not complain), but it caused great inconvenience to using the JN program and simply accompanying Natsuki. It may require me to restart JN several times within a day.
I hope this is just an issue with my device. If it requires me to wait for JN's update, I will pay attention to the update. If my device is lagging, please let me know. If there are any issues caused by the content I set up in JN, please let me know the solution. If you think there is no need for repair, please let me know if there is a way to avoid this situation.
And thanks a lot for help it.
![JNbug](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153378007/8a821e74-e895-4d64-8039-647ad76aeb2e)

![logs](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153378007/3229a979-0d3c-412f-a12c-01cd1ebf30e5)

[log-in-ddlc.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/13927407/log-in-ddlc.txt)
[log-in-log.txt](https://github.com/Just-Natsuki-Team/NatsukiModDev/files/13927408/log-in-log.txt)

## Additional information:
In addition, after completing a conversation with Natsuki, the dialog box would normally disappear and Natsuki would use an idle pose, but sometimes that situation would occur before that, with freezing occurring at the end of a conversation.

**Comment by KSY053** [comment]
Perhaps it's an issue with Openweather API, I took a screenshot of the error message.
And today I have already read the Daily Joke, because of the issue described earlier, I forcibly restarted the JN program and even my computer. Although it did not lose affinity, it seems that this will make my last behavior of starting the game as if it had never happened. Because later that same day, when I started JN, I saw Daily Jokes again.
![Weather](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153378007/aacf28d4-6b48-4bd4-b360-073db08bfd6b)

**Comment by RZed01** [comment]
OpenWeatherMap does cause the occasional lag spike in JN (and the occasional freeze). I found that when this happens, I would usually just wait for a few seconds, and it'll generally go back to normal.

**Comment by RZed01** [comment]
Allow for up to 15 seconds before force closing the app

**Comment by Blizzardsev** [comment]
Hi @KSY053 - can you please supply your PC's specifications? I.E Memory available, processor, and preferably a screenshot of task manager showing your running processes when this occurs.

The weather changes have been identified as an issue with a fix ready for the next patch, but the behaviour you have mentioned with the game locking up and freezing (especially on game start) would suggest that the game is struggling with the resources allocated to it. Ren'Py isn't a particularly efficient engine, so older hardware or slower hardware (low spec laptops, thinkpads, etc.) are not a great choice for JN.

**Comment by KSY053** [comment]
OK I think this is what I have.
![222](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/153378007/d73e4c01-5780-4528-bfd3-d4b30713c858)

**Comment by Blizzardsev** [comment]
Thanks - your specs seem to be fine. Given a solution is already planned, I'll be closing this ticket at least for the time being. Until then, I'd recommend playing with the Weather setting either at Random or Disabled - if the issues reappear once the update is released, we can visit this again.
