### ISSUE TITLE
[ BUG REPORT ] [FIXED] - Cant press talk button, when I press it 2 times, screen fades black, it plays the ddlc menu music, and the day restarts, and the textbox text is slightly off as well.

### ISSUE THREAD

**Issue by toffeezx** [Just-Natsuki-Team/NatsukiModDev#869]
idk how this happend but i was just spending time with natsuki / natsundere when i opened the game back up, i could not talk to her, i could not press the talk button! and when i press it 2 times, the screen fades to black, it plays the ddlc menu music, and it restarts the day o_o and the font is slightly off as well. idk how this happend but i need help!!!
![screenshot0022](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149102958/6a5ddc1e-c054-40e2-ac16-915a090160bc)

**Comment by toffeezx** [comment]
i meant to say text, not font

**Comment by toffeezx** [comment]
nvm i fixed it.

**Comment by RZed01** [comment]
> nvm i fixed it.

If your problem is solved, close the issue.
