### ISSUE TITLE
[ BUG REPORT ] - Progress Lost

### ISSUE THREAD

**Issue by deluxslep** [Just-Natsuki-Team/NatsukiModDev#874]
# Overview:
All progress lost, Original first run overwritten. 

## Replication steps:
I am not sure; I opened the game and it reset all my progress.

## Additional information:
Was running on (.rpy) files. Date: 2/8/24

**Comment by Blizzardsev** [comment]
Hi @deluxslep - going forward, please be advised that users running source code distributions (and any modifications they choose to make) do so at their own risk.

Given you have marked this as completed, we'll assume this is no longer a problem.
