### ISSUE TITLE
[ SUPPORT REQUEST ] - 

### ISSUE THREAD

**Issue by yeetusnewtus** [Just-Natsuki-Team/NatsukiModDev#877]
# Overview:
I didn't get a Valentine's Day event, although Natsuki has confessed, I have the option to headpat and the option of saying 'I love you' in the main menu.

## Additional information:
Idk if it matters but I run on Windows 11 and the game's had no bugs like this so far, so I don't know why the event didn't show up. Also its I opened the game up like 15 minutes ago at around 10:07 PM (14th of February ofc).

**Comment by Blizzardsev** [comment]
Hi @yeetusnewtus - can you please provide your log (found under the log folder in your DDLC folder) as well as your persistent?

You can find your persistent by following the steps [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).

Once you have both, please attach them inside a zip/7z archive or similar.

**Comment by RaionArt** [comment]
Are you still interested in solving that issue @yeetusnewtus?

**Comment by RaionArt** [comment]
I will close this because of inactivity, feel free to reopen if you still need assistance.
