### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by HoboFloppa2** [Just-Natsuki-Team/NatsukiModDev#878]
Hi, i've trying to open DDLC with the Just Natsuki mod, i downloaded the latest release (Not source), replaced the “Game“ files from og Ddlc with the mod's one, also replaced the “Lib“ files to the Jn's files, i try to open it and it just doesn't, does anyone has an idea?

Btw, i'm on Mac, i don't have any idea of what's up with it.. Could somebody help me??
Thanks

**Comment by Blizzardsev** [comment]
Hi @HoboFloppa2 - can you please confirm if you have reviewed the thread linked to on the readme for Mac installations [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/221#issuecomment-1066030620)?

**Comment by HoboFloppa2** [comment]
> Hi @HoboFloppa2 - can you please confirm if you have reviewed and followed the steps on the thread linked to on the installation instructions on the readme for Mac installations [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/221#issuecomment-1066030620)?

Yeah i did, still couldn't tho..
I could run the Vanilla DDLC with no problem on desktop, but then, tried modding it and it just doesn't open
I don't know if you could help with screenshots or videos, anything would be useful

**Comment by HoboFloppa2** [comment]
> Hi @HoboFloppa2 - can you please confirm if you have reviewed and followed the steps on the thread linked to on the installation instructions on the readme for Mac installations [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/issues/221#issuecomment-1066030620)?

Oh nevermind, no worries, i just messed up by mixing Lib files from DDLC into the mod one's, thanks though

**Comment by Blizzardsev** [comment]
@HoboFloppa2 I'll be closing the ticket - if you experience any more issues then let us know.
