### ISSUE TITLE
[ SUPPORT REQUEST ] - You are running source (.rpy) files! Unless you know what you are doing please switch to release files.

### ISSUE THREAD

**Issue by plankys** [Just-Natsuki-Team/NatsukiModDev#881]
In the top left corner of my screen, it tells me to switch to release files, and I cannot find them. It would be awesome if you could give me a link to them, thank you!

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by SteelAxleVII** [comment]
This means that you have clicked on the “View Code” 
button. Doing that only gives you the source code, which tells you about running rpy files. You need to go to the Releases section next to the source files.

**Comment by SteelAxleVII** [comment]
![IMG_4459](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/27037292/1ad22d7c-a5ba-481e-beff-4a6cd1bec359)

This is where you’ll need to go if you don’t want the red messages. And then download the latest version.

**Comment by plankys** [comment]
Im there, but its only showing the JN installer installation.

**Comment by SteelAxleVII** [comment]
Show me you screen

**Comment by plankys** [comment]
![Screenshot_4-3-2024_204132_github com](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/162249914/3d665f92-5f94-49c3-8de9-e225f8fe2cd0)

**Comment by SteelAxleVII** [comment]
Click on jn-1.3.4.zip. You’ll need to download the vanilla version again and then paste the mod into the game folders. This will not affect Natsuki’s affection level

**Comment by plankys** [comment]
Great! Will this erase my data though?

**Comment by SteelAxleVII** [comment]
Your data stays the same. It only affects what you do in the game, not outside the game.

**Comment by SteelAxleVII** [comment]
Inside the JN, are a couple of folders. There are some folders that share the same name as the vanilla game. You’ll need to paste those to the vanilla game that have the same name.

**Comment by plankys** [comment]
So like Jn game folder into ddlc game folder?

**Comment by SteelAxleVII** [comment]
Paste the “game” folder from the JN folder to the Vanilla “game” folder. The same goes with the “lib” folder

**Comment by plankys** [comment]
Thank you so much! Have a great day.

**Comment by SteelAxleVII** [comment]
Forgot one thing. Also paste the “update” folder to the Vanilla game as well.

**Comment by plankys** [comment]
It did not work, it brought me to a new playthrough of the actual game.

**Comment by plankys** [comment]
Did not mean to close it, Sorry!

**Comment by SteelAxleVII** [comment]
Show me your game folder. Like a couple of screen shots

**Comment by plankys** [comment]
For the mod or ddlc?

**Comment by SteelAxleVII** [comment]
The mod specifically

**Comment by plankys** [comment]
[
![Screenshot (2)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/162249914/acf33116-55b3-4745-9b4b-4605c3bf1db7)
](url)

**Comment by plankys** [comment]
![Screenshot (2)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/162249914/91d7aa2e-91c1-4d18-8654-a14ea0a83b9b)

**Comment by plankys** [comment]
![Screenshot (4)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/162249914/100ae869-bf12-4282-ad4f-9c4939373fed)

**Comment by plankys** [comment]
![Screenshot (3)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/162249914/f9316252-2c30-423d-8243-26bd3548774f)

**Comment by plankys** [comment]
![Screenshot (5)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/162249914/7f817ea7-9df9-4532-a151-e9e1a5d98a73)

**Comment by plankys** [comment]
the last one jut shows that the folder named "mod assets" is on there

**Comment by SteelAxleVII** [comment]
Did you paste the mods folder to the game?

**Comment by plankys** [comment]
I just pasted the folders Game, lib and update

**Comment by SteelAxleVII** [comment]
Let me know if it works

**Comment by plankys** [comment]
I did that before but it did not work, I can try again though.

**Comment by plankys** [comment]
I tried it again and it worked! Thank you so much.
