### ISSUE TITLE
[ SUPPORT REQUEST ] - she disappeared ;-;

### ISSUE THREAD

**Issue by GCReborn** [Just-Natsuki-Team/NatsukiModDev#884]
so i was time traveling (bad ik but i wanted to say "i love you" to her) then i tried to go back a week, (original day) and she glitched out and disappeared and now the windows are glitchy and she has yet to return, im very sad

**Comment by Blizzardsev** [comment]
Hi @GCReborn - for this to take place, multiple instances of time travel must have occurred - including an explicit warning from Natsuki herself. Given this warning and our stance on cheating, we'll be closing this ticket - you may choose to start a new game if you so wish.
