### ISSUE TITLE
[ BUG REPORT ] - i keep getting this error and the game wont start. what do i do

### ISSUE THREAD

**Issue by abcdefeg** [Just-Natsuki-Team/NatsukiModDev#886]
![Screenshot 2024-03-16 005415](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/148695515/db11ab1a-6edb-4f5a-8d3c-682f688f4d7a)

it wont let me open up the game and it says please contant JN staff

**Comment by abcdefeg** [comment]
hello?

**Comment by RaionArt** [comment]
Hello @abcdefeg ,
please send your persistent forward so we can look into it. You will need to attach it here inside a zip archive so GitHub will allow it to be uploaded. Additionally please send your log file from the log folder as well.

**Comment by abcdefeg** [comment]
I fixed it myself so its good now lol
