### ISSUE TITLE
[ BUG REPORT ] - Yet another grammatical error (Daily Joke)

### ISSUE THREAD

**Issue by RZed01** [Just-Natsuki-Team/NatsukiModDev#889]
# Overview:
There is a grammatical error in one of Natsuki's Daily Jokes- specifically the one about tractors:
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149847536/2c03196b-d5f6-4cb3-b567-02363d9de02e)
I don't think the word "see" should be in this sentence. Or the word "catch", if you intend on keeping "see". But they can't both be in this sentence.

## Replication steps:
Have Natsuki randomly bring up the tractor joke, or bring it up manually.

## Additional information:
Observed on Windows 10 22H2, non-Insider Preview build.

**Comment by Blizzardsev** [comment]
Hi @RZed01 - thanks. This will be resolved in the next patch.
