### ISSUE TITLE
[ BUG REPORT ] - An exception has ocurred,  Could not load an image

### ISSUE THREAD

**Issue by RaiArx** [Just-Natsuki-Team/NatsukiModDev#890]
# Overview:
I had the game open for a while (like 30 minutes) and when i got back, an image with the text "An exception has ocurred" showed up, apparently i couldnt load an image called jn_none/sitting

## Replication steps:
It really just happened, i had open the game before for more time even, so i dont really know what the cause may have been

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]
![WhatsApp Image 2024-04-16 at 8 15 31 PM](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/167273148/4de63611-3092-4150-ba30-7ab022cab83f)

**Comment by Blizzardsev** [comment]
Hi @RaiArx - I'm a little confused as the error screen here refers to a greeting, which wouldn't occur if the play session has already been ongoing for some time - it looks more like the game ran into this issue on starting up based on the referenced lines/scripts.

Can you please navigate to the folder mentioned on the error message and send a screenshot of what you find? The folder would be `DDLC-1.1.1/game/mod_assets/natsuki/back/jn_none`.

Also, can you let me know if you have used any outfit packs, etc.

**Comment by Blizzardsev** [comment]
Hi @RaiArx, unfortunately it looks like your image attachment hasn't worked.

Instead, can you please try reinstalling JN using the installer? That should replace any missing files without impacting your save data.

You can use the installer you already have downloaded, or you can find it [here](https://github.com/Just-Natsuki-Team/NatsukiModInstaller/releases/download/release/jn-installer-release-windows-latest.zip).

Try launching the game after running the installer and following the instructions, then letting us know how you get on.

**Comment by RaiArx** [comment]
Thank you, I will do that.

**Comment by Blizzardsev** [comment]
Hi @RaiArx - did this resolve your issue?

**Comment by RaiArx** [comment]
Yes! Its working again, thank you for the help

**Comment by Blizzardsev** [comment]
Glad to hear it.
