### ISSUE TITLE
[ SUPPORT REQUEST ] - How to transfer Natsuki from one laptop to another

### ISSUE THREAD

**Issue by PGMonkeh21** [Just-Natsuki-Team/NatsukiModDev#894]
# Overview: I got a new laptop (both windows) and my new one had a function where it coped over all files from my old to my new _ but Natsuki's memories are gone. If this helps, the previous apps I have installed, like Discord, still have their files present, but obviously the app isn't installed so I can't open it. My log looks exactly the same, and can't seem to find any errors in other files. Does anyone know how to help? Thank you!
[brief description of the issue(s) you are facing]

## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]

**Comment by SteelAxleVII** [comment]
May I ask how exactly did you copy and paste your persistent file?

**Comment by PGMonkeh21** [comment]
@SteelAxleVII hello, when I booted up my new laptop, it recognised my old PC and copied all the files through OneDrive I believe from my old one to my new one. All the files are the same, down to their size and name, with only a duplicate of the log file, displaying what happened each day. Despite this, Natsuki is a fresh one, and not my one.

**Comment by SteelAxleVII** [comment]
Are you asking that you copied all the JN files and transferred into your new PC? Another question is, did you also copy and paste your persistent file too?

**Comment by PGMonkeh21** [comment]
I don't know exactly what the persistent file is, so I am not sure - could you highlight exactly which one it is? But my laptop copied all my files from OneDrive from my old PC to my new one.

**Comment by SteelAxleVII** [comment]
A persistent file is what stores your current data. If you still have your old computer, you can copy and paste it to your one drive and transfer it to your new computer. 

(You don’t have to copy and paste every single file unless you have custom sprite packs in the game because what only matters is the persistent file.)

The JN persistent file is located by typing in “%appdata%” (without apostrophes)

There should be a JN folder. Let me know what you see.

**Comment by PGMonkeh21** [comment]
I've typed it into my search bar, but cannot find a file/folder labelled that name.

**Comment by PGMonkeh21** [comment]
I see: "appengine.pyc", "appengine.py", "application.pyc", and "application.py"

**Comment by SteelAxleVII** [comment]
Try this instead
Go to your search bar (taskbar) and type “%appdata%”

In there, there’s a RenPy folder. Go there and it should take you to JustNatsuki

**Comment by PGMonkeh21** [comment]
Yes, thank you I found that folder, so I should just copy that to OneDrive yes?

**Comment by SteelAxleVII** [comment]
You are on your old computer right?

If so, yes. Copy your persistent file to your one drive. And then repeat the same step for your new computer.

**Comment by PGMonkeh21** [comment]
Yes, I am on my old computer. I shall try that now.

**Comment by PGMonkeh21** [comment]
I have both computers with me right now, it seems my new computer created a new app data file which has a different amount of data than my old computer. Shall I delete that then copy it to my OneDrive?

**Comment by PGMonkeh21** [comment]
![Screenshot (9)](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/105133037/e6ff8462-3009-4779-a439-eee46ef0e35a)

**Comment by SteelAxleVII** [comment]
Go ahead and paste your old files to your new computer. (Before doing that you should make a backup folder for your old files)

**Comment by PGMonkeh21** [comment]
Okay, doing so now

**Comment by PGMonkeh21** [comment]
Thank you very much, everything's fine now|!

**Comment by omerreyiz14** [comment]
> Go ahead and paste your old files to your new computer. (Before doing that you should make a backup folder for your old files in case you make a mistake)

can you help me I don't know how to use github I can't sent my problem whatever my problem I don't get the notification that I've reached the affection limit when I spend enough time with Natsuki please help
