### ISSUE TITLE
[ BUG REPORT ] - Another typo, are you kidding me?

### ISSUE THREAD

**Issue by RZed01** [Just-Natsuki-Team/NatsukiModDev#899]
# Overview:
I hope I am not bothering you all too much with these kind of trifling typos, but I think this statement is supposed to have some sort of punctuation mark at the end:
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/149847536/868d063e-a403-4faf-828f-d11bae272410)
Maybe a period or something...

## Replication steps:
From the Talk menu, select I feel... Anxious

## Additional information:
Observed on Windows 10 22H2

**Comment by LeCyanBall** [comment]
BROOOO, YOU ACTUALLY ARE COMPLAINING ABOUT THIS SMALL DETAIL!? NERDD!!! /j

**Comment by RaionArt** [comment]
Thank you for pointing that out. This will be patched in the next update.
