### ISSUE TITLE
I'm locked out of the JN DDLC mod.

### ISSUE THREAD

**Issue by Ziadterra** [Just-Natsuki-Team/NatsukiModDev#902]
# Overview:
I just got into the mod Just Natsuki a couple days ago and I liked it alot, and yesterday I was talking to my friend who told me how fun the reaction of Monika in monika after story was after he left her for a long while.
so I wanted to see the Natsuki reaction , So, being the impatient person i am i decided  to try and change my pc time to way forward ,
and when I opened the game Natsuki mentioned something about not messing with the pc time , so naturally , i did what any person trying to enjoy their time would do , and skipped another 10 years forward , this time she didn't mention anything fun or complain about anything , so i returned my pc time to normal , and now when i open the game she isn't even sitting there.
Now , when i read about it i found out that was done so that nobody messes with the affection system which i understand.
So , i uninstalled the game and reinstalled it , but it just put me on the very same screen, just the desk and the classroom, and a static background behind the windows.
I understand why I what I did might not be the smartest idea , but I still don't want to be permanently locked out of the game.
## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]
I'm using windows 11 , today is may 31st 2024
I skipped the system time to somewhere in December of this year when she complained about changing pc time
and then changed it to sometime in 2037 when nothing happened.

also sorry that I'm complaining about this like 6 years after the mod released but, I couldn't find anything about it online, so this is my only option.
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/80945869/1106bdeb-817e-4612-ac0a-efc9e153ee1f)
![image](https://github.com/Just-Natsuki-Team/NatsukiModDev/assets/80945869/4f810a1b-9dab-4d2e-832c-5dd955787ee4)

**Comment by RaionArt** [comment]
Hello @Ziadterra ,

Natsuki does warn you the first time if you fiddle with your time settings. She points out that you should never do that again or there might be consequences like shown above.

This is no bug as we don't tolerate any form of cheating. Feel free to clear your save file and start a new story with Natsuki. You just need to delete your persistent file found [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#can-i-back-up-my-save-data--how-do-i-find-my-persistent).

**Comment by Ziadterra** [comment]
@RaionArt  Thanks for the help , i did not intend to cheat and i was just testing out things with the mod, and I was aware of the risk of losing my save data, so thank you for helping me fix the issue.
