### ISSUE TITLE
[ FEATURE REQUEST ] - Adding more audio players to the activity system.

### ISSUE THREAD

**Issue by Appled-Dev** [Just-Natsuki-Team/NatsukiModDev#903]
# Overview:
A trio of lesser-known audio players aren't detected, so I might as well add them, right?

## Must haves:
Detection for MusicBee, AIMP, and Winamp.

## Could haves:
This doesn't apply!

## Is this feature request related to a problem? Please describe.
No problem. I thought it'd be a nice addition, as I use MusicBee.

**Comment by Blizzardsev** [comment]
This will be introduced in 1.3.5.
