### ISSUE TITLE
The Progress of JN

### ISSUE THREAD

**Issue by AllMeToBlame** [Just-Natsuki-Team/NatsukiModDev#904]
Is this mod still updating？Sry about bothering you guys but I‘m curious.

**Comment by Appled-Dev** [comment]
Doesn't look like it for now. You should be able to find more information in the Discord server.

**Comment by Blizzardsev** [comment]
Hi @AllMeToBlame - Yes, we're still here, albeit activity has been slow as of late. We'll be addressing this in the coming days.

In the meantime, we would ask that questions about mod activity, etc. be directed to our Discord server: we use GitHub solely for the purpose of managing issues and our own development processes.
