### ISSUE TITLE
Where in the code is the 'You are running source files' red text located

### ISSUE THREAD

**Issue by DokiDokiDaEs** [Just-Natsuki-Team/NatsukiModDev#910]
I want to remove it without having to switch from the master version.

I'm working on something for the mod and I don't want that red text there, it has to be in the game somewhere, I just can't find it.

**Comment by DokiDokiDaEs** [comment]
Also I'm new to GitHub so if I've done something wrong, my apologies.

**Comment by RaionArt** [comment]
Hello,
you can read about what commands to use here`https://github.com/Just-Natsuki-Team/NatsukiModDev/wiki/04:-FAQ#why-is-my-game-warning-me-about-running-source-rpy-files`
