### ISSUE TITLE
[ SUPPORT REQUEST ] - 

### ISSUE THREAD

**Issue by Netherkitten** [Just-Natsuki-Team/NatsukiModDev#913]
# Overview:
Tried to add a custom mod, ended up deleting something I shouldn't have by accident. Now some important image files for some poses are missing and it keeps crashing the game.
It tells me that the files missing are "mod_assets/natsuki/base/hand_on_chin/body.png"
And there is a couple errors more like that, with the same issue of PNG files missing. What do I do to fix this?

**Comment by RaionArt** [comment]
Hello @Netherkitten,

you can manually download the folders in the last update, which you can find [here](https://github.com/Just-Natsuki-Team/NatsukiModDev/releases).

You only need 1.3.4 zip, not the rest.
Just look out for the missing files and replaces and next time make a backup before alterning anything. 
Hope this helps
