### ISSUE TITLE
[ SUPPORT REQUEST ] - Natsuki doesn't celebrate christmas

### ISSUE THREAD

**Issue by maxizfa** [Just-Natsuki-Team/NatsukiModDev#920]
# Overview:
[brief description of the issue(s) you are facing]
natsuki doesn' want to celebrate christmas and im pretty sure that i have the enough affection to celebrate it
## Additional information:
[any other information you think is relevant - I.E operating system, date and so on]
23/12/24, windows 11 (custom OS)

**Comment by Blizzardsev** [comment]
Hi @maxizfa - apologies, are you sure it is in fact Christmas yet in your region?

**Comment by maxizfa** [comment]
we are just 1 day to really celebrate christmas, but it has to be the day for her to put decoration? or just the month itself

**Comment by RaionArt** [comment]
She only celebrates on the 24th and 25th

**Comment by maxizfa** [comment]
okay, thanks for the quick support  and replying, have a nice day/night or evening!
